import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import * as g from '../game/engine.ts';
const { fixtures } = JSON.parse(
  readFileSync(new URL('./fixtures/classic-replay.json', import.meta.url)),
);
const operations = {
  move: g.move,
  castSkill: g.castSkill,
  endTurn: g.endTurn,
  enterRoom: g.enterRoom,
  buy: g.buy,
  leaveRoom: g.leaveRoom,
  chooseReward: g.chooseReward,
};
// Golden results generated by pre-v0.2 commit 994b9a7, not the code under test.
test('real classic saves replay the exact pre-v0.2 combat, RNG, prices and rewards', () => {
  for (const { label, input, actions, sha256 } of fixtures) {
    let s = g.loadSave(input);
    assert.ok(s, label);
    assert.equal(s.rulesVersion, undefined);
    const results = [];
    for (const [fn, ...args] of actions) {
      const r = operations[fn](s, ...args);
      assert.equal(r.error, undefined, label);
      results.push(g.copy(r));
      s = r.state;
    }
    assert.equal(
      createHash('sha256').update(JSON.stringify(results)).digest('hex'),
      sha256,
      label,
    );
  }
});
