import type { SpriteDef } from '../sprite.ts';

/**
 * Card icons, 18×18, one frame each, anchored at the centre (9, 9).
 * Each board tile is a card of the deck: the board draws the family card
 * (red «Удар», blue «Защита», violet «Чернила», gold «Бухгалтерия», grey status)
 * and one of these icons on top of it.
 * Light: warm key from the upper left, cold rim on the right edge, shadows cold.
 *
 * Shared legend (one char per palette colour, same letters as items.ts):
 *   k ink0  j ink1  n ink2  N ink3        1..6 cold1..cold6
 *   = teal0 7 teal1 8 teal2 9 teal3 t teal4 T teal5
 *   0 vio0  v vio1  V vio2  i vio3  I vio4  l vio5
 *   M red0  m red1  x red2  r red3  R red4  P red5
 *   U orange1 u orange2 o orange3 O orange4
 *   A gold1 a gold2 z gold3 Z gold4 W cream
 *   % wood0 b wood1 B wood2 c wood3 C wood4
 *   & green0 f green1 F green2 e green3 E green4
 *   D grey0 d grey1 G grey2 g grey3 y grey4 Y white w paper q paper2
 *   Q skin0 S skin1 s skin2 L skin3
 *   h beige0 H beige1 J beige2 K beige3
 */
const legend: Record<string, string> = {
  '.': '',
  k: 'ink0', j: 'ink1', n: 'ink2', N: 'ink3',
  1: 'cold1', 2: 'cold2', 3: 'cold3', 4: 'cold4', 5: 'cold5', 6: 'cold6',
  '=': 'teal0', 7: 'teal1', 8: 'teal2', 9: 'teal3', t: 'teal4', T: 'teal5',
  0: 'vio0', v: 'vio1', V: 'vio2', i: 'vio3', I: 'vio4', l: 'vio5',
  M: 'red0', m: 'red1', x: 'red2', r: 'red3', R: 'red4', P: 'red5',
  U: 'orange1', u: 'orange2', o: 'orange3', O: 'orange4',
  A: 'gold1', a: 'gold2', z: 'gold3', Z: 'gold4', W: 'cream',
  '%': 'wood0', b: 'wood1', B: 'wood2', c: 'wood3', C: 'wood4',
  '&': 'green0', f: 'green1', F: 'green2', e: 'green3', E: 'green4',
  D: 'grey0', d: 'grey1', G: 'grey2', g: 'grey3', y: 'grey4', Y: 'white', w: 'paper', q: 'paper2',
  Q: 'skin0', S: 'skin1', s: 'skin2', L: 'skin3',
  h: 'beige0', H: 'beige1', J: 'beige2', K: 'beige3',
};

const icon = (rows: string[]): SpriteDef => ({ w: 18, h: 18, legend, frames: { idle0: rows }, ox: 9, oy: 9 });

export const CARD_ICONS: Record<string, SpriteDef> = {
  // ── Удар (red) ──────────────────────────────────────────────────────

  // Кулак — a raised fist with a shirt cuff.
  card_fist: icon([
    '..................',
    '....kk.kk.kk......',
    '...kLskLskLskkk...',
    '...kLsSLsSLsSLsk..',
    '...kLsSLsSLsSLsSk.',
    '...kLsSLsSLsSLsSk.',
    '...kLsSLsSLsSLsSk.',
    '..kkkkkkkkkQQQQQk.',
    '.kLLLLLLWWksSLsSk.',
    '.kssssssssksSLsSk.',
    '.kSSSSSSSSkSQSSQk.',
    '..kSSkkkkkkSSSSk..',
    '...kLssssssssSk...',
    '...kkkkkkkkkkkk...',
    '...kWWWwwwwzw5k...',
    '...kwwwwwwwww5k...',
    '...kqqqqqqqqqqk...',
    '...kkkkkkkkkkkk...',
  ]),
  // Дырокол — a two-hole punch, front view, dropping paper confetti.
  card_punch: icon([
    '......kkkkkk......',
    '...kkkYYYYYYkkk...',
    '.kkYYYyyyyyyyyykk.',
    'kYyyyyyyyyyyyyyy5k',
    'kgggggggggggggggGk',
    '.kkkkkkkkkkkkkkkk.',
    '..kYyygk..kYyygk..',
    '..kyyggk..kyyggk..',
    '.kkGGGGkkkkGGGGkk.',
    'kYwwwwwwwwwwwwwwqk',
    'kGGGGGGGGGGGGGGGdk',
    '.kkkkkkkkkkkkkkkk.',
    '..................',
    '....kk......kk....',
    '...kYwk.kk.kYwk...',
    '...kwqkkYwkkwqk...',
    '....kk.kwqk.kk....',
    '........kk........',
  ]),
  // Красная ручка — a red ballpoint with a white clip; a red drop hangs from the tip.
  card_redpen: icon([
    '.............kk...',
    '............kPRk..',
    '...........kPRrxk.',
    '..........kYRrxk..',
    '.........kYRrxk...',
    '........kYRrxk....',
    '.......kxmmMk.....',
    '......kxmmMk......',
    '.....kYygkk.......',
    '....kYgkk.........',
    '....kGk...........',
    '....kRk...........',
    '...kRrxk..........',
    '..kRrrxxk.........',
    '..kPrrrxk.........',
    '..kPrrxxk.........',
    '...kxxxk..........',
    '....kkk...........',
  ]),
  // Точилка — a green pencil going into a steel sharpener; a curled shaving lies beside it.
  card_sharpener: icon([
    '..................',
    '.kkk..............',
    'kPPRk.............',
    'kPRRxk............',
    '.kRxxgk...........',
    '..kYyggk..........',
    '...kFeeEk.........',
    '....kFeeEkkkkkkkk.',
    '.....kFeeEdYYYY5k.',
    '......kFeeEdyyy5k.',
    '..kkk..kddFeyyy5k.',
    '.keOCk.kYGddyyy5k.',
    'keOkkk.kYyyyyyy5k.',
    'kOk....kYyggggG5k.',
    'keCkk..kYyGGGGG5k.',
    '.keOCk.kgggggggGk.',
    '..kkk..kkkkkkkkkk.',
    '..................',
  ]),
  // Кнопки — three push pins: yellow, white and teal heads.
  card_pins: icon([
    '..................',
    '............kkkkk.',
    '.kkkkk.....kTTTt9k',
    'kZZZzak....kTttt9k',
    'kZzzzak.....kkkkk.',
    '.kkkkk.......ktk..',
    '..kzk.......kTt9k.',
    '.kZzakkkkkk.kkkkk.',
    '.kkkkkYYYygk.kyk..',
    '..kykkYyyygk.kyk..',
    '..kyk.kkkkk...k...',
    '...k...kyk........',
    '......kYygk.......',
    '......kkkkk.......',
    '.......kyk........',
    '.......kyk........',
    '........k.........',
    '..................',
  ]),
  // Ножницы — open office scissors with orange loops.
  card_scissors: icon([
    '..................',
    '..kkkk............',
    '.kOOOok........kk.',
    'kOokkouk......kYyk',
    'kOk..kuk.....kYyk.',
    'kok..kuk...kkYyk..',
    'koukkuUk..kYyyk...',
    '.kuuUuukkkYyyk....',
    '..kkkkuoYyygk.....',
    '......kOdyYk......',
    '..kkkkOoygyYk.....',
    '.kOOOoukkkgyYk....',
    'kOokkouk..kgyYk...',
    'kOk..kuk...kgyYk..',
    'kok..kuk....kkgYk.',
    'koukkuUk......kgYk',
    '.kuuUUk........kk.',
    '..kkkk............',
  ]),
  // Линейка — a wooden ruler with tick marks.
  card_ruler: icon([
    '..................',
    '.....k............',
    '....kWk...........',
    '...kOBWk..........',
    '..kOOOOWk.........',
    '.kcCOOOBWk........',
    '..kcCOBOOWk.......',
    '...kcCOOOBWk......',
    '....kcCOOOOWk.....',
    '.....kcCOOOBWk....',
    '......kcCOBOOWk...',
    '.......kcCOOOBWk..',
    '........kcCOOOOWk.',
    '.........kcCOOOOk.',
    '..........kcCOOk..',
    '...........kcCk...',
    '............kk....',
    '..................',
  ]),
  // Степлер — a steel stapler with its jaw open.
  card_stapler: icon([
    '..................',
    '..................',
    '..................',
    '............kkkk..',
    '..........kkYyyyk.',
    '.......kkkYyyyy5k.',
    '.....kkYYyyyyyg5k.',
    '...kkYyyyyyggGGk..',
    '.kkYyyyyygGGdddk..',
    'kYyyyyygGGddkkk...',
    'kyyygGGddkkk.kYk..',
    'kyggdddkkkkkkkYk..',
    'kggggggggggYYYYk..',
    'kGGGGGGGGGGGGG4k..',
    'kddddddddddddddk..',
    '.kkkkkkkkkkkkkk...',
    '..................',
    '..................',
  ]),
  // Шило — a pear-shaped wooden handle and a long steel spike.
  card_awl: icon([
    '......kkkkk.......',
    '.....kOOCCck......',
    '....kOWCCCcBk.....',
    '....kOCCCcBBk.....',
    '....kCCCCcBBk.....',
    '.....kCCccBk......',
    '......kccBk.......',
    '......kZzak.......',
    '......kzaAk.......',
    '.......kYgk.......',
    '.......kYgk.......',
    '.......kYgk.......',
    '.......kYgk.......',
    '.......kYgk.......',
    '.......kYk........',
    '.......kYk........',
    '........k.........',
    '..................',
  ]),
  // Резак — a yellow box cutter with a snap-off blade.
  card_cutter: icon([
    '..................',
    '..................',
    '..................',
    '..................',
    '......kkk.........',
    '.....kgYgk........',
    '.kkkkkGdGkkk......',
    'kZZZZZZZZZZkkkk...',
    'kzzzzzzzzzagYYk...',
    'kzzzzzzzzzaygyyk..',
    'knNnNnNzzzayygyyk.',
    'knNnNnNaaaAyyygyGk',
    'kAAAAAAAAAAkkkkkkk',
    '.kkkkkkkkkk.......',
    '..................',
    '..................',
    '..................',
    '..................',
  ]),
  // Тревожная кнопка — a big red button on a hazard-striped box.
  card_alarm: icon([
    '..................',
    '.W.....kkkk.....W.',
    '..W..kkPPRRkk..W..',
    '....kPPRRRRRrk....',
    '...kPRRRRRRRrrk...',
    '...kRRRRRRRRrxk...',
    '...kxRRRRRRRrxk...',
    '...kxxrrrrrrxxk...',
    '..kkkkkkkkkkkkkk..',
    '..kYyyyyyyyyyyGk..',
    '.kkkkkkkkkkkkkkkk.',
    '.kZZZZZZZZZZZZZzk.',
    '.kzzNNzzNNzzNNzak.',
    '.kzNNzzNNzzNNzzak.',
    '.kNNzzNNzzNNzzNak.',
    '.kkkkkkkkkkkkkkkk.',
    '..................',
    '..................',
  ]),

  // ── Защита (blue) ──────────────────────────────────────────────────

  // Папка — a closed manila folder with a tab, a sheet peeking out, a label on the flap.
  card_folder: icon([
    '..................',
    '..................',
    '..kkkkk...........',
    '.kKKKKJk...kkkkk..',
    '.kKJJJJJkkkYwwwqk.',
    '.kKJJJJJJJkwwwwqk.',
    '.kkkkkkkkkkkkkkkk.',
    '.kKKKKKKKKKKKKKJk.',
    '.kKJJJJJJJJJJJJHk.',
    '.kKJwwwwwwwJJJJ4k.',
    '.kKJwggggwwJJJJ4k.',
    '.kKJwwwwwwwJJJJ4k.',
    '.kKJJJJJJJJJJJJ4k.',
    '.kKJJJJJJJJJJJJHk.',
    '.kHHHHHHHHHHHHHHk.',
    '.kkkkkkkkkkkkkkkk.',
    '..................',
    '..................',
  ]),
  // Скоросшиватель — a stuffed box binder: label, finger ring and a steel clasp on the cover.
  card_binder: icon([
    '..................',
    '.......kkkkkkkkk..',
    '....kkkwwwwwww34k.',
    '..kkwwwwwww33334k.',
    '.k54444423333334k.',
    '.k5YYYYY23333334k.',
    '.k5wgggw2333kkkkk.',
    '.k5wggww233kYyygk.',
    '.k5wwwww233kydygk.',
    '.k54444423kYyyyyk.',
    '.k54yYy423kyggggk.',
    '.k5yNNNg233kkkkkk.',
    '.k5yNNNg23333334k.',
    '.k54ggg423333334k.',
    '.k54444423333334k.',
    '.k544444233334kk..',
    '.kggggggg34kkk....',
    '..kkkkkkkkk.......',
  ]),
  // Файлик — a clear sheet protector: punched strip, a page inside, a glare.
  card_sleeve: icon([
    '.kkkkkkkkkkkkkkk..',
    '.k5555555555664k..',
    '.k522YYYYYYY6w6k..',
    '.k5k2Ywwwww6wq4k..',
    '.k522YGGGG6wwq3k..',
    '.k522Ywwwwwwwq3k..',
    '.k522Yggggggwq3k..',
    '.k5k2Ywwwwwwwq3k..',
    '.k522Ygggggwwq3k..',
    '.k522Ywwwwwwwq3k..',
    '.k522Yggggggwq3k..',
    '.k5k2Ywwwwwwwq3k..',
    '.k522Ygggwwwwq3k..',
    '.k522Ywwwwwwwq3k..',
    '.k522qqqqqqqqq3k..',
    '.k5k22222222223k..',
    '.k5222222222223k..',
    '.kkkkkkkkkkkkkkk..',
  ]),
  // Зонтик — a half-open umbrella with a wooden crook handle.
  card_umbrella: icon([
    '........kk........',
    '.......k54k.......',
    '......k6543k......',
    '.....k655432k.....',
    '....k65554332k....',
    '....k65554332k....',
    '...k6655443322k...',
    '...k6655443322k...',
    '..k6kkkk43kkkk2k..',
    '...k...kgGk...k...',
    '.......kgGk.......',
    '.......kgGk.......',
    '.......kgGk.......',
    '..k....kCck.......',
    '.kCk...kCck.......',
    '.kCkkkkkCck.......',
    '.kcCCCCCcck.......',
    '..kkkkkkkk........',
  ]),
  // Картотечный ящик — a filing drawer pulled out, folders with coloured tabs.
  card_drawer: icon([
    '........kk........',
    '....kk.kEek.......',
    '...kRrkkEek.kk....',
    '...kRrkYwwqkZzk...',
    '..kKJJHYwwqkZzk...',
    '.kgKJJHYwwqKJHGk..',
    '.kgKJJHYwwqKJHGk..',
    '.kgKJJHYwwqKJHGk..',
    '.kNNNNNNNNNNNNNk..',
    'kYYYYYYYYYYYYYY5k.',
    'kYyyyygwwwgyyyy5k.',
    'kYyyyygqqqgyyyy5k.',
    'kYyyyyyyyyyyyyy5k.',
    'kYyyyYYYYYYYyyy5k.',
    'kYyyyGGGGGGGyyy5k.',
    'kgggggggggggggg5k.',
    '.kkkkkkkkkkkkkkk..',
    '..................',
  ]),
  // Ламинатор — a beige laminator feeding out a glossy sheet.
  card_laminator: icon([
    '..................',
    '..................',
    '..kkkkkkkkkkkkkk..',
    '.kKKKKKKKKKKKKKJk.',
    '.kJJJJJJJJJJJRJHk.',
    '.kHHHHHHHHHHHHHHk.',
    '.kJJJJJJJJJJJJJ4k.',
    '.kJkkkkkkkkkkkJ4k.',
    '.kHk566666666kHHk.',
    '.kkk5wwwwww66kkkk.',
    '...k5wggggw65k....',
    '...k5wwwww6w5k....',
    '...k5wggg6ww5k....',
    '...k5www6www5k....',
    '...k5ww6wwww5k....',
    '...k555555555k....',
    '...kkkkkkkkkkk....',
    '..................',
  ]),
  // Архивная коробка — a kraft archive box with a lid, label and hand hole.
  card_archivebox: icon([
    '..................',
    '..kkkkkkkkkkkkkk..',
    '.kWOOOOOOOOOOOOCk.',
    '.kOOOOOOOOOOOOCck.',
    'kCCCCCCCCCCCCCCc5k',
    'kcccccccccccccccBk',
    '.kkkkkkkkkkkkkkkk.',
    '..kOCCCCCCCCCCck..',
    '..kOCwwwwwwwCC4k..',
    '..kOCwggggwwCC4k..',
    '..kOCwwwwwwwCC4k..',
    '..kOCqqqqqqqCC4k..',
    '..kOCCCCCCCCCC4k..',
    '..kOCCCkkkkCCC4k..',
    '..kOCCCCCCCCCC4k..',
    '..kcccccccccccck..',
    '..kkkkkkkkkkkkkk..',
    '..................',
  ]),
  // Бронежилет из папок — a vest of two folders held together with silver tape.
  card_vest: icon([
    '...kkk......kkk...',
    '..kKJJk....kKJJk..',
    '..kKJJJk..kKJJHk..',
    '..kKJJJk..kJJJHk..',
    '.kKJJJJJkkJJJJJHk.',
    'kKJJJJJJkkJJJJJJHk',
    'kKJJJJJJHJJJJJJJ4k',
    'kKJwwwJJHJJJJJJJ4k',
    'kKJwggJJHJJJJJJJ4k',
    'kYYYYYYYYYYYYYYY5k',
    'kgggggggggggggggGk',
    'kKJJJJJJHJJJJJJJ4k',
    'kKJJJJJJHJJJJJJJ4k',
    'kYYYYYYYYYYYYYYY5k',
    'kgggggggggggggggGk',
    'kHHHHHHHHHHHHHHHHk',
    '.kkkkkkkkkkkkkkkk.',
    '..................',
  ]),
  // Планшет — a clipboard raised like a shield: board, steel clip, notes.
  card_clipboard: icon([
    '..................',
    '......kkkkkk......',
    '..kkkkYYyyygkkkk..',
    '.kCCCkYyyyygkCcBk.',
    '.kCCCkyyyyGGkCcBk.',
    '.kCCYkkkkkkkkqc4k.',
    '.kCCYwwwwwwwwqc4k.',
    '.kCCYwggggggwqc4k.',
    '.kCCYwwwwwwwwqc4k.',
    '.kCCYwggggwwwqc4k.',
    '.kCCYwwwwwwwwqc4k.',
    '.kCCYwgggggwwqc4k.',
    '.kCCYwwwwwwwwqc4k.',
    '.kCCYwggwwwwwqc4k.',
    '.kCCYwwwwwwwwqc4k.',
    '.kCCqqqqqqqqqqc4k.',
    '.kcccccccccccccBk.',
    '..kkkkkkkkkkkkkk..',
  ]),

  // ── Чернила (violet) ───────────────────────────────────────────────

  // Чернила — a square ink bottle: black cap, violet ink, a drop on the label.
  card_ink: icon([
    '..................',
    '......kkkkkk......',
    '.....kgGGGGdk.....',
    '.....kGddddDk.....',
    '.....kkkkkkkk.....',
    '.....kYVVVV5k.....',
    '...kkYVVVVVV5kk...',
    '..kYVVVVVVVVVV5k..',
    '..kYllllllllll5k..',
    '..kYIIIIIIIIIi5k..',
    '..kYiWWWIWWWii5k..',
    '..kYiWWIiiWWiV5k..',
    '..kYiWIiiiVWiV5k..',
    '..kYiWIiiVVWiV5k..',
    '..kYiqqVVVqqiV5k..',
    '..kYiiiiiiiiiV5k..',
    '..kVVVVVVVVVVVVk..',
    '...kkkkkkkkkkkk...',
  ]),
  // Корректор — a white correction pen blotting out a line of ink.
  card_corrector: icon([
    '..............k...',
    '.............kYkk.',
    '............kYY66k',
    '...........kIIi66k',
    '..........kIIiiVgk',
    '.........kYYiiVgk.',
    '........kYY66ygk..',
    '.......kYY66ygk...',
    '......kYY66ygk....',
    '.....kYY66ygk.....',
    '....kYyg6ygk......',
    '....kyggGgk.......',
    '....kggGgk........',
    '....kGkkk.........',
    '..kkYk..kkkkkk....',
    '.kYYYYkkIiIiIik...',
    '.kYY66kkkkkkkk....',
    '..kkkk............',
  ]),
  // Печать «Срочно» — a wooden rubber stamp over a fresh red «!» imprint.
  card_urgent: icon([
    '...........kkkk...',
    '..........kOCCck..',
    '..........kCccBk..',
    '...........kcBk...',
    '...........kcBk...',
    '.........kkkkkkkk.',
    '.........kOCCCCck.',
    '.........kcccccBk.',
    '..........kxRRxk..',
    'kkkkkkkkkkkkkkkkkk',
    'kWwwRrwwwwwwwwww5k',
    'kwwwRrwwwGGGGGww5k',
    'kwwwRrwwwwwwwwww5k',
    'kwwwRrwwwGGGGwww5k',
    'kwwwwwwwwwwwwwww5k',
    'kwwwRrwwwGGGGGww5k',
    'kwwwxxwwwwwwwwww5k',
    'kkkkkkkkkkkkkkkkkk',
  ]),
  // Клякса — a menacing ink splat with angry eyes and a toothy grin.
  card_blotcurse: icon([
    '.........kk.......',
    '..k.....kIik......',
    '.kIk....kIik...kk.',
    '.kIik..kkIik..kIik',
    '..kIikkIIiikkkiVk.',
    '..kIIIiiiiiiikVk..',
    '...kIkiiiiiikik...',
    '..kIIikkiikkiiVk..',
    '..kIiYYYiiYYYiVk..',
    '.kiiiYYkiikYYiiVk.',
    '.kiiiiiiiiiiiiVVk.',
    '..kiikkkkkkkkiVk..',
    '..kikYkYkYkYkVVk..',
    '..kiikkkkkkkVVkk..',
    '.kiiiiiiiiVVVkVVk.',
    '.kiVkkkkikkkkkiVVk',
    '.kVk...kVk....kkVk',
    '..k.....k.......k.',
  ]),
  // Перо — a white quill, its nib dipped in violet ink.
  card_quill: icon([
    '..............kkk.',
    '............kkYqwk',
    '..........kkYYqwk.',
    '........kkYYYqwqk.',
    '.......kYYWYqwwk..',
    '......kYYYYqwqwk..',
    '.....kYYWYqwwwk...',
    '....kYYYYqwqkk....',
    '....kYYWqwwk......',
    '....kYYqwkk.......',
    '....kYqkk.........',
    '....kWk...........',
    '...kWk............',
    '..kIk.............',
    '.kik..............',
    '.kIk..............',
    'kIiik.............',
    '.kkk..............',
  ]),
  // Штамп «Копия» — a self-inking stamp and its two identical violet squares.
  card_copystamp: icon([
    '....kkkkkkkkkk....',
    '...kYYyyyyyyygk...',
    '...kyggggggggGk...',
    '...kkkkkkkkkkkk...',
    '....kGlIIIIiGk....',
    '....kdGGGGGGdk....',
    '...kkkkkkkkkkkk...',
    '...kIIiiiiiiiVk...',
    '....kkkkkkkkkk....',
    '.kkkkkkkkkkkkkkkk.',
    '.kWwwwwwwwwwwww5k.',
    '.kwwiiiiiwwwwww5k.',
    '.kwwiwwwiwwwwww5k.',
    '.kwwiwwiiiiiwww5k.',
    '.kwwiwwiwwwiwww5k.',
    '.kwwiiiiwwwiwww5k.',
    '.kwwwwwiiiiiwww5k.',
    '.kkkkkkkkkkkkkkkk.',
  ]),
  // Копирка — carbon paper between two sheets: the copy comes out violet.
  card_carbon: icon([
    '......kkkkkkkkkkk.',
    '......kWwwwwwww5k.',
    '......kwIIIIIIw5k.',
    '...kkkkkkkkkkkw5k.',
    '...kN3NNNNNNNkw5k.',
    '...kNN3NNNNNNkI5k.',
    'kkkkkkkkkkkNNkw5k.',
    'kYYYYYYYYYkNNkw5k.',
    'kYGGGGGGw5kNNkq5k.',
    'kYwwwwwww5k3Nkkkk.',
    'kYGGGGGww5kNNk....',
    'kYwwwwwww5kNNk....',
    'kYGGGGGGw5kNNk....',
    'kYwwwwwww5kkkk....',
    'kYGGGwwww5k.......',
    'kYwwwwwww5k.......',
    'kqqqqqqqqqk.......',
    'kkkkkkkkkkk.......',
  ]),
  // Пресс-папье — a glass paperweight dome with a millefiori flower, on papers.
  card_weight: icon([
    '..................',
    '..................',
    '.......kkkk.......',
    '.....kkYYlIkk.....',
    '....kYlllIIIik....',
    '...kYllIIIIIiik...',
    '...kYlIIITIii6k...',
    '..kYllIITZTiii6k..',
    '..kYllITZWZTii6k..',
    '.kllIIIITZTiiVV6k.',
    '.klIIIIiiTiiVVVVk.',
    '.klIIIiiiiiVVVVVk.',
    'kklIIiiiiVVVVVVVkk',
    'kYqqqqqqqqqqqqqqYk',
    'kwwwwwwwwwwwwwwwqk',
    'kqqqqqqqqqqqqqqqqk',
    'kkkkkkkkkkkkkkkkkk',
    '..................',
  ]),

  // ── Бухгалтерия (gold) ─────────────────────────────────────────────

  // Скрепка — a steel paper clip.
  card_clip: icon([
    '.....kkk..........',
    '....kYYYk.........',
    '...kygggyk........',
    '..kygkkkgyk.......',
    '..kyk...kyk.......',
    '..kyk.kkkYgk......',
    '..kYgkYykkyk......',
    '...kykkygkYgk.....',
    '...kYgkYykkyk.....',
    '....kykkygkYgk....',
    '....kYgkYykkyk....',
    '.....kykkygkYgk...',
    '.....kYgkYykkyk...',
    '......kykkyYYyk...',
    '......kYgkkyyk....',
    '.......kyk.kk.....',
    '.......kYgk.......',
    '........kk........',
  ]),
  // Монетка — a gold coin with a raised rim and a star.
  card_coin: icon([
    '.......kkkk.......',
    '.....kkWWWZkk.....',
    '....kWWWWWZZZk....',
    '...kWWaaaaaaZZk...',
    '..kWWaazzzzazZzk..',
    '.kWWazzzzzzzzzzzk.',
    '.kWWazzzzWzzzzzzk.',
    '.kWazzzzWWZzzzZzk.',
    '.kWazzzWWWZazzZak.',
    '.kWazzzzWZazzzZak.',
    '.kZazzzzWzazzzZak.',
    '.kZZazzzzzzzzZaak.',
    '.kZZzzzzzzzzzZaak.',
    '..kZZzzzzzzZZaak..',
    '...kZzzZZZZZaak...',
    '....kzzzaaaaak....',
    '.....kkzaaakk.....',
    '.......kkkk.......',
  ]),
  // Чек — a torn-off receipt, curling at the bottom.
  card_receipt: icon([
    '.....k.k.k.k......',
    '....kWkWkWkWkk....',
    '....kWwwwwwwwk....',
    '....kWGGGGGwwk....',
    '....kWwwwwwwwk....',
    '....kWggwwgggk....',
    '....kWwwwwwwwk....',
    '....kWggwwwggk....',
    '....kWwwwwwwwk....',
    '....kWgggwwggk....',
    '....kWwwwwwwwk....',
    '....kWqwqwqwqk....',
    '....kWGGGwwGGk....',
    '....kWwwwwwwwk....',
    '....kqqqqqqqqk....',
    '....kyyyyyyyyk....',
    '.....kqqqqqqk.....',
    '......kkkkkk......',
  ]),
  // Премия — an envelope stuffed with a banknote, red seal.
  card_bonus: icon([
    '..................',
    '....kkkkkkkkkk....',
    '....kFFFFFFFFk....',
    '...kkFEEEEEEFkk...',
    '..kWkFEEeeEEFkqk..',
    '.kWWkFEeWWeEFkqqk.',
    'kWWwkFEEeeEEFkwqqk',
    'kWwwkFEEEEEEFkwwqk',
    'kkkkkkkkkkkkkkkkkk',
    'kqqWWWWWWWWWWWWq5k',
    'kWWqqWWWWWWWWqqw5k',
    'kWWWWqqWWWWqqwww5k',
    'kWWWWWWqRrqwwwww5k',
    'kwwwwwwwrxwwwwww5k',
    'kwwwwwwwwwwwwwww5k',
    'kqqqqqqqqqqqqqqqqk',
    'kkkkkkkkkkkkkkkkkk',
    '..................',
  ]),
  // Кредитка — a teal corporate card with a gold chip.
  card_card: icon([
    '..................',
    '..................',
    '..................',
    '..kkkkkkkkkkkkkk..',
    '.kTTTTTTTTTTTTt9k.',
    '.kTtttttttttYtt5k.',
    '.kTtZZzatttYYtt5k.',
    '.kTtZaazttttttt5k.',
    '.kTtzzaAtttttt95k.',
    '.kTttttttttttt95k.',
    '.kTtYYtYYtYYtY95k.',
    '.kTttttttttttt95k.',
    '.kTtWWWWtttttt95k.',
    '.k99999999999988k.',
    '..kkkkkkkkkkkkkk..',
    '..................',
    '..................',
    '..................',
  ]),
  // Копилка — a pink piggy bank swallowing a coin.
  card_piggy: icon([
    '..................',
    '..........kkk.....',
    '.........kWZak....',
    '.........kWZak....',
    '.......k.kWZak....',
    '......kPkkWZak..k.',
    '.....kPRPkkkkkkkRk',
    '....kLPRRPPPPPPkRk',
    '...kLLLPPPPPPPPPkk',
    '..kLLPPPPPPPPPPPRk',
    '.kPPPPkPPPPPPPPPk.',
    '.kxPPPPPPPPPPPRRk.',
    '.kxPRPPPPPPPRRRRk.',
    '.kPRPPPPPPRRRRxk..',
    '..kkkPPRRRRRxxk...',
    '....kPRkRRxxPRk...',
    '....kPRkkkkkPRk...',
    '.....kk.....kk....',
  ]),
  // Квартальный отчёт — a report whose chart arrow breaks out of the page.
  card_report: icon([
    '.............kkkk.',
    '............kEEEEk',
    '.kkkkkkkkkk..kEeek',
    'kWWWWWWWWWqkkEeeFk',
    'kWwwwwwwwwqkeekeFk',
    'kWwGGGGGwwkeek.kFk',
    'kWwwwwwwwwekkk..k.',
    'kWwgggwwweww5k....',
    'kWwwwwwwweww5k....',
    'kWwwwewwezaw5k....',
    'kWwweweewzaw5k....',
    'kWwewzawwzaw5k....',
    'kWewwzazazaw5k....',
    'kWwzazazazaw5k....',
    'kWwzazazazaw5k....',
    'kWwzazazazaw5k....',
    'kqqqqqqqqqqqqk....',
    '.kkkkkkkkkkkk.....',
  ]),
  // Золотая скрепка — the rare multiplier: a shining gold clip with sparkles.
  card_goldclip: icon([
    '..........kkk.....',
    '.........kWWWk....',
    '...W....kZzzZzk...',
    '...W...kZzkkkZzk..',
    '.WWYWW.kZk...kZk..',
    '...W..kWzkkk.kZk..',
    '...W..kZkkWZkWzk..',
    '.....kWzkZzkkZk...',
    '.....kZkkWZkWzk...',
    '....kWzkZzkkZk....',
    '....kZkkWZkWzk....',
    '...kWzkZzkkZk.....',
    '...kZkkWZkWzk.....',
    '...kWZWZkkZk......',
    '....kZZkkWzk..W...',
    '.....kk.kZk..WYW..',
    '.......kWzk...W...',
    '........kk........',
  ]),

  // ── Status (grey) ──────────────────────────────────────────────────

  // Волокита — a bundle of yellowed papers tied with red string under a wax seal (a dead tile enemies slip in).
  card_redtape: icon([
    '..................',
    '........k.k.......',
    '...kkkkkrkrkkkkk..',
    '..kwwwwwwrwwwwwwk.',
    '..kwwgggwrwgggwk..',
    '.kwwwwwwwrwwwwwk..',
    '.kwKKKKKKrKKKKKJk.',
    '.kkKJJJJJrJJJJJJJk',
    'kwKKKKKKKrKKKKJkk.',
    '.kKJJJJJkkkJJJJJk.',
    '.kwKKKKkRRrkKKKKJk',
    'krrrrrrkRxrkrrrrrk',
    '.kkwKKKkxrxkKKKJk.',
    'kKJJJJJJkkkJJJJkk.',
    '.kwKKKKKKrKKKKKKJk',
    '.kKJJJJJJrJJJJJJk.',
    '..kkkkkkkkkkkkkk..',
    '..................',
  ]),
};
