import type { SpriteDef } from '../sprite.ts';

/**
 * Cast: unlockable heroes, the merchant Savva and room props.
 * Same rules as the style anchor (hero.ts): warm key light from the upper left, cold rim
 * on the right, cold shadows, 1px ink0 outline, 2–3 tones per material.
 */

function shiftDown(rows: string[], from: number): string[] {
  const out = rows.slice();
  const w = rows[0].length;
  for (let y = from; y > 0; y--) out[y] = rows[y - 1];
  out[0] = '.'.repeat(w);
  return out;
}

// ---------------------------------------------------------------------------
// Intern — improved "item get" pose (same palette letters as hero_intern).
const internLegend = {
  '.': '',
  k: 'ink0',
  h: 'ink2',
  H: 'cold2',
  s: 'skin2',
  S: 'skin1',
  L: 'skin3',
  c: 'cold5',
  w: 'paper',
  W: 'cream',
  q: 'paper2',
  r: 'red3',
  R: 'red1',
  p: 'cold1',
  P: 'ink3',
  b: 'wood1',
  B: 'wood2',
  m: 'red1',
  Y: 'white',
};

const internHold = [
  '.kkkk........kkkk.',
  'kLLssk......kLsssk',
  'kLsssk......ksssSk',
  'kSsSkkhhkkhhkksSSk',
  'kqqkhhhhhhhhhhkqqk',
  'kWwkhhhhhhhhhhkwqk',
  'kWwkhhhhhhhhhHkwqk',
  'kWwkhhhhhhhhhhkwck',
  'kWwkhhhhhhhhhhkwqk',
  'kWwkhhLLLLhhLLkwqk',
  'kWwkhLssssLssskwqk',
  'kWqkSkkkksskkkkqqk',
  'kWwkSkYckskYcckwqk',
  'kWwkSkkkksskkkkwqk',
  'kWwkSssssssssskwqk',
  'kWwkSsssssmmmskwqk',
  'kWwk.kSSsssmsskwqk',
  'kWwWkkkSSSSSkkwwqk',
  'kWwwwwwwwrrwwwwwqk',
  '.kWwwwwwwrRwwwwqk.',
  '..kWwwwwwrRwwwqk..',
  '..kWwwwwwrRwwwqk..',
  '..kqqqqqqqqqqqqk..',
  '.....kppppppppk...',
  '.....kppppPpppk...',
  '.....kpppkkPppk...',
  '.....kpppk.kPpk...',
  '.....kpPpk.kPpk...',
  '....kbBbbk.kbbBk..',
  '....kkkkkk.kkkkk..',
];

// ---------------------------------------------------------------------------
// Accountant — green eyeshade, bald dome, pencil behind the ear, vest, sleeve garters,
// clutches a ledger with a glowing adding-machine strip; attack = pencil jab.
const accLegend = {
  '.': '',
  k: 'ink0',
  s: 'skin2',
  S: 'skin1',
  L: 'skin3',
  c: 'cold5',
  Y: 'white',
  W: 'cream',
  w: 'paper',
  q: 'paper2',
  g: 'green2',
  G: 'green3',
  n: 'green4',
  N: 'green1',
  a: 'grey3',
  e: 'grey2',
  E: 'grey1',
  V: 'wood3',
  v: 'wood2',
  b: 'wood1',
  B: 'wood2',
  o: 'gold3',
  z: 'red5',
  r: 'red3',
  R: 'red1',
  m: 'red1',
};

const accIdle0 = [
  '..................',
  '.....kkkkkk.......',
  '...kkLWLLsskk.....',
  '..kLLLssssscsk....',
  '..kLssssssYcssk...',
  '.kaLsssssssccssk..',
  '.kagNNgggggGGGGkk.',
  'kkaeNgggGGGGGGGnnk',
  'kzokeNNNNNNNNNNNNk',
  'kkkeSSSSSSSSSSSk..',
  '..kSsYYksssYYksk..',
  '..kSsSSssssSSsssk.',
  '...kSsssssssssssk.',
  '...kSssssssmmsssk.',
  '....kSSsssssssk...',
  '.....kkSSSSSkk....',
  '....kWVWrRrWvvk...',
  '...kWVVvWwWvvbqk..',
  '..krkVVkkkkkkbkrk.',
  '..kWkVkWWWWWqkkqk.',
  '..kWkVkNnnnNgkkqk.',
  '..kLLLkNggggNLLLk.',
  '..kkkkkNNNNNNkkkk.',
  '.....keeeeeeeek...',
  '.....keeeeEeeek...',
  '.....keeekkEeek...',
  '.....keeek.kEek...',
  '.....keEek.kEek...',
  '....kbBbbk.kbbBk..',
  '....kkkkkk.kkkkk..',
];

const accAttack = [
  '..................',
  '......kkkkkk......',
  '....kkLWLLsskk....',
  '...kLLLssssscsk...',
  '...kLssssssYcssk..',
  '..kaLsssssssccssk.',
  '..kagNNgggggGGGGkk',
  '..kaeNgggGGGGGGGnk',
  '..kaeeNNNNNNNNNNNk',
  '..kaeSSSSSSSSSSSk.',
  '...kSsYYksssYYksk.',
  '...kSsSSssssSSsssk',
  '....kSsssssssssssk',
  '....kSsssssmWWmssk',
  '.....kSSsssssssk..',
  '......kkSSSSSkk...',
  '.....kWVWrRrWvkkk.',
  '....kWVVvWwWvLLoWa',
  '...krkkkkkkvvSSkkk',
  '...kWkWWWWWkvbkk..',
  '...kWkNnnnNkvbk...',
  '...kLLggggNkbbk...',
  '...kkkNNNNNkbbk...',
  '....kkeeeeeeeek...',
  '.....keeeeEeeek...',
  '....keeekkEeeek...',
  '...keeek..kEeek...',
  '..keEek....kEek...',
  '.kbBbbk....kbbBk..',
  '.kkkkkk....kkkkk..',
];

const accHurt = [
  '..................',
  '...............k..',
  '....kkkkkk....kck.',
  '..kkLWLLsskk...k..',
  '.kLLLssssscsk...k.',
  '.kLssssssYcssk.kck',
  'kaLsssssssccssk.k.',
  'kagNNgggggGGGGkk..',
  'kaeNgggGGGGGGGnnk.',
  'kaeeNNNNNNNNNNNNk.',
  'kaeSSSSSSSSSSSk...',
  'kSsSkkksssSkkksk..',
  'kSsSSssssSSsssk...',
  '.kSssssssssssk....',
  '.kSssssmmmmssk....',
  '..kSSsssssssk.....',
  '...kkSSSSSkk......',
  '..kWVWrRrWvvk.....',
  '.kWVVvWwWvvbqk....',
  'krkVVkkkkkkbkrk...',
  'kWkVkWWWWWqkkqk...',
  'kLLLkNnnnNgLLLk...',
  'kkkkkNNNNNNkkkk...',
  '...keeeeeeeek.....',
  '...keeeeEeeek.....',
  '...keeekkEeek.....',
  '...keeek.kEek.....',
  '...keEek.kEek.....',
  '..kbBbbk.kbbBk....',
  '..kkkkkk.kkkkk....',
];

const accHold = [
  '.kkkk........kkkk.',
  'kLLssk......kLsssk',
  'kLsssk......ksssSk',
  'kSsSkkkkkkk..ksSSk',
  'kqqkkLWLLsskk.kqqk',
  'kWwkLLssssscskkwqk',
  'kWwkssssssYcsskwqk',
  'kWwksssssssccskwqk',
  'kWwkNNgggggGGGkwqk',
  'kWwkNgggGGGGGGGnnk',
  'kzokeNNNNNNNNNNNNk',
  'kWwkSSSSSSSSSSkwqk',
  'kWwksYYkssYYkskwqk',
  'kWwksSSsssSSsskwqk',
  'krrkSssssssssskrrk',
  'kWwkSsssssmmmskwqk',
  'kWwk.kSSsssmsskwqk',
  'kWwWkkkSSSSSkkwwqk',
  'kWwwVVWrRrWvvbwwqk',
  '.kWVVvvvWvvvbbqk..',
  '..kVVvvvovvvbbk...',
  '..kVvvvvkvvvbbk...',
  '..kbbbbbbbbbbbk...',
  '.....keeeeeeeek...',
  '.....keeeeEeeek...',
  '.....keeekkEeek...',
  '.....keeek.kEek...',
  '.....keEek.kEek...',
  '....kbBbbk.kbbBk..',
  '....kkkkkk.kkkkk..',
];

// ---------------------------------------------------------------------------
// Janitor — red polka-dot headscarf, blue overalls, yellow rubber gloves, mop.
const janLegend = {
  '.': '',
  k: 'ink0',
  f: 'red3',
  F: 'red2',
  d: 'red4',
  W: 'cream',
  n: 'wood3',
  s: 'skin2',
  S: 'skin1',
  L: 'skin3',
  Y: 'white',
  x: 'red1',
  w: 'paper',
  q: 'paper2',
  o: 'cold3',
  O: 'cold2',
  i: 'cold4',
  I: 'cold1',
  y: 'grey4',
  g: 'gold3',
  G: 'gold4',
  j: 'gold2',
  u: 'wood3',
  U: 'wood4',
  a: 'grey3',
  e: 'grey2',
  h: 'ink2',
  P: 'ink3',
  c: 'cold5',
  t: 'teal4',
};

const janIdle0 = [
  '..................',
  '.....kkkkkkk......',
  '...kkddddffffk.kkk',
  '..kddWdfffffffkkUk',
  '.kkdffffffWffFkkUk',
  'kfFkdffffffffFFkuk',
  'kFfkfWffffffFFFkuk',
  '.kkFFFFFFFFFFFFkuk',
  '..kFnnLLLLnnLLnkuk',
  '..kSnkkksssskkskuk',
  '..kSssYkksskYkskuk',
  '..kSssssssssssckuk',
  '..kSsdssssssdsskuk',
  '..kSssssssxxxsskuk',
  '...kSSsssssssk.kuk',
  '....kkSSSSSkk..kuk',
  '...kWiwwwwiwqk.kuk',
  '..kWwiyoooyOqkkkuk',
  '..kwkiooooooOkGGgk',
  '..ksSkiooooOOkGgjk',
  '..kSskiooooOOkgjjk',
  '..kggkiooooOOkkjuk',
  '..kgjkIooooOOk.kuk',
  '...kkkioooooOk.kuk',
  '....kiooooOOOk.kuk',
  '....kiookkOOOkkyyk',
  '....kiook.kOOkaeak',
  '....kiOok.kOkaqaek',
  '...khPhhk.khkaeqak',
  '...kkkkkk.kkkkkkkk',
];

const janAttack = [
  '..................',
  '......kkkkkkk.....',
  '....kkddddffffk...',
  '...kddWdfffffffk..',
  '..kkdffffffWffFk..',
  '.kfFkdffffffffFFk.',
  '.kFfkfWffffffFFFk.',
  '..kkFFFFFFFFFFFFk.',
  '...kFnnLLLLnnLLnk.',
  '...kSnkkksssskksk.',
  '...kSssYkksskYksk.',
  '...kSssssssssssct.',
  '...kSsdssssssdsskt',
  '...kSsssssxxxxssk.',
  '....kSSsssxFFxkkyk',
  '.....kkSSSSSkkkyak',
  '....kWiwwwwiwqkaek',
  '...kSkkyokkyOkyaek',
  '..kkkGgkkGgkkkaeyk',
  '..kUugguugguuyyayk',
  '..kkkjjkkjjkkkaeyk',
  '...kkkkookkOOkyaek',
  '....kkiooooOOkkyak',
  '....kkiooooooOk...',
  '.....kiooooOOOk...',
  '....kiookkOOOOk...',
  '...kiook..kOOOk...',
  '..kiOok....kOOk...',
  '.khPhhk....khPhk..',
  '.kkkkkk....kkkkk..',
];

const janHurt = [
  '................c.',
  '...............c..',
  '....kkkkkkk...kkk.',
  '..kkddddffffkkkUk.',
  '.kddWdfffffffkkUk.',
  'kkdffffffWffFkkuk.',
  'kFkdffffffffFFkuk.',
  'kfkfWffffffFFFkuk.',
  'kkFFFFFFFFFFFFkuk.',
  '.kFnnLLLLnnLLnkuk.',
  '.kSnsskkskkssskuk.',
  '.kSsskkssskksskuk.',
  '.kSssssssssssckuk.',
  '.kSsdssssssdsskuk.',
  '.kSsssssxFFxsskuk.',
  '..kSSssssxxsk.kuk.',
  '...kkSSSSSkk..kuk.',
  '..kWiwwwwiwqkkkuk.',
  '.kWwiyoooyOqkGGgk.',
  '.kwkiooooooOkGgjk.',
  '.kSskiooooOOkgjjk.',
  '.kggkiooooOOkkjuk.',
  '.kgjkIooooOOk.kuk.',
  '..kkkioooooOk.kuk.',
  '...kiooooOOOk.kuk.',
  '...kiookkOOOkkyyk.',
  '...kiook.kOOkaeak.',
  '...kiOok.kOkaqaek.',
  '..khPhhk.khkaeqak.',
  '..kkkkkk.kkkkkkkk.',
];

const janHold = [
  '.kkkk........kkkk.',
  'kGGggk......kGgggk',
  'kGgggk......kgggjk',
  'kjgjjkkkkkkkkjjgjk',
  '.kjjkddddffffkjjk.',
  'kLskdWdfffffffksSk',
  'kLskffffffWffFksSk',
  'kLskdffffffffFksSk',
  'kLskfWffffffFFksSk',
  'kLskFFFFFFFFFFksSk',
  'kLsknnLLLLnnLLksSk',
  'kqqknssssssssskqqk',
  'kWwksskssskssskwqk',
  'kWwksksssksksskwqk',
  'kWwksdsssssdsskwqk',
  'kWwksssxWWWxsskwqk',
  'kWwkSSsssxxxsskwqk',
  'kWwWkkSSSSSkkwwwqk',
  'kWwwWiwwwwiwqwwwqk',
  '.kWwkiyoooyOkkwqk.',
  '..kkkiooooooOkkk..',
  '....kiooooOOOk....',
  '....kiooooOOOk....',
  '....kkioooooOk....',
  '....kiooooOOOk....',
  '....kiookkOOOk....',
  '....kiook.kOOk....',
  '....kiOok.kOOk....',
  '...khPhhk.khPhk...',
  '...kkkkkk.kkkkk...',
];

// ---------------------------------------------------------------------------
// Merchant «Савва» — night-shift vendor behind a counter, lit by a hurricane lantern.
// Frontal; idle1 = breathing + flame flicker, talk = open mouth, wink, raised finger.
const merchLegend = {
  '.': '',
  k: 'ink0',
  a: 'grey3',
  e: 'grey2',
  E: 'grey1',
  L: 'skin3',
  s: 'skin2',
  S: 'skin1',
  n: 'red4',
  B: 'wood1',
  b: 'wood2',
  Y: 'white',
  W: 'cream',
  o: 'gold3',
  O: 'gold4',
  j: 'gold2',
  t: 'teal3',
  T: 'teal2',
  d: 'teal1',
  D: 'teal0',
  r: 'red3',
  R: 'red2',
  x: 'red1',
  U: 'wood4',
  u: 'wood3',
  v: 'wood2',
  V: 'wood1',
  z: 'wood0',
  f: 'orange3',
  F: 'orange4',
  c: 'cold4',
  q: 'paper2',
  y: 'grey4',
  g: 'teal4',
};

const merchIdle0 = [
  '..........kkkkkkkkkk..........',
  '.......kkkaaaaaaeeeeekkk......',
  '......kaaaaeeeeeeeeeeeeEk.....',
  '.....kaaeeeeeeeeeeeeeeeEck....',
  '.....keeeeeeeeeeeeeeeeEEck....',
  '.....kEEEEEEEEEEEEEEEEEEEk....',
  '......kkaaaaaaaeeeeeeeeEkk....',
  '.......kkkkkkkkkkkkkkkkkk.....',
  '.......kSSSSSSSSSBBBBSk.......',
  '......kSsBBBBsssssssssSk......',
  '......kSsskYYsLsskYYssck......',
  '......kSssnssLssSssnsSSk......',
  '.......kssbBBBnnBBBbsSk.......',
  '.......kSkWWoWWWWWWkSSk.......',
  '........kSkkkkkkkkkSSk........',
  '.........kSSSSSSSSSSk.........',
  '.....ktTkrrrrrrRRRRRRkdDk.....',
  '...kttTkrrrRRRRRRRRxxkTddDk...',
  '.kkkktTxTkTkrRkDTTTTTkkkddgk..',
  '.kktktTrTqTkrRkDTTTTkOWokdgk..',
  'kyyyekTrToTkWWkDTTTTkoWjkdgk..',
  '.kWFktDDDDDkrRkDTTToDDDDDdgk..',
  'kWFfFkdddddkWWkDTojTddddddgk..',
  'kWffFkdddddkrxkDjTTTddddddgk..',
  '.kFFkkddddkkTkTDTTTTkdddddkk..',
  'kyyyekLLsSkTTTTDTTTTkLssSSkk..',
  'keeeEkLsSkkkkkkkkkkkksSSkkkkkk',
  'kkkkkkUUUUUuuuuuuuuuuuuuuuuuvk',
  'kuuuuuuuuuuuuuuuuuuuuuuuuuuvVk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kVVVVVVVVVVVVVVVVVVVVVVVVVVVVk',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kVVVVVVzVVVVVVVzVVVVVVVzVVVVVk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
];

const merchIdle1 = [
  '..............................',
  '..........kkkkkkkkkk..........',
  '.......kkkaaaaaaeeeeekkk......',
  '......kaaaaeeeeeeeeeeeeEk.....',
  '.....kaaeeeeeeeeeeeeeeeEck....',
  '.....keeeeeeeeeeeeeeeeEEck....',
  '.....kEEEEEEEEEEEEEEEEEEEk....',
  '......kkaaaaaaaeeeeeeeeEkk....',
  '.......kkkkkkkkkkkkkkkkkk.....',
  '.......kSSSSSSSSSBBBBSk.......',
  '......kSsBBBBsssssssssSk......',
  '......kSsskYYsLsskYYssck......',
  '......kSssnssLssSssnsSSk......',
  '.......kssbBBBnnBBBbsSk.......',
  '.......kSkWWoWWWWWWkSSk.......',
  '........kSkkkkkkkkkSSk........',
  '.........kSSSSSSSSSSk.........',
  '.....ktTkrrrrrrRRRRRRkdDk.....',
  '.kkkktTkrrrRRRRRRRRxxkTddDk...',
  '.kktktTxTkTkrRkDTTTTTkkkddgk..',
  'kyyyekTrTqTkrRkDTTTTkOWokdgk..',
  '.kWFktTrToTkWWkDTTTTkoWjkdgk..',
  'kWfFFkDDDDDkrRkDTTToDDDDDdgk..',
  'kWFfFkdddddkWWkDTojTddddddgk..',
  '.kFFktdddddkrxkDjTTTddddddgk..',
  'kyyyekddddkkTkTDTTTTkdddddkk..',
  'keeeEkLsSkkkkkkkkkkkksSSkkkkkk',
  'kkkkkkUUUUUuuuuuuuuuuuuuuuuuvk',
  'kuuuuuuuuuuuuuuuuuuuuuuuuuuvVk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kVVVVVVVVVVVVVVVVVVVVVVVVVVVVk',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kVVVVVVzVVVVVVVzVVVVVVVzVVVVVk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
];

const merchTalk = [
  '..........kkkkkkkkkk..........',
  '.......kkkaaaaaaeeeeekkk......',
  '......kaaaaeeeeeeeeeeeeEk.....',
  '.....kaaeeeeeeeeeeeeeeeEck....',
  '.....keeeeeeeeeeeeeeeeEEck....',
  '.....kEEEEEEEEEEEEEEEEEEEk....',
  '......kkaaaaaaaeeeeeeeeEkk....',
  '.......kkkkkkkkkkkkkkkkkk.....',
  '.......kSBBBBSSSSBBBBSk.......',
  '......kSssssssssssssssSk......',
  '......kSsskYYsLsskkkssck......',
  '......kSssnssLssSssnsSSk......',
  '.......kssbBBBnnBBBbsSk.......',
  '.......kSkWWoWWWWWWkSSk.......',
  '........kSxrrrxxxxxSSk........',
  '.........kSSSSSSSSSSk...k.....',
  '.....ktTkrrrrrrRRRRRRkdkLk....',
  '...kttTkrrrRRRRRRRRxxkkkskk...',
  '.kkkktTxTkTkrRkDTTTTTkLssSkk..',
  '.kktktTrTqTkrRkDTTTTkksssSkk..',
  'kyyyekTrToTkWWkDTTTTkkSSSSkk..',
  '.kWFktDDDDDkrRkDTTToDkddddkk..',
  'kWFfFkdddddkWWkDTojTdkddddkk..',
  'kWffFkdddddkrxkDjTTTddddddkk..',
  '.kFFkkddddkkTkTDTTTTTdddddgk..',
  'kyyyekLLsSkTTTTDTTTTTdddddgk..',
  'keeeEkLsSkkkkkkkkkkkkkkkkkkkkk',
  'kkkkkkUUUUUuuuuuuuuuuuuuuuuuvk',
  'kuuuuuuuuuuuuuuuuuuuuuuuuuuvVk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kVVVVVVVVVVVVVVVVVVVVVVVVVVVVk',
  'kvvvvvvVvvvvvvvVvvvvvvvVvvvvck',
  'kVVVVVVzVVVVVVVzVVVVVVVzVVVVVk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
];

// ---------------------------------------------------------------------------
// Props.
const stoneLegend = {
  '.': '',
  k: 'ink0',
  W: 'paper',
  a: 'grey4',
  b: 'grey3',
  c: 'grey2',
  d: 'grey1',
  e: 'cold1',
  f: 'cold4',
};

const pedestal = [
  '..kkkkkkkkkkkkkk..',
  '.kWWaaaaaaaaaaaak.',
  'kWaaaaaaaaaaaaaaak',
  'kbbbbbbbbbbbbbbbfk',
  'kccccccccccccccdek',
  '.kkkkkkkkkkkkkkkk.',
  '...kWbbbcbbbbcfk..',
  '...kWbbbcbbbbcfk..',
  '...kccccccccccek..',
  '...kWbcbbbbcbdfk..',
  '.kkkkkkkkkkkkkkkk.',
  'kWaaaaaaaaaaaaaaak',
  'kbbbbbbbbbbbbbbdek',
  'kkkkkkkkkkkkkkkkkk',
];

const dealLegend = {
  '.': '',
  k: 'ink0',
  W: 'grey1',
  b: 'ink3',
  c: 'ink2',
  d: 'ink1',
  e: 'vio0',
  f: 'cold2',
  q: 'red3',
  r: 'red2',
  R: 'red1',
  x: 'red0',
  S: 'red4',
  L: 'red5',
  X: 'red2',
  o: 'gold2',
  O: 'gold3',
};

const pedestalDeal = [
  '..kkkkkkkkkkkkkk..',
  '.kqqrrrrrrrrrrrrk.',
  'kqrrrrrrrrrrrrrrRk',
  'kRrrrrrrrrrrrrrRRk',
  'kxRRRRRRRRRRRRRRxk',
  '.kkkkkRRRRRRRkkkk.',
  '...kWbkRRRRRkcfk..',
  '...kWbkSLSSSkcfk..',
  '...kWkSSXXXSSkfk..',
  '...kWbkXSSXXkdfk..',
  '.kkkkkkkkkkkkkkkk.',
  'kOoooooooooooooook',
  'kbccccccccccccccek',
  'kkkkkkkkkkkkkkkkkk',
];

const trapLegend = {
  '.': '',
  k: 'ink0',
  W: 'paper',
  a: 'grey3',
  b: 'grey2',
  f: 'cold4',
  U: 'wood4',
  u: 'wood3',
  v: 'wood2',
  V: 'wood1',
  P: 'ink3',
  y: 'grey4',
  h: 'ink1',
  g: 'ink2',
  e: 'cold1',
};

const trapClosed = [
  '................................',
  '....kkkkkkkkkkkkkkkkkkkkkkkk....',
  '...kWaaaaaaaaaaaaaaaaaaaaaabk...',
  '..kakkkkkkkkkkkkkkkkkkkkkkkkbk..',
  '..kakUuuuVuuuVuuuuVuuuVuuuvkbk..',
  '..kakyPPPPPPPPPPPPPPPPPPPPykbk..',
  '.kaakuuuuVuuuVuuuuVuuuVuuuvkbfk.',
  '.kaakuuuuVuuuVuyyuVuuuVuuuvkbfk.',
  '.kaakyPPPPPPPPykkyPPPPPPPPykbfk.',
  'kaaakkkkkkkkkkkkkkkkkkkkkkkkbbbk',
  'kWaaaaaaaaaaaaaaaaaaaaaaaaaabbbk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
];

const trapOpen = [
  '............k......k............',
  '....kkkkkkkkUkkkkkkUkkkkkkkk....',
  '...kWaaaaaakUkaaaakUkaaaaaabk...',
  '..kakkkkkkkkukkkkkkukkkkkkkkbk..',
  '..kakeeeeeeeuUUUUUUueeeeeeekbk..',
  '..kakgggggggvggggggvgggggggkbk..',
  '.kaakhhhhhhhvuuuuuuvhhhhhhhkbfk.',
  '.kaakhhhhhhhVhhhhhhVhhhhhhhkbfk.',
  '.kaakkkhhhhhVVVVVVVVhhhhhkkkbfk.',
  'kaaakkkkkkkkkkkkkkkkkkkkkkkkbbbk',
  'kWaaaaaaaaaaaaaaaaaaaaaaaaaabbbk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
];

const chestLegend = {
  '.': '',
  k: 'ink0',
  U: 'wood4',
  u: 'wood3',
  v: 'wood2',
  V: 'wood1',
  i: 'grey4',
  I: 'grey3',
  J: 'grey2',
  o: 'gold3',
  O: 'gold4',
  j: 'gold2',
  e: 'cold1',
  f: 'cold4',
  h: 'ink1',
  W: 'cream',
};

const chestClosed = [
  '..kkkkkkkkkkkk..',
  '.kUUuiuuuuiuuvk.',
  'kUuuuiuuuuiuuvfk',
  'kuvvvIvvvvIvvVVk',
  'kkkkkkkoOkkkkkkk',
  'kUuuuiuojuiuuvfk',
  'kuuuuiukkuiuuvfk',
  'kuvvvIvvvvIvvvVk',
  'kVVVVIVVVVIVVVVk',
  'kuvvvIvvvvIvvvfk',
  'kuvvvIvvvvIvvvVk',
  'kVVVVJVVVVJVVVek',
  'kkkkkkkkkkkkkkkk',
];

const chestOpen = [
  '.kkkkkkkkkkkkkk.',
  '.kvVVVVVVVVVVVk.',
  '.kvVVVVVVVVVVVk.',
  'kkkkkkkkkkkkkkkk',
  'kUhhhhhhhhhhhhfk',
  'kuhhhWOhhhhhhhVk',
  'kkkkkkkkkkkkkkkk',
  'kuvvvIvvvvIvvvfk',
  'kVVVVIVVVVIVVVVk',
  'kuvvvIvvvvIvvvfk',
  'kuvvvIvvvvIvvvVk',
  'kVVVVJVVVVJVVVek',
  'kkkkkkkkkkkkkkkk',
];

const goldLegend = {
  '.': '',
  k: 'ink0',
  W: 'cream',
  G: 'gold4',
  g: 'gold3',
  j: 'gold2',
  J: 'gold1',
  y: 'grey4',
  a: 'grey3',
  e: 'grey2',
  h: 'ink1',
  f: 'cold4',
};

const goldClosed = [
  '..kkkkkkkkkkkk..',
  '.kWWgjggggjggjk.',
  'kWggggggggggggfk',
  'kgjjjJjjjjJjjJJk',
  'kkkkkkkyykkkkkkk',
  'kWgggjgyygjgggfk',
  'kgggjjkaakjjggJk',
  'kgjjjJkekkJjjjJk',
  'kJJJJJkkkkJJJJJk',
  'kgjjjJjjjjJjjjfk',
  'kgjjjJjjjjJjjjJk',
  'kJJJJJJJJJJJJJJk',
  'kkkkkkkkkkkkkkkk',
];

const goldOpen = [
  '.kkkkkkkkkkkkkk.',
  '.kjJJJJJJJJJJjk.',
  '.kjJJJJJJJJJJjk.',
  'kkkkkkkkkkkkkkkk',
  'kWhhhhhhhhhhhhfk',
  'kghhhWGhhhhhhhJk',
  'kkkkkkkkkkkkkkkk',
  'kgjjjJjjjjJjjjfk',
  'kJJJJJJJJJJJJJJk',
  'kgjjjJjjjjJjjjfk',
  'kgjjjJjjjjJjjjJk',
  'kJJJJJJJJJJJJJJk',
  'kkkkkkkkkkkkkkkk',
];

const arrowLegend = {
  '.': '',
  k: 'ink0',
  W: 'cream',
  w: 'paper',
  q: 'paper2',
};

const arrowRight = [
  '.....k.....',
  '.....kk....',
  '.....kWk...',
  'kkkkkkWWk..',
  'kWWWWWWWwk.',
  'kWwwwwwwwqk',
  'kqqqqqwwqk.',
  'kkkkkkwqk..',
  '.....kqk...',
  '.....kk....',
  '.....k.....',
];

const arrowUp = [
  '.....k.....',
  '....kWk....',
  '...kWwqk...',
  '..kWWwwqk..',
  '.kWWwwwwqk.',
  'kkkkWwqkkkk',
  '...kWwqk...',
  '...kWwqk...',
  '...kWwqk...',
  '...kWqqk...',
  '...kkkkk...',
];

const signLegend = {
  '.': '',
  k: 'ink0',
  U: 'wood4',
  u: 'wood3',
  v: 'wood2',
  V: 'wood1',
  y: 'grey4',
  q: 'paper2',
  f: 'cold4',
};

const sign = [
  '.....kqk........................kqk.....',
  '.....kUk........................kUk.....',
  '.....kqk........................kqk.....',
  '.....kUk........................kUk.....',
  '..kkkkykkkkkkkkkkkkkkkkkkkkkkkkkkykkkk..',
  '.kUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUuk.',
  'kUukkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkuVk',
  'kUukVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVkuVk',
  'kUukvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkuVk',
  'kUukvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkuVk',
  'kUukvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkuVk',
  'kUukvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkuVk',
  'kUukvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkuVk',
  'kUukvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkuVk',
  'kUukkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkuVk',
  'kuVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVfk',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
];

export const CAST: Record<string, SpriteDef> = {
  hero_intern_hold: { w: 18, h: 30, legend: internLegend, frames: { idle0: internHold }, ox: 9, oy: 29 },
  hero_accountant: {
    w: 18,
    h: 30,
    legend: accLegend,
    frames: { idle0: accIdle0, idle1: shiftDown(accIdle0, 22), attack: accAttack, hurt: accHurt, hold: accHold },
    ox: 9,
    oy: 29,
  },
  hero_janitor: {
    w: 18,
    h: 30,
    legend: janLegend,
    frames: { idle0: janIdle0, idle1: shiftDown(janIdle0, 22), attack: janAttack, hurt: janHurt, hold: janHold },
    ox: 9,
    oy: 29,
  },
  merchant: { w: 30, h: 36, legend: merchLegend, frames: { idle0: merchIdle0, idle1: merchIdle1, talk: merchTalk }, ox: 15, oy: 35 },
  pedestal: { w: 18, h: 14, legend: stoneLegend, frames: { idle0: pedestal }, ox: 9, oy: 13 },
  pedestal_deal: { w: 18, h: 14, legend: dealLegend, frames: { idle0: pedestalDeal }, ox: 9, oy: 13 },
  trapdoor: { w: 32, h: 12, legend: trapLegend, frames: { closed: trapClosed, open: trapOpen }, ox: 16, oy: 11 },
  chest: { w: 16, h: 13, legend: chestLegend, frames: { closed: chestClosed, open: chestOpen }, ox: 8, oy: 12 },
  chest_locked: { w: 16, h: 13, legend: goldLegend, frames: { closed: goldClosed, open: goldOpen }, ox: 8, oy: 12 },
  door_arrow: { w: 11, h: 11, legend: arrowLegend, frames: { idle0: arrowRight }, ox: 5, oy: 5 },
  door_arrow_up: { w: 11, h: 11, legend: arrowLegend, frames: { idle0: arrowUp }, ox: 5, oy: 5 },
  shopkeeper_sign: { w: 40, h: 17, legend: signLegend, frames: { idle0: sign }, ox: 20, oy: 16 },
};
