import type { SpriteDef } from '../sprite.ts';

/**
 * Floor 2 «Затопленный архив»: flooded archive, rain through a broken skylight, teal water,
 * mist, warm lanterns. Local colours at medium value; the lighting pass darkens them and adds
 * glow to emissive pixels (lantern flame and glass). Skylight glass is left transparent.
 * Anchors: tiles 0,0; ceiling pieces top-centre (lantern at its hook); floor props
 * bottom-centre; the crate at its waterline.
 */
const L = {
  '.': '',
  k: 'ink0',
  n: 'ink2',
  N: 'ink3',
  '1': 'cold1',
  '2': 'cold2',
  '4': 'cold4',
  '5': 'cold5',
  q: 'teal0',
  Q: 'teal1',
  t: 'teal2',
  T: 'teal3',
  u: 'teal4',
  U: 'teal5',
  '7': 'vio0',
  v: 'vio1',
  V: 'vio2',
  f: 'red0',
  x: 'red1',
  X: 'red2',
  o: 'orange1',
  O: 'orange2',
  p: 'orange3',
  j: 'gold1',
  J: 'gold2',
  y: 'gold3',
  Y: 'gold4',
  c: 'cream',
  b: 'wood1',
  B: 'wood2',
  d: 'wood3',
  D: 'wood4',
  a: 'green0',
  e: 'green1',
  E: 'green2',
  g: 'grey1',
  G: 'grey2',
  m: 'grey3',
  M: 'grey4',
  w: 'paper',
  W: 'paper2',
  i: 'white',
};

export const ENV_ARCHIVE: Record<string, SpriteDef> = {
  // Damp concrete block wall, tiles both ways.
  ar_wall: {
    w: 32,
    h: 32,
    legend: L,
    frames: {
      idle0: [
        'GGGGGGGGGGGGGGGQmmmmmmmmGtgGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGtGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGtGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGgGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGQGGGGGGGGGGGGGGGG',
        'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
        'mmmmmgtgGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGgtgGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGgtgGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGgtGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGgtGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGtGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGtGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGtGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGtGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGgGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGQ',
        'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
      ],
    },
    ox: 0,
    oy: 0,
  },
  // Wet floor tiles, tiles both ways.
  ar_floor: {
    w: 32,
    h: 16,
    legend: L,
    frames: {
      idle0: [
        'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN',
        'NgggggggggggggggNggggggggggggggg',
        'NggttTttttggggggNggttttggggggggg',
        'NgggggggggggggggNggggggggggggggg',
        'NgggggggggggggggNggggggggggggggg',
        'NgggggggggggggggNggggggggggggggg',
        'NgggggggggggggggNggggggggggggggg',
        'NgggggggggggggggNggggggggggggggg',
        'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN',
        'NgggggggggggggggNggggggggggggggg',
        'NgggggggggggggggNggggggggttTtttg',
        'NgggggggggttttggNggggggggggggggg',
        'NgggggggggggggggNQQttttttQQQQQQg',
        'NgggggggggggggggNQQQQQQQQQQQQQQg',
        'NgggggggggggggggNQQQQQQQQQQQQQQg',
        'NgggggggggggggggNggggggggggggggg',
      ],
    },
    ox: 0,
    oy: 0,
  },
  // Water surface edge, tiles horizontally; idle0..3 loop the swell.
  ar_waterline: {
    w: 32,
    h: 6,
    legend: L,
    frames: {
      idle0: [
        '.UUUUUUU........................',
        'uTTTTTTTuuu.....uuuuuuuuuu...uuu',
        'TtttttttTTTuuuuuTTTTTTTTTTuuuTTT',
        't.......tttTTTTTttttttttttTTTttt',
        '...TTT.....ttttt..........ttt...',
        '............TT.....TTT..........',
      ],
      idle1: [
        '.........UUUUUUU................',
        'uu...uuuuTTTTTTTuuu.....uuuuuuuu',
        'TTuuuTTTTtttttttTTTuuuuuTTTTTTTT',
        'ttTTTtttt.......tttTTTTTtttttttt',
        '..ttt......TTT.....ttttt........',
        '....................TT.....TTT..',
      ],
      idle2: [
        '.................UUUUUUU........',
        'uuuuuuuuuu...uuuuTTTTTTTuuu.....',
        'TTTTTTTTTTuuuTTTTtttttttTTTuuuuu',
        'ttttttttttTTTtttt.......tttTTTTT',
        '..........ttt......TTT.....ttttt',
        '...TTT......................TT..',
      ],
      idle3: [
        '.........................UUUUUUU',
        'uuu.....uuuuuuuuuu...uuuuTTTTTTT',
        'TTTuuuuuTTTTTTTTTTuuuTTTTttttttt',
        'tttTTTTTttttttttttTTTtttt.......',
        '...ttttt..........ttt......TTT..',
        '....TT.....TTT..................',
      ],
    },
    ox: 0,
    oy: 0,
  },
  // Horizontal pipe, tiles horizontally.
  ar_pipe_h: {
    w: 32,
    h: 8,
    legend: L,
    frames: {
      idle0: [
        '..............kkkk..............',
        'kkkkkkkkkkkkkkkMmkkkkkkkkkkkkkkk',
        'mmmmmmmmmmmmmmkmGkmmmmmmmmmmmmmm',
        'GGGGGGGGGGGGGGkmGkGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGkmGkGGGGGGGGGGGGGG',
        '11111111111111kGgk11111111111111',
        'kkkkkkkkkkkkkkkg1kkkkkkkkkkkkkkk',
        '..............kkkk..............',
      ],
    },
    ox: 0,
    oy: 0,
  },
  // Vertical pipe, tiles vertically.
  ar_pipe_v: {
    w: 8,
    h: 32,
    legend: L,
    frames: {
      idle0: [
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        'kkkkkkkk',
        'kMmmmGgk',
        'kmGGGgTk',
        'kkkkkkkk',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
        '.kmGgTk.',
      ],
    },
    ox: 0,
    oy: 0,
  },
  // Broken skylight; glass is transparent, shards cling to the frame.
  ar_skylight: {
    w: 100,
    h: 26,
    legend: L,
    frames: {
      idle0: [
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk',
        'kGmgggggggggggggggggggggggmgggggggggggggggggggggggmgggggggggggggggggggggggmggggggggggggggggggggggmgk',
        'kGggkkkkkkkkkkkkkkkkkkkk1gggkkkkkkkkkkkkkkkkkkkk1gggkkkkkkkkkkkkkkkkkkkk1gggkkkkkkkkkkkkkkkkkkkk1ggk',
        'kGgk....................1ggkUuuuuUUuuU..UuuuuU..1ggkUuuuUUuU............1ggk....................1ggk',
        'kGgk....................1ggkUuuuuU.UuU...UuuuUUU1ggkUuuuU.U.............1ggk....55............551ggk',
        'kGgk....................1ggk.UuuU..UU....UuuUUuu1ggkUuuuU.U.............1ggk......555.......55..1ggk',
        'kGgk....................1ggk.UuuU...U.....UuUUUu1ggk.UuU................1ggk.........55...55....1ggk',
        'kGgk....................1ggk.UuU..........UU...U1ggk.UuU................1ggk...........5i5......1ggk',
        'kGgk....................1ggk.UuU...........U....1ggk.UuU................1ggk...........555......1ggk',
        'kGgk........5..4........1ggk..U................U1ggk.UuU................1ggk.........555..5.....1ggk',
        'kGgk.......5..4.........1ggk..U...............UU1ggk..U.................1ggk........5..5...55...1ggk',
        'kGgk......5..4..........1ggkU..........U......UU1ggk..U...............U.1ggk.......5...5.....5..1ggk',
        'kGgk.....5..4...........1ggkuU........UU.....UuU1ggk..U..............UU.1ggk......5....5......5.1ggk',
        'kGgk....5..4............1ggkuuUU......UuU...UuuU1ggk.................UU.1ggk....55....5........51ggk',
        'kGgk......4.............1ggkuuUUU....UuuU...UuuU1ggk................UuuU1ggk...5......5.........1ggk',
        'kGgk....................1ggkUU......UuuuuU.UuuuU1ggk...............UuuuU1ggk..5.......5.........1ggk',
        'kGgGGGGGGGGGGGGGGGGGGGGG1ggGGGGGGGGGGGGGGGGGGGGG1ggGGGGGGGGGGGGGGGGGGGGG1ggGGGGGGGGGGGGGGGGGGGGG1ggk',
        'kGmgggggggggggggggggggggggmgggggggggggggggggggggggmgggggggggggggggggggggggmggggggggggggggggggggggmgk',
        'kggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kGGGGGGGGGGGttGGGGGGGGGGGGGGGGGGGGGGGtGGGGGGGGGGGGGGGGGGGGGGGttGGGGGGGGGGGGGGGGGGGGGGGGGtGGGGGGGGGGk',
        'kGGGGGGGGGGGttGGGGGGGGGGGGGGGGGGGGGGGtGGGGGGGGGGGGGGGGGGGGGGGttGGGGGGGGGGGGGGGGGGGGGGGGGtGGGGGGGGGGk',
        'kgggggggggggtggggggggggggggggggggggggtgggggggggggggggggggggggtggggggggggggggggggggggggggtggggggggggk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
      ],
    },
    ox: 50,
    oy: 0,
  },
  // Hanging lantern, anchored at the hook; flame and glass are emissive.
  ar_lantern: {
    w: 10,
    h: 18,
    legend: L,
    frames: {
      idle0: [
        '....kk....',
        '....kk....',
        '...k..k...',
        '....kk....',
        '...kJJk...',
        '..kJJJjk..',
        '.kkkkkkkk.',
        '.kpyyyypk.',
        '.kyYccYyk.',
        '.kyYccYyk.',
        '.kyYcYYyk.',
        '.kpyYYypk.',
        '.kpyOOypk.',
        '.kkkkkkkk.',
        '..kJJJjk..',
        '..kjjjjk..',
        '...kkkk...',
        '..........',
      ],
      idle1: [
        '....kk....',
        '....kk....',
        '...k..k...',
        '....kk....',
        '...kJJk...',
        '..kJJJjk..',
        '.kkkkkkkk.',
        '.kpyyYypk.',
        '.kyYYcYyk.',
        '.kyYccYyk.',
        '.kyYccYyk.',
        '.kpyYYypk.',
        '.kpyOOypk.',
        '.kkkkkkkk.',
        '..kJJJjk..',
        '..kjjjjk..',
        '...kkkk...',
        '..........',
      ],
    },
    ox: 5,
    oy: 0,
  },
  ar_shelf: {
    w: 44,
    h: 70,
    legend: L,
    frames: {
      idle0: [
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmGGkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkGGuk',
        'kmnGnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnGnuk',
        'kmGGnnnnnnnnnnnnnkkkkkkkkkkkkknnnnnnnnnnGGuk',
        'kmGGnkkkkkkkkkkkkkDDDDDDDDDDDknnnnnnnnnnGGuk',
        'kmnGnkDDDDDDDDDDkkddddddddddBknnnnnnnnnnGnuk',
        'kmGGnkdddddddddBkkbbbbbbbbbbBknnnnnnnnnnGGuk',
        'kmGGnkbbbbbbbbbBkkDdddddddddBknnnnnnnnnnGGuk',
        'kmnGnkDddddddddBkkDddwwwkkkdBknkkkkkkkknGnuk',
        'kmGGnkDdkkkwWddBkkDddwmmWdddBknkkkkkkwknGGuk',
        'kmGGnkDddwmmWddBkkDddwwwWdddBknkwwwwwwknGGuk',
        'kmnGnkDddwwwWddBkkDdddddddddBknkWWWWWWknGnuk',
        'kmGGnkDddddddddBkkDdddddddddBknkwwwwwwknGGuk',
        'kmGGnkkkkkkkkkkkkkkkkkkkkkkkkknkkkkkkkknGGuk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmGGnkkkkkkkkkkkkkkkkkkkkkkkkkkkknnnnnnnGGuk',
        'kmGGnk211kkXxxkkdBkkEeekk211kkVvknnnkkkkkGuk',
        'kmnGnkWWWkkWWWkkWWkkWWWkkWWWkkWWknnnkwWWknuk',
        'kmGGnkwwwkkwwwkkwwkkwwwkkwwwkkwwknnkwWWkGGuk',
        'kmGGnkWWWkkWWWkkWWkkWWWkkWWWkkWWknnkXxxkGGuk',
        'kmnGnk21NkkXxfkkdbkkEeakk21NkkV7knnkXxxkGnuk',
        'kmGGnk21NkkXxfkkdbkkEeakk21NkkV7knkXxxknGGuk',
        'kmGGnk21NkkXxfkkdbkkEeakk21NkkV7knkXxxknGGuk',
        'kmnGnk2kNkkXkfkkdkkkEkakk2kNkkVkknkXxxknGnuk',
        'kmGGnk21NkkXxfkkdbkkEeakk21NkkV7kkXxxknnGGuk',
        'kmGGnk21NkkXxfkkdbkkEeakk21NkkV7kkXxxknnGGuk',
        'kmnGnkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkknnGngk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmGGnkkk11j1111j11kknnnnnnnnnnnnnnnnnnnnGGgk',
        'kmnGnkEkkkkkkkkkkkkknnnkkkkkkkkkkkkkkkknGngk',
        'kmGGnkeejeeeeeeejeeknnnkDDDDDDDDDDDDDDknGGgk',
        'kmGGnkkkkkkkkkkkkkkknnnkdddddddddddddBknGGgk',
        'kmnGnnkddJddddddJddknnnkbbbbbbbbbbbbbBknGngk',
        'kmGGnnkBBjBBBBBBjBBknnnkDddddddddddddBknGGgk',
        'kmGGnkkkkkkkkkkkkkkkknnkDdkkkwwwWddddBknGGgk',
        'kmnGnkXXJXXXXXXXXJXXknnkDdddwmmmWddddBknGngk',
        'kmGGnkxxjxxxxxxxxjxxknnkDdddwwwwWddddBknGGgk',
        'kmGGnkkkkkkkkkkkkkkkknnkDddddddddddddBknGGgk',
        'kmnGnnnnnnnnnnnnnnnnnnnkDddddddddddddBknGngk',
        'kmGGnnnnnnnnnnnnnnnnnnnkkkkkkkkkkkkkkkknGGgk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmnGnnnnnnnnnnnnnnnnnnnnnnnnnnnnkkkkknnnGngk',
        'kmGGnnnnnnnnnnnnnnnnnnnnnnnnnnnnktQQknnnGGgk',
        'kmGGnkkkkkkkkkkkkkknnnnnnnnnnnnnkWWWknnnGGgk',
        'kmnGnkDDDDDDDDDDDDknnnnnnnnnnnnnkwwwknnnGngk',
        'kmGGnkdddddddddddBk..kkkkkkkkkknkWWWknnnGGgk',
        'kmGGnkbbbbbbbbbbbBk.kDDDDDDDDDknktQqknnnGGgk',
        'kmnGnkDddddddddddBkkdddddddddBknktQqknnnGngk',
        'kmGGnkDdddwwwkkkdBkkbbbbbbbbbBknktQqknnnGGgk',
        'kmGGnkBBBBBBBBBBBBkkBBBBBBBBBBknktkqknnnGGgk',
        'kmnGnkbbbbbbbbbbbbkkbbbbbbbbbbknkqqqknnnGngk',
        'kmGGnkbbbbbbbbbbbbkkbbbbbbbbbbknkqqqknnnGGgk',
        'kmGGnkkkkkkkkkkkkkkkkkkkkkkkkkknkkkkknnnGGgk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kkkk....................................kkkk',
        'kkkk....................................kkkk',
      ],
    },
    ox: 22,
    oy: 69,
  },
  ar_boxes: {
    w: 34,
    h: 22,
    legend: L,
    frames: {
      idle0: [
        '.....kkkkkkkkkkkkkkkkkk...........',
        '.....kDDDDDDDDDDDDDDDDDkk.........',
        '......kDDDDDDDDDDDDDDDDDk.........',
        '......kddddddddddddddddBk.........',
        '......kbbbbbbbbbbbbbbbbBk.........',
        '......kDdddddddddddddddBk.........',
        '......kDddddwwwwwWdkkkdBk.........',
        '......kDddddwmmmmWdddddBk.........',
        '......kDddddwwwwwWdddddBk.........',
        '......kDdddddddddddddddBk.........',
        '......kDdddddddddddddddBk.........',
        'kkkkkkkkkkkkkkkkkkkkkkkkk.........',
        'kDDDDDDDDDDDDDDDkkkkkkkkkkkkkkkkkk',
        'kddddddddddddddBkDDDDDDDDDDDDDDDDk',
        'kbbbbbbbbbbbbbbBkdddddddddddddddBk',
        'kDdddddddddddddBkbbbbbbbbbbbbbbbBk',
        'kDdkkkwwwwWddddBkDddddddddddddddBk',
        'kDddddwmmmWddddBkDddddwwwwwWkkkdBk',
        'kDddddwwwwWddddBkDddddwmmmmWddddBk',
        'kBBBBBBBBBBBBBBBkBBBBBBBBBBBBBBBBk',
        'kbbbbbbbbbbbbbbbkbbbbbbbbbbbbbbbbk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
      ],
    },
    ox: 17,
    oy: 21,
  },
  ar_ladder: {
    w: 14,
    h: 60,
    legend: L,
    frames: {
      idle0: [
        '.kk........kk.',
        'kJjk......kJjk',
        'kJ.k......kJ.k',
        'kkkkkkkkkkkkkk',
        'kDDDDDDDDDDDdk',
        'kdddddddddddBk',
        'kkkkkkkkkkkkkk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDddkkkkkkddBk',
        'kDddDDDDDDddBk',
        'kDddBBBBBBdduk',
        'kDddkkkkkkdduk',
        'kDdk......kduk',
        'kDdk......kduk',
        'kDdk......kduk',
        'kDddkkkkkkdduk',
        'kDddDDDDDDdduk',
        'kDddBBBBBBdduk',
        'kDddkkkkkkdduk',
        'kDdk......kduk',
        'kDdk......kduk',
        'kDdk......kduk',
        'kDddkkkkkkdduk',
        'kDddDDDDDDdduk',
        'kDddBBBBBBdduk',
        'kDddkkkkkkdduk',
        'kDdk......kduk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDddkkkkkkddBk',
        'kDddDDDDDDddBk',
        'kDddBBBBBBddBk',
        'kDddkkkkkkddBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDddkkkkkkddBk',
        'kDddDDDDDDddBk',
        'kDddBBBBBBddBk',
        'kDddkkkkkkddBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDddkkkkkkddBk',
        'kDddDDDDDDddBk',
        'kDddBBBBBBddBk',
        'kDddkkkkkkddBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kDdk......kdBk',
        'kggk......kggk',
        'kmgk......kmgk',
        'kkkk......kkkk',
      ],
    },
    ox: 7,
    oy: 59,
  },
  // Floating crate; anchor sits on the waterline, the soaked bottom rows hang below it.
  ar_crate: {
    w: 20,
    h: 18,
    legend: L,
    frames: {
      idle0: [
        'kkkkkkkkkkkkkkkkkkkk',
        'kDDDDDDDDDDDDDDDDDDk',
        'kDmddddddddddddddmdk',
        'kkkkkkkkkkkkkkkkkkkk',
        'kDdkdddddddddddDdkuk',
        'kDdkBBBBBBBBBBDdkduk',
        'kDdkBBBBBBBBDdkBkduk',
        'kDdkBBBBBBBDdkBBkduk',
        'kDdkbbbbbbDdkbbbkduk',
        'kDdkdddddDdkddddkduk',
        'kDdkBBBBDdkBBBBBkddk',
        'kDdkBBDdkBBBBBBBkddk',
        'kDdkBDdkBBBBBBBBkddk',
        'kDdkDdkBBBBBBBBBkddk',
        'kkkkkkkkkkkkkkkkkkkk',
        'kBGBBBBBBBBBBBBBBGBk',
        'kbbbbbbbbbbbbbbbbbbk',
        'kkkkkkkkkkkkkkkkkkkk',
      ],
    },
    ox: 10,
    oy: 14,
  },
  ar_door: {
    w: 30,
    h: 54,
    legend: L,
    frames: {
      idle0: [
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        'kGGGGGGGGGGGGGGGGGGGGGGGGGGGGk',
        'kGggggggggggggggggggggggggggNk',
        'kGgkkkkkkkkkkkkkkkkkkkkkkkkgNk',
        'kGgkmmmmmmmmmmmmmmmmmmmmmmkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGugkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGugkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGugkgNk',
        'kGgkkkkkkkkkkkkkkkkkkkkkkkkgNk',
        'kGgkmmMmmmMmmmMmmmMmmmMmmmkgNk',
        'kGgkGGGGGGGGGGGGGGGGGGGGGGkgNk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkgNk',
        'kkmmmkGGGGGGGGGGGGGGGGGGugkgNk',
        'kkkkkkGGGGkkkkkkkkkkGGGGugkgNk',
        'kGgkmGGGGGkWWWWWWWWkGGGGugkgNk',
        'kGgkmGGGGGkWmmmmmmWkGGGGugkgNk',
        'kGgkmGGGGGkWWWWWWWWkGGGGugkgNk',
        'kGgkmGGGGGkkkkkkkkkkGGGGugkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGugkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGugkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGugkgNk',
        'kGgkmGGGGGGGGkkkkkGGGGGGugkgNk',
        'kGgkmGGGGGGkkMMMMMkkGGGGugkgNk',
        'kGgkmGGGGGkkMkGmGkMkkGGGugkgNk',
        'kGgkmGGGGGkMGGGmGGGmkGGGugkgNk',
        'kGgkmGGGGkMkGGGmGGGkmkGGugkgNk',
        'kGgkmGGGGkMGGGkkkGGGmkGGugkgNk',
        'kGgkmGGGGkMmmmkJkmmmmkGGugkgNk',
        'kGgkmGGGGkMGGGkkkGGGmkGGugkgNk',
        'kGgkmGGGGkMkGGGmGGGkmkGGGgkgNk',
        'kGgkmGGGGGkMGGGmGGGmkGGGGgkgNk',
        'kGgkmGGGGGkkmkGmGkmkkGGGGgkgNk',
        'kGgkmGGGGGGkkmmmmmkkGGGGGgkgNk',
        'kGgkmGGGGGGGGkkkkkGGGGGGGgkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGGgkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGGgkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGGgkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGGgkgNk',
        'kGgkmGGGGGGGGGGGGGGGGGGGGgkgNk',
        'kkkkkkGGGGGGGGGGGGGGGGGGGgkgNk',
        'kkmmmkGGGGGGGGGGGGGGGGGGGgkgNk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkgNk',
        'kGgkmmMmmmMmmmMmmmMmmmMmmmkgNk',
        'kGgkGGGGGGGGGGGGGGGGGGGGGGkgNk',
        'kGgkkkkkBkkkkkkkkkkkkkkkkkkgNk',
        'kGgkmGGGoGGGGGGGGGBGGGoGGgkgNk',
        'kGgkmGGGoGGGGGGGGGBGGGoGGgkgNk',
        'kGgkmGGGoGGGGGGGGGBGGGoGGgkgNk',
        'kGgkmGGGoGGGGGGGGGGGGGoGGgkgNk',
        'kGgkmGGGoGGGGGGGGGGGGGoGGgkgNk',
        'kGgkmQQQQQQQQQQQQQQQQQQQGgkgNk',
        'kGgkmtttttttttttttttttttGgkgNk',
        'kGgkmtttttttttttttttttttGgkgNk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
      ],
    },
    ox: 15,
    oy: 53,
  },
};
