import type { SpriteDef } from '../sprite.ts';

/**
 * Floor 4 «Дирекция»: executive floor at night in a thunderstorm.
 * Warm wood and brass against cold storm light. Local colours at medium value; the lighting pass darkens them.
 * Emissive: lamp bulb, chandelier candle bulbs, lit city windows.
 * Anchors: tileables at (0,0); floor and wall props at bottom centre; di_chandelier at top centre (hangs from y=0).
 */
const legend = {
  '.': '',
  k: 'ink0',
  K: 'ink1',
  n: 'ink2',
  N: 'ink3',
  c: 'cold1',
  C: 'cold2',
  v: 'cold3',
  i: 'cold5',
  '5': 'teal0',
  t: 'teal1',
  T: 'teal2',
  u: 'teal3',
  '6': 'vio0',
  q: 'vio1',
  Q: 'vio2',
  m: 'red0',
  r: 'red1',
  R: 'red2',
  x: 'red3',
  y: 'gold1',
  Y: 'gold2',
  g: 'gold3',
  G: 'gold4',
  w: 'cream',
  a: 'wood0',
  b: 'wood1',
  B: 'wood2',
  d: 'wood3',
  D: 'wood4',
  e: 'green0',
  f: 'green1',
  F: 'green2',
  s: 'green3',
  S: 'green4',
  '0': 'grey0',
  '1': 'grey1',
  '2': 'grey2',
  z: 'paper',
  Z: 'paper2',
  W: 'white',
  h: 'skin0',
  H: 'skin1',
  l: 'skin2',
};

// di_wall 32x32: tileable dark wood paneling
const di_wall_idle0 = [
  'ddbddddddddddddddddddddddddddddd',
  'BBbBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'Bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  'BBbddddddddddddddddddddddddddddd',
  'BBbdBBBBBBBBBBBBBBBBBBBBBBBBBBBb',
  'BBbdBBBBBBBBBBBBBBBBBBBBBBBBBBBb',
  'BBbdBBbbbbbbbbbbbbbbbbbbbbbbbBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbBBBBBBBBBBBBBBBBBBBBBdBBb',
  'BBbdBBbddddddddddddddddddddddBBb',
  'BBbdBBBBBBBBBBBBBBBBBBBBBBBBBBBb',
  'BBbdBBBBBBBBBBBBBBBBBBBBBBBBBBBb',
  'BBbdbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
];

// di_floor 32x16: tileable polished marble
const di_floor_idle0 = [
  'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN',
  'N2222222222222222222222222222222',
  'N2111111111111111111111111111111',
  'N2111111111111111111111111111111',
  'N2111111111111111111111111111111',
  'N2111111111111111111111111111111',
  'N2111111111111111111111111211111',
  'N2111111111111111111111122111111',
  'N2111111111111111111112211111111',
  'N2111111111111111122221111111111',
  'N2111111111111112211111111111111',
  'N2111111111111221111111111111111',
  'N2111111222222111111111111111111',
  'N2111122111111211111111111111111',
  'N2111211111111121111111111111111',
  'N2111111111111111111111111111111',
];

// di_window 120x92: glass is transparent (x8..111, y6..83): paint the storm sky and di_city behind it
const di_window_idle0 = [
  '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
  '.kDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDk.',
  '.kddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddk.',
  '.kBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBk.',
  '.kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbk.',
  '.kddBbCKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKCdBbbk.',
  '.kddBbCKCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCK........................KC.........................KC.........................KC........................KCdBbbk.',
  '.kddBbCKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKCdBbbk.',
  'kDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDk',
  'kdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddvk',
  'kBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCk',
  'kBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbk',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
];

// di_desk 84x30: items stand with their bottom row on desk row 6 (anchor.y - 23); free top x2..50, e.g. di_lamp at anchor + (-30, -23)
const di_desk_idle0 = [
  '.....................................................kk.............................',
  '....................................................kDdk............................',
  '....................................................kddk......kkkkkkkkkkkk..........',
  '....................................................kddk.....kwwwwwwwwwwwwk.........',
  '...................................................kxxRRk....kzzzzzzzzzzzZk.........',
  '...................................................kRRRRk....kZZZZZZZZZZZZk.........',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkrrrrkkkkkkzZZZZZZZZZZZkkkkkkkkk.',
  'kdddddddddddddddddddddddffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddk',
  'kdddddddddddddddddddddddfFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFdddddddddddddddddddddddk',
  'kDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDvk',
  'kdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddCk',
  'kBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBk',
  '.kkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkk.',
  '..kBdddddddddddddddddddddddBaaaaaaaaaaaaaaaaaaaaaaaaaaaaBdddddddddddddddddddddddCk..',
  '..kBdBBBBBBBBBBBBBBBBBBBBBbBbbbbbbbbbbbbbbbbbbbbbbbbbbbbBdBBBBBBBBBBBBBBBBBBBBBbCk..',
  '..kBdBBBBBBBBBgYyBBBBBBBBBbBbbbddddddddddddddddddddddbbbBdBBBBBBBBBgYyBBBBBBBBBbCk..',
  '..kBdbbbbbbbbbbbbbbbbbbbbbbBbbbdBBBBBBBBBBBBBBBBBBBBbbbbBdbbbbbbbbbbbbbbbbbbbbbbCk..',
  '..kBdddddddddddddddddddddddBbbbdBBBBBBBBBBBBBBBBBBBBbbbbBdddddddddddddddddddddddCk..',
  '..kBdBBBBBBBBBBBBBBBBBBBBBbBbbbdBBBBBBBBBBBBBBBBBBBBbbbbBdBBBBBBBBBBBBBBBBBBBBBbCk..',
  '..kBdBBBBBBBBBgYyBBBBBBBBBbBbbbdBBBBBBBBBBBBBBBBBBBBbbbbBdBBBBBBBBBgYyBBBBBBBBBbCk..',
  '..kBdbbbbbbbbbbbbbbbbbbbbbbBbbbdBBBBBBBBBBBBBBBBBBBBbbbbBdbbbbbbbbbbbbbbbbbbbbbbCk..',
  '..kBdddddddddddddddddddddddBbbbdBBBBBBBBBBBBBBBBBBBBbbbbBdddddddddddddddddddddddCk..',
  '..kBdBBBBBBBBBBBBBBBBBBBBBbBbbbdBBBBBBBBBBBBBBBBBBBBbbbbBdBBBBBBBBBBBBBBBBBBBBBbCk..',
  '..kBdBBBBBBBBBgYyBBBBBBBBBbBbbbdbbbbbbbbbbbbbbbbbbbbbbbbBdBBBBBBBBBgYyBBBBBBBBBbCk..',
  '..kBdBBBBBBBBBBBBBBBBBBBBBbBbbbbbbbbbbbbbbbbbbbbbbbbbbbbBdBBBBBBBBBBBBBBBBBBBBBbCk..',
  '..kBdbbbbbbbbbbbbbbbbbbbbbbBbbbbbbbbbbbbbbbbbbbbbbbbbbbbBdbbbbbbbbbbbbbbbbbbbbbbCk..',
  '..kBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBk..',
  '..kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbk..',
  '..kbbbkkkkkkkkkkkkkkkkkkbbbkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkbbbkkkkkkkkkkkkkkkkkkbbbk..',
  '...kkk..................kkk..............................kkk..................kkk...',
];

// di_lamp 14x16: bulb row 7 (cream/gold4) is emissive
const di_lamp_idle0 = [
  '..............',
  '..kkkkkkkkkk..',
  '.kSSssssssFFk.',
  'kSsssssssssFfk',
  'kssssssssssFfk',
  'kFFFFFFFFFFffk',
  'kYggggggggggYk',
  '.kGwwwwwwwwGk.',
  '..kkkkYgkkkk..',
  '.....kYgk.....',
  '.....kYgk.....',
  '.....kYgk.....',
  '.kkkkkYgkkkkk.',
  '.kgggggggggyk.',
  '.kYYYYYYYYYyk.',
  '.kkkkkkkkkkkk.',
];

// di_bookcase 42x66: four shelves over a closed cabinet
const di_bookcase_idle0 = [
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'dddddddddddddddddddddddddddddddddddddddddd',
  'BbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBB',
  'BbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbB',
  'kdBbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadBCk',
  'kdBbaaaaaaaaaaaaaaaaaaRrrmaaaaaaaaaaaadBCk',
  'kdBbaaRrmaaaaaaaaaaaaayyymdBbRrrmaaaaadBCk',
  'kdBbdbyymDBdBbaaaaaaaaRrrmyybyyymDdBaadBCk',
  'kdBbdbRrmyBdBbddddzaaaRrrmdBbRrrmyyBaadBCk',
  'kdBbdbRrmDBdZbBBBBZaaaRrrmdBbRrrmDdBaadBCk',
  'kdBbdbRrmDBdZbRRRRRzaaRrrmdBbRrrmDdBaadBCk',
  'kdBbdbRrmDBdBbrrrrrZaaRrrmdBbRrrmDdBaadBCk',
  'kdBbdbyymyBdBbRRRRRRzayyymyybyyymyyBaadBCk',
  'kdBbdbRrmDBdBbrrrrrrZaRrrmdBbRrrmDdBaadBCk',
  'kdBbdddddddddddddddddddddddddddddddddddBCk',
  'kdBbBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBdBCk',
  'kdBbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdBCk',
  'kdBbaaaaaaaaaaaaaaaaaaaaaa210aaa210aaadBCk',
  'kdBbaa210aaaaaCcNaaCNaaaaayy0CcNyy0aaadBCk',
  'kdBb20yy0CcN20yyNaaCNaaCcN210yyN210210dBCk',
  'kdBby0210yyNy0CcNaaCNaayyN210CcN210210dBCk',
  'kdBb20210CcN20CcNaaCNaaCcN210CcN210210dBCk',
  'kdBb20210CcN20CcNaaCNaaCcN210CcN210210dBCk',
  'kdBb20210CcN20CcNaaCNaaCcN210CcN210210dBCk',
  'kdBby0yy0yyNy0yyNaaCNaayyNyy0yyNyy0210dBCk',
  'kdBb20210CcN20CcNaaCNaaCcN210CcN210210dBCk',
  'kdBbdddddddddddddddddddddddddddddddddddBCk',
  'kdBbBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBdBCk',
  'kdBbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdBCk',
  'kdBbdbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadBCk',
  'kdBbybaaaadbaaaaFfedbaaaaaaaadBbaadbRmdBCk',
  'kdBbdbFffedbFffeyyeybaaaaaaaadBbFeybymdBCk',
  'kdBbdbFffedbFffeFfedbFFFFzaaadZbFedbRmdBCk',
  'kdBbdbFZfedbFZfeFfedbffffZaaadZbFedbRmdBCk',
  'kdBbdbFZfedbFZfeFfedbRRRRRzaadBbFedbRmdBCk',
  'kdBbdbFffedbFffeFfedbrrrrrZaadBbFedbRmdBCk',
  'kdBbybFffedbFffeyyeybddddddzadBbFeybymdBCk',
  'kdBbdbFffedbFffeFfedbBBBBBBZadBbFedbRmdBCk',
  'kdBbdddddddddddddddddddddddddddddddddddBCk',
  'kdBbBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBdBCk',
  'kdBbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdBCk',
  'kdBbaadBbQ6aaaaaaaRmaaaaaaaaaaadBbaaaadBCk',
  'kdBbQ6yybQ6dBbQqq6RmaaaaRrmRmCNdBbaaaadBCk',
  'kdBbQ6dBbQ6yybyyy6RmdbaayymymyNdBbQq6adBCk',
  'kdBbQ6dBbQ6dBbQqq6RmybaaRrmRmCNdBbyy6adBCk',
  'kdBbQ6dBbQ6dBbQqq6RmdbaaRrmRmCNdBbQq6adBCk',
  'kdBbQ6dBbQ6dBbQqq6RmdbaaRrmRmCNdBbQq6adBCk',
  'kdBbQ6dBbQ6dBbQqq6RmdbaaRrmRmCNdBbQq6adBCk',
  'kdBbQ6yybQ6yybyyy6RmybaayymymyNdBbyy6adBCk',
  'kdBbQ6dBbQ6dBbQqq6RmdbaaRrmRmCNdBbQq6adBCk',
  'kdBbdddddddddddddddddddddddddddddddddddBCk',
  'kdBbBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBdBCk',
  'kdBBBBBBBBBBBBBBBBBBbdBBBBBBBBBBBBBBBBBBCk',
  'kdBBBddddddddddddddBbdBddddddddddddddBBBCk',
  'kdBBBdBBBBBBBBBBBBbBbdBdBBBBBBBBBBBBbBBBCk',
  'kdBBBdBBBBBBBBBBBBbBbdBdBBBBBBBBBBBBbBBBCk',
  'kdBBBdBBBBBBBBBBBBgBbdBgBBBBBBBBBBBBbBBBCk',
  'kdBBBdBBBBBBBBBBBBbBbdBdBBBBBBBBBBBBbBBBCk',
  'kdBBBdbbbbbbbbbbbbbBbdBdbbbbbbbbbbbbbBBBCk',
  'kdBBBBBBBBBBBBBBBBBBbdBBBBBBBBBBBBBBBBBBCk',
  'dddddddddddddddddddddddddddddddddddddddddd',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
];

// di_portrait 30x36: censored boss
const di_portrait_idle0 = [
  '.kkkkkkkkkkkkkYYkkkkkkkkkkkkk.',
  'kYYYYYYYYYYYYggggYYYYYYYYYYYYk',
  'kYGYYYYYYYYYYYYYYYYYYYYYYYYgBk',
  'kYYbbbbbbbbbbbbbbbbbbbbbbbYyBk',
  'kYYbbbbbbbbbbBBBBbbbbbbbbbYyBk',
  'kYYbbbbbbbbBBBBBBBBbbbbbbbYyBk',
  'kYYbbbbbbbBBnnnnnnBBbbbbbbYyBk',
  'kYYbbbbbbBnn112211nnBbbbbbYyBk',
  'kYYbbbbbbn1122222111nbbbbbYyBk',
  'kYYbbbbbBn1HllllllH1nBbbbbYyBk',
  'kYYbbbbbn1HllllllllH1nbbbbYyBk',
  'kYYbbbbkkkkkkkkkkkkkkkkbbbYyBk',
  'kYYbbbbkkkkkkkkkkkkkkkkbbbYyBk',
  'kYYbbbbkkkkkkkkkkkkkkkkbbbYyBk',
  'kYYbbbbbhHllllllllllHhbbbbYyBk',
  'kYYbbbbbhHllllhhllllHhbbbbYyBk',
  'kYYbbbbbhHHllllllllHHhbbbbYyBk',
  'kYYbbbbbbhHlhhhhhhlHhbbbbbYyBk',
  'kYYbbbbbbhHhllllllhHhbbbbbYyBk',
  'kYYbbbbbbbhHHHHHHHHhbbbbbbYyBk',
  'kYYbbbbbbbbhhhhhhhhbbbbbbbYyBk',
  'kYYbbbbbbNcNNzZZzNNcNbbbbbYyBk',
  'kYYbbbbNccCNzzRRzzNCccNbbbYyBk',
  'kYYbbbNccCCNzzRxzzNCCccNbbYyBk',
  'kYYbbNcccCCCNzRxzNCCCcccNbYyBk',
  'kYYbbNcccCCCNzRxzNCCCcccNbYyBk',
  'kYYbbNcccCCCCNRxNCCCCcccNbYyBk',
  'kYYbbNccccCCCNRrNCCCccccNbYyBk',
  'kYYbbNccccCCCCNNCCCCccccNbYyBk',
  'kYYbbNccccCCCCCCCCCCccccNbYyBk',
  'kYYbbNccccCCCCCCCCCCccccNbYyBk',
  'kYYbbbbbbbbbbbbbbbbbbbbbbbYyBk',
  'kYYYYYYYYYYYYYYYYYYYYYYYYYYyBk',
  'kYgyyyyyyyyyyyyyyyyyyyyyyyygBk',
  'kYBBBBBBBBBBBBBBBBBBBBBBBBBBBk',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
];

// di_plant 24x42: potted palm
const di_plant_idle0 = [
  '...........k............',
  '..........kFk...........',
  '..........kFk...........',
  '.........kFFk..k........',
  '.......k.kFFk.kSk.......',
  '......kSkkFFkkSFFk......',
  '.....kFsSkFskkssFFk.....',
  '....kFFsskFskSsFfFFk....',
  '...kFFFFsSFsksFfffk.....',
  '...kFFffFsFsksffkkkkk...',
  '...kSfSffsFsksfkFFFFFk..',
  '..ksssssffsskskFkfffFfk.',
  '.kFFFFFFsFFssFFffffffFk.',
  '.kFFFFFkfsFssFffkfffffFk',
  '.kFFfffkkfkskkfkkkkkffFk',
  'kFFfkkFFFFFkkFFFFFFkkfFf',
  'FFFkFFfffkkkkkkffffFkkFk',
  'kffFFfkffkkdBkkfkfffFkfF',
  'kFfFffkkkkBBbk.k.kffFFfF',
  'FFFfffk...kdBk....kffFfk',
  'FfFfkk....kdBk.....kfFfk',
  'kfFfk....kBBbk......kfFk',
  '.kFk......kdBk......kfFf',
  'kfFk......kdBk.......kFk',
  'kffk.....kBBbk.......kFf',
  '.kFk......kdBk......kFfk',
  '.kFk......kdBk......kFfk',
  'kfFk.....kBBbk......kFk.',
  '.kFk......kdBk.......k..',
  '..k..kkkkkkdBkkkkkk.....',
  '....kuuuuuuuuuuuuuuk....',
  '....kTttttttttttttTk....',
  '.....ktTutttttttt5k.....',
  '.....ktTutttttttt5k.....',
  '.....ktTutttttttt5k.....',
  '......ktyYYyyyyy5k......',
  '......ktTutttttt5k......',
  '......ktTutttttt5k......',
  '.......ktTutttt5k.......',
  '.......ktTutttt5k.......',
  '.......ktTutttt5k.......',
  '........kkkkkkkk........',
];

// di_chandelier 44x24: hangs from its top row; candle flames emissive
const di_chandelier_idle0 = [
  '...................YYYYYY...................',
  '...................kyyyyk...................',
  '....................kgYk....................',
  '...........k........kyyk........k...........',
  '..........kGk.......kgYk.......kGk..........',
  '....k.....kwGk......kyyk......kGwk.....k....',
  '...kGk....kwwk......kgYk......kwwk....kGk...',
  '...kwGk...kzZk.....kYgYYk.....kZzk...kgwk...',
  '...kwwk...kzZk....kYggYYYk....kZzk...kwwk...',
  '...kzZk...kzZk...kYggGgYYYk...kZzk...kZzk...',
  '...kzZk..kgggYk..kYgggYYYYk..kYYYYk..kZzk...',
  '...kzZk...kyyk..kYkYggYYYkYk..kyyk...kZzk...',
  '..kgggYk...kYkkkYYkkYYYYkkYYkkkYk...kYYYYk..',
  '...kyyk....kyYYYYyk.kYYk.kyYYYYyk....kyyk...',
  '....kyYkk...kyyyYk..kYyk..kYyyyk...kkYyk....',
  '.....kyYYkkkkkiYyk..kgYk..kyYikkkkkYYyk.....',
  '......kyyYYYYYvyk...kYyk...kyvYYYYYyyk......',
  '......kikyyyyyyk....kWik....kyyyyyykik......',
  '......kvkkikkkk.....kivk.....kkkkikkvk......',
  '.......k.kvk........kvvk........kvk.k.......',
  '..........k.........kvk..........k..........',
  '.....................k......................',
  '............................................',
  '............................................',
];

// di_city 160x64: tileable along x; transparent above the roofs, opaque rain haze in the bottom rows
const di_city_idle0 = [
  '................................................................................................................................................................',
  '................................................................................................................................................................',
  '................................................................................................................................................................',
  '................................................................................................................................................................',
  '................................................................................................................................................................',
  '................................................................................................................................................................',
  '......................................................................................................................x.........................................',
  '......................................................................................................................c.........................................',
  '......................................................................................................................c.........................................',
  '......................................................................................................................c.........................................',
  '..................................................................................................................c...c.........................................',
  '..................................................................................................................c...c.........................................',
  '..............................................................................................................ccccccccc.........................................',
  '..............................................................................................................ccccccccc.........................................',
  '..............................................................................................................ccccccccc.........................................',
  '..............................................................................................................ccccccccc.........................................',
  '............................................................c...............................................cccccccccccc........................................',
  'cccccccc....................................................c..........c..............................c.....cccccccccccc........................................',
  'cccccccc................................................ccccccccc......c..............................c.....cccccccccccc................c.......................',
  'cccccccc................................................ccccccccc....ccccc........................cccccccc..cccccccccccc................c.......................',
  'cccccccc.........................ccccccc................ccccccccc....ccccc........................cccccccc..cccccccccccc............cccccccc....................',
  'cccccccc.........................ccccccc................ccccccccc....ccccc................cccccc..cccccccc..cccccccccccc............cccccccc....................',
  'cccccccc.........................ccccccc..............ccccccccccccc..ccccc................cccccc..cccccccc..cccccccccccc............cccccccc....................',
  'cccccccc.........................ccvcccc..............cccccccccccccccccccccc..............ccccccccccccccccccccccccccvccc............cccccccc....................',
  'cccccvcc.........................ccccccc..............cccccccccccccccccccccc..............cccccccccccccccccccccccccccccc..........cccccccccccc..................',
  'cccccccc.........................ccccccc..............cccccccccccccccccccccc..............cccccccccccccccccccccccccccccc..........cccccccccccc..................',
  'cccccccc.........................ccccccc..............cccccccccccccccccccccc..............cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc....',
  'cccccccc..............cccccccccccccccccc..............cccccccccccccccccccccc..............cccccccccccccccccccccccvcccccccccccccccccccccccccccccccccccccccccc....',
  'cccccccc..............ccccccccccNccccccccccccccccccccccccccccccccccccccccccc..............cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc....',
  'ccccccNc..............cccccccccNNNcccccccccccccccccccccccccccccccccccccccccc..............cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc....',
  'cccccNNNcccccccccccccccccccccccNNNcccccccNNNNNNncccccccccccccccccccccccccccc..............ccccccccYccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccccNNNcccccccccccccccccccccccNNNccccccNNNNNNNnccccccccccccccccccccccccccccccccccccccccccccccccccNccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccccNNNccccccccccccccNNNNNNNNNNNNNNNnccNNNNNNNnccccccccccccccccccccccccccccccccccccccccccccccccccNccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'ccccNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnccccccccvcccccccccccccccccccccccccccccccccccccccccNccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnccccccccccccccccccccccccccccccccccccvcccccccccccccNccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnccccccccccccccccccccccccccccccccccccccccccccccccccNccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnccccccccccccccccccccccccccccccccccccccccccccvccccNNNNNNNnccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnccccccccccccccccccccccccccccccccNNNNNNNNNNNNNNNnNNNNNNNNnccccNcccccccccccccccccccccccccccNNNNNNNNNNncccccccccccc',
  'cccNNNNNNNNNNNNNNNnccNNNNgNgNNNNNNNNNnccNNNNNNNncccccccccccccccccccccccccccccccNNNNNNNNNNNNNNNNnNNNNNNNNnccccNcccccccccccccccccNccccccccNNNNNNNNNNNncccccccccccc',
  'cccNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNncccccccccccccccccccccccccccccccNNNNNNNNNNNNNNNNnNNNNNNNNnccccNccccccccccccccccNNNcccccccNNNNNNNNNNNncccccccccccc',
  'cccNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNncccccccccccccccccccccccccccccccNNNNgNgNNNNNNNNNnNNNNNNNNnccccNccccccccccccccccNNNcccccccNNNNNNNNNNNncccNNNNNNNNn',
  'cccNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnccccccccccccccccccccccNccccccccNNNNNNNNNNNNNNNNnNNNNNNNNnccccNccccccccccccccccNNNcccccccNNNNNNNNNNNnccNNNNNNNNNn',
  'cccNNNNNNNNNNgNgNNnccNNNNNNNNNNNNNNNNnccNNNNNNNncNNNNNNNNNNncccccccccNNNcccccccNNNNNNNNNNNNNNNNnNNNNNNNNncccNNNNNNNNNncNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'cccNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNncccccccccNNNcccccccNNNNNNNNNNNNNNNNnNNNNNNNNnccNNNNNNNNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'cccNNNNNNNNNNNNnNNnccNNNNNNNNNNNNNNvNnccNNNNNNNnNNNNNNNNNNNncccccccccNNNcccccccNNNNNNNNNNNNNNNNnNNNNNNNNnccNNNNNNNNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'ccNNNNNNNNNNNNNnNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNncNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnNNgNgNgNnccNNgNgNNNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'ccNNNNNNNNNNNNNnNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNnNNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnNNNNNNNNnccNNNNNNNNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'ccNNNNNNNNNNNNNnNNnccNNgNgNgNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNnNNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnNNNNNNNNnccNNNNNNNNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'ccNNNNNNNNNNNNNngNnccNNNNNNNNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNnNNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnNNNNNNNNnccNNNNgNgNgNnNNNNNNNNNNvNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'ccNNNNNNNNNNNNNnNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNnNNNNNNNNNNNNNNNNnccNNgNNNNNNNNNNNNNnNNNNNNNNnccNNNNNNNNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'ccNNNNNNNNNNNNNnNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNnNNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnNNNNNNNNnccNNNNNNNNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'ccNNNNNNNNNNNNNnNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNnNNNNNNNNNNgNgNgNnccNNNNNNNNNNNNNNNNnNNNNNNNNnccNNgNgNgNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'ccNNNNNNNNNNNNNnNNnccNNNNNNNNNNNNNNNNnccNNNNNNNnNNNNNNNNNNNnNNNNNNNNNNNNNNNNnccNNNNNNNNNNNNNNNNnNNNNNNNNnccNNNNNNNNNNnNNNNNNNNNNNNNNNNNnNNNNNNNNNNNnccNNNNNNNNNn',
  'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
];

// di_door 32x56: double door
const di_door_idle0 = [
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
  'kdDDDDDDDDDDDDDDDDDDDDDDDDDDDDDk',
  'kdddddddddddddddddddddddddddddCk',
  'kdBBBBBBBBBBBBBBBBBBBBBBBBBBBBCk',
  'kdbbbbbbbbbbbbbbbbbbbbbbbbbbbbCk',
  'kdBbdBBBBBBBBBBaBBBBBBBBBBBbdBCk',
  'kdBbdBBBBBBBBBBaBBBBBBBBBBBbdBCk',
  'kdBbdBBBBBBBBBBaBBBBBBBBBBBbdBCk',
  'kdBbdBddddddddBaBBddddddddBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBddddBbBaBBdBddddBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBbbbbBbBaBBdBbbbbBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdbbbbbbbBaBBdbbbbbbbBbdBCk',
  'kdBbdBBBBBBBBBBaBBBBBBBBBBBbdBCk',
  'kdBbdBBBBBBBBGgaBggBBBBBBBBbdBCk',
  'kdBbdBBBBBBBBgyaBgyBBBBBBBBbdBCk',
  'kdBbdBBBBBBBBBBaBBBBBBBBBBBbdBCk',
  'kdBbdBBBBBBBBBBaBBBBBBBBBBBbdBCk',
  'kdBbdBddddddddBaBBddddddddBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBddddBbBaBBdBddddBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdBbbbbBbBaBBdBbbbbBbBbdBCk',
  'kdBbdBdBBBBBBbBaBBdBBBBBBbBbdBCk',
  'kdBbdBdbbbbbbbBaBBdbbbbbbbBbdBCk',
  'kdBbdBBBBBBBBBBaBBBBBBBBBBBbdBCk',
  'kdBbdBBBBBBBBBBaBBBBBBBBBBBbdBCk',
  'kdBbbbbbbbbbbbbbbbbbbbbbbbbbdBCk',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
];

export const ENV_DIRECTORATE: Record<string, SpriteDef> = {
  di_wall: {
    w: 32,
    h: 32,
    legend,
    frames: { idle0: di_wall_idle0 },
    ox: 0,
    oy: 0,
  },
  di_floor: {
    w: 32,
    h: 16,
    legend,
    frames: { idle0: di_floor_idle0 },
    ox: 0,
    oy: 0,
  },
  di_window: {
    w: 120,
    h: 92,
    legend,
    frames: { idle0: di_window_idle0 },
    ox: 60,
    oy: 91,
  },
  di_desk: {
    w: 84,
    h: 30,
    legend,
    frames: { idle0: di_desk_idle0 },
    ox: 42,
    oy: 29,
  },
  di_lamp: {
    w: 14,
    h: 16,
    legend,
    frames: { idle0: di_lamp_idle0 },
    ox: 7,
    oy: 15,
  },
  di_bookcase: {
    w: 42,
    h: 66,
    legend,
    frames: { idle0: di_bookcase_idle0 },
    ox: 21,
    oy: 65,
  },
  di_portrait: {
    w: 30,
    h: 36,
    legend,
    frames: { idle0: di_portrait_idle0 },
    ox: 15,
    oy: 35,
  },
  di_plant: {
    w: 24,
    h: 42,
    legend,
    frames: { idle0: di_plant_idle0 },
    ox: 12,
    oy: 41,
  },
  di_chandelier: {
    w: 44,
    h: 24,
    legend,
    frames: { idle0: di_chandelier_idle0 },
    ox: 22,
    oy: 0,
  },
  di_city: {
    w: 160,
    h: 64,
    legend,
    frames: { idle0: di_city_idle0 },
    ox: 0,
    oy: 0,
  },
  di_door: {
    w: 32,
    h: 56,
    legend,
    frames: { idle0: di_door_idle0 },
    ox: 16,
    oy: 55,
  },
};
