import type { SpriteDef } from '../sprite.ts';

/**
 * Style anchor. Warm key light from the upper left (desk lamps), cold rim light from the
 * right (rainy windows). Near-black outline, 2–3 tones per material, chunky readable shapes.
 */
const legend = {
  '.': '',
  k: 'ink0',
  h: 'ink2',
  H: 'cold2',
  s: 'skin2',
  S: 'skin1',
  L: 'skin3',
  c: 'cold5',
  w: 'paper',
  W: 'cream',
  q: 'paper2',
  r: 'red3',
  R: 'red1',
  p: 'cold1',
  P: 'ink3',
  b: 'wood1',
  B: 'wood2',
  m: 'red1',
  x: 'red2',
  y: 'grey4',
  Y: 'white',
  t: 'teal4',
};

const idle0 = [
  '......kk..kk......',
  '.....khhkkhhk.kk..',
  '....khhhhhhhhkhhk.',
  '...khhhhhhhhhhhhk.',
  '...khhhhhhhhhhHhk.',
  '..khhhhhhhhhhhhHhk',
  '..khhhhhhhhhhhhhhk',
  '..khhhLLLLhhLLLhhk',
  '..khhLssssLssssshk',
  '..khkkkkssskkkkssk',
  '..kSkcckkskcckkssk',
  '..kSkkkkssskkkksck',
  '...kSsssssssssssk.',
  '...kSssssssmmsssk.',
  '....kSSsssssssk...',
  '.....kkSSSSSkk....',
  '....kWwwwrrwwwk...',
  '...kWWwwwrrwwwqk..',
  '..kWWwwwwrRwwwqqk.',
  '..kWkwwwwrRwwwkqk.',
  '..kWkwwwwrRwwwkqkx',
  '..kLkwwwwwRwwwkLyk',
  '..kLkqqqqqqqqqkkY.',
  '...k.kppppppppk.k.',
  '.....kppppPpppk...',
  '.....kpppkkPppk...',
  '.....kpppk.kPpk...',
  '.....kpPpk.kPpk...',
  '....kbBbbk.kbbBk..',
  '....kkkkkk.kkkkk..',
];

function shiftDown(rows: string[], from: number): string[] {
  // Breathing: everything above `from` moves down 1px, legs stay planted.
  const out = rows.slice();
  const w = rows[0].length;
  for (let y = from; y > 0; y--) out[y] = rows[y - 1];
  out[0] = '.'.repeat(w);
  return out;
}

const idle1 = shiftDown(idle0, 22);

const attack = [
  '.......kk..kk.....',
  '......khhkkhhk.kk.',
  '.....khhhhhhhhkhhk',
  '....khhhhhhhhhhhhk',
  '....khhhhhhhhhhHhk',
  '...khhhhhhhhhhhhHk',
  '...khhhhhhhhhhhhhk',
  '...khhhLLLLhhLLLhk',
  '...khhLssssLssssshk'.slice(0, 18),
  '...khkkkkssskkkksk',
  '...kSkcckkskcckksk',
  '...kSkkkkssskkkksk',
  '....kSssssssssssk.',
  '....kSsssssmmmssk.',
  '.....kSSsssssssk..',
  '......kkSSSSSkk...',
  '.....kWwwwrrwwkkkk',
  '....kWWwwwrrwwwxxY',
  '...kWWwwwwrRwwwkyY',
  '...kWkwwwwrRwwwkk.',
  '...kWkwwwwrRwwwk..',
  '...kLkwwwwwRwwwk..',
  '...kLkqqqqqqqqqk..',
  '....kkppppppppk...',
  '.....kppppPpppk...',
  '....kpppkkPpppk...',
  '...kpppk..kPppk...',
  '..kpPpk....kPpk...',
  '.kbBbbk....kbbBk..',
  '.kkkkkk....kkkkk..',
];

const hurt = [
  '..................',
  '....kk..kk........',
  '...khhkkhhk.kk....',
  '..khhhhhhhhkhhk...',
  '.khhhhhhhhhhhhk...',
  '.khhHhhhhhhhhhhk..',
  'khHhhhhhhhhhhhhk..',
  'khhhhhhhhhhhhhhk..',
  'khhhLLLLhhLLLhhk..',
  'khhLssssLsssssk...',
  'khkkkkssskkkkssk..',
  'kSkkkkkskkkkksck..',
  'kSkkkkssskkkksk...',
  '.kSssssssssssk....',
  '.kSsssmmmmsssk....',
  '..kSSsssssssk.....',
  '...kkSSSSSkk......',
  '..kWwwwrrwwwk.....',
  '.kWWwwwrrwwwqk....',
  'kWWwwwwrRwwwqqk...',
  'kWkwwwwrRwwwkqk...',
  'kLkwwwwrRwwwkLk...',
  'kLkqqqqqqqqqkkk...',
  '.k.kppppppppk.....',
  '...kppppPpppk.....',
  '...kpppkkPppk.....',
  '...kpppk.kPpk.....',
  '...kpPpk.kPpk.....',
  '..kbBbbk.kbbBk....',
  '..kkkkkk.kkkkk....',
];

const hold = [
  '.kk............kk.',
  'kyYk..kk..kk..kyYk',
  'kLLk.khhkkhhk.kLLk',
  'kLsk.khhhhhhhkksLk',
  'kssk.khhhhhhhhhssk',
  '.kskhhhhhhhhhhhsk.',
  '.kskhhhhhhhhhhhsk.',
  '.kskhhhhhhhhhhhsk.',
  '.kskhhLLLLhLLLhsk.',
  '.kskhLssssLsssssk.',
  '.kskkkkksssskkkkk.',
  '.kskckkkssskckksk.',
  '.kskkkkksssskkkks.',
  '.ksksssssssssssk..',
  '.kskSsssmmmmsssk..',
  '.kWkkSSsssssssk...',
  '.kWwkkkSSSSSkk....',
  '.kWwwwwwrrwwwk....',
  '..kWwwwwrrwwwqk...',
  '..kWwwwwrRwwwqk...',
  '..kWwwwwrRwwwqk...',
  '..kLwwwwrRwwwqk...',
  '..kkqqqqqqqqqqk...',
  '...kppppppppk.....',
  '...kppppPpppk.....',
  '...kpppkkPppk.....',
  '...kpppk.kPpk.....',
  '...kpPpk.kPpk.....',
  '..kbBbbk.kbbBk....',
  '..kkkkkk.kkkkk....',
];

export const HERO: Record<string, SpriteDef> = {
  hero_intern: {
    w: 18,
    h: 30,
    legend,
    frames: { idle0, idle1, attack, hurt, hold },
    ox: 9,
    oy: 29,
  },
};
