import type { SpriteDef } from '../sprite.ts';

/**
 * HUD pips (9×9), minimap marks (7×7) and enemy intent icons (11×11).
 * Single frame 'idle0', anchor top-left (0, 0).
 * Warm = health, coins, fire; cold = soul, armour, ink, water.
 * Legend: same characters as render/art/items.ts.
 */
const legend: Record<string, string> = {
  '.': '',
  k: 'ink0', j: 'ink1', n: 'ink2', N: 'ink3',
  1: 'cold1', 2: 'cold2', 3: 'cold3', 4: 'cold4', 5: 'cold5', 6: 'cold6',
  '=': 'teal0', 7: 'teal1', 8: 'teal2', 9: 'teal3', t: 'teal4', T: 'teal5',
  0: 'vio0', v: 'vio1', V: 'vio2', i: 'vio3', I: 'vio4', l: 'vio5',
  M: 'red0', m: 'red1', x: 'red2', r: 'red3', R: 'red4', P: 'red5',
  U: 'orange1', u: 'orange2', o: 'orange3', O: 'orange4',
  A: 'gold1', a: 'gold2', z: 'gold3', Z: 'gold4', W: 'cream',
  '%': 'wood0', b: 'wood1', B: 'wood2', c: 'wood3', C: 'wood4',
  '&': 'green0', f: 'green1', F: 'green2', e: 'green3', E: 'green4',
  D: 'grey0', d: 'grey1', G: 'grey2', g: 'grey3', y: 'grey4', Y: 'white', w: 'paper', q: 'paper2',
  Q: 'skin0', S: 'skin1', s: 'skin2', L: 'skin3',
};

const def = (w: number, h: number, rows: string[]): SpriteDef => ({ w, h, legend, frames: { idle0: rows }, ox: 0, oy: 0 });
const hud = (rows: string[]) => def(9, 9, rows);
const map = (rows: string[]) => def(7, 7, rows);
const intent = (rows: string[]) => def(11, 11, rows);

export const HUD_ICONS: Record<string, SpriteDef> = {
  // ── HUD pips 9×9 ──────────────────────────────────────────────────
  hud_heart_full: hud([
    '.kkk.kkk.',
    'kRPRkRrrk',
    'kPRrrrrxk',
    'kRrrrrrxk',
    'kRrrrrrxk',
    '.kRrrrxk.',
    '..krrxk..',
    '...kxk...',
    '....k....',
  ]),
  hud_heart_half: hud([
    '.kkk.kkk.',
    'kRPRkNNnk',
    'kPRrrNnnk',
    'kRrrrNnnk',
    'kRrrrNnnk',
    '.kRrrnnk.',
    '..krrnk..',
    '...kxk...',
    '....k....',
  ]),
  hud_heart_empty: hud([
    '.kkk.kkk.',
    'k11NkNNnk',
    'k1NNNNnnk',
    'kNNNNNnnk',
    'kNNNNnnnk',
    '.kNNnnnk.',
    '..kNnnk..',
    '...knk...',
    '....k....',
  ]),
  hud_soul_full: hud([
    '.kkk.kkk.',
    'k565k544k',
    'k6544443k',
    'k5444432k',
    'k5444432k',
    '.k54443k.',
    '..k443k..',
    '...k3k...',
    '....k....',
  ]),
  hud_soul_half: hud([
    '.kkk.....',
    'k565k....',
    'k6544k...',
    'k5444k...',
    'k4444k...',
    '.k443k...',
    '..k43k...',
    '...k2k...',
    '....k....',
  ]),
  hud_armor: hud([
    'kkkk.....',
    'k56kkkkk.',
    'k5666654k',
    'k5444443k',
    'k5444443k',
    'k4444432k',
    '.k44332k.',
    '..k432k..',
    '...kkk...',
  ]),
  hud_coin: hud([
    '..kkkkk..',
    '.kZZZzak.',
    'kZWzzzzak',
    'kZzaaazak',
    'kzzazazAk',
    'kzzaaaaAk',
    'kzzzzzaAk',
    '.kaaaaAk.',
    '..kkkkk..',
  ]),
  hud_bomb: hud([
    '.....kOWO',
    '....kC.O.',
    '..kkGkk..',
    '.k25NNnk.',
    'k23NNNn2k',
    'k2NNNnn2k',
    'kNNNnnn2k',
    '.knnnn2k.',
    '..kkkkk..',
  ]),
  hud_key: hud([
    '.kkkk....',
    'kZzzak...',
    'kzkkak...',
    'kzaaAk...',
    '.kzak....',
    '.kzakk...',
    '.kzaZk...',
    '.kzakk...',
    '..kk.....',
  ]),
  hud_ink: hud([
    '....k....',
    '...klk...',
    '...kIk...',
    '..kIiVk..',
    '.kIliiVk.',
    '.klIiiVk.',
    '.kIiiVvk.',
    '..kVVvk..',
    '...kkk...',
  ]),

  // ── Minimap marks 7×7 ─────────────────────────────────────────────
  map_treasure: map([
    '.k.k.k.',
    'kZkZkzk',
    'kZZzzak',
    'kZrzrak',
    'kzzzzak',
    'kaaaaAk',
    'kkkkkkk',
  ]),
  map_shop: map([
    '..kkk..',
    '.kZZzk.',
    'kZWzzak',
    'kZzazak',
    'kzzzaAk',
    '.kaaAk.',
    '..kkk..',
  ]),
  map_boss: map([
    '.kkkkk.',
    'kYYYYyk',
    'kYkYkgk',
    'kykYkgk',
    '.kyyGk.',
    '.kykGk.',
    '..kkk..',
  ]),
  map_secret: map([
    'kkkkkkk',
    'kyykggk',
    'kykygGk',
    'kyykgGk',
    'kgggkGk',
    'kggkGdk',
    'kkkkkkk',
  ]),
  map_deal: map([
    '..kkk..',
    '.kRPrk.',
    'kRrxrxk',
    'kRxRxrk',
    '.kxxxk.',
    '.kxkxk.',
    '.kk.kk.',
  ]),
  map_start: map([
    '.kkkkk.',
    'kCCccBk',
    'kCcccBk',
    'kCccZBk',
    'kCcccBk',
    'kcccBBk',
    'kkkkkkk',
  ]),

  // ── Intent icons 11×11 ────────────────────────────────────────────
  int_attack: intent([
    '...........',
    '..kk.kk.kk.',
    '.kLskLskLsk',
    '.kLskLskssk',
    '.kLskssksSk',
    'kkkkkkkssSk',
    'kLLLLLLksSk',
    'kkkkkkkssSk',
    '..kSssssSSk',
    '..kSSSSSSk.',
    '...kkkkkk..',
  ]),
  int_heavy: intent([
    '.O.........',
    'O.O.kkkkk..',
    '.OkkRPPPRk.',
    '.kRPPRRRRrk',
    '.kPRRRRRRxk',
    'kkkkRRRRrxk',
    'kRRRkRRrrxk',
    'kRrrkrrrxxk',
    '.kkkrrrxxk.',
    '...kYYYyyk.',
    '...kkkkkkk.',
  ]),
  int_block: intent([
    '.kkkkkkkkk.',
    'k566666654k',
    'k564444443k',
    'k544444443k',
    'k544444443k',
    'k444444432k',
    '.k4444432k.',
    '.k4444332k.',
    '..k44332k..',
    '...k432k...',
    '....kkk....',
  ]),
  int_heal: intent([
    '...kkkkk...',
    '...kEEek...',
    '...kEeek...',
    'kkkkEeekkkk',
    'kEEEEeeeeek',
    'kEeeeeeeeFk',
    'kkkkeeeFkkk',
    '...keeFk...',
    '...keFFk...',
    '...kkkkk...',
    '...........',
  ]),
  int_summon: intent([
    '.......kk..',
    '......kPRk.',
    '....kkkRwk.',
    '...kWWWwwk.',
    '..kWWkwwwqk',
    '.kWWWWwwqqk',
    'kRWWwwwwqqk',
    '.kkkwwwqqk.',
    '...kkqqqk..',
    '.....kkk...',
    '...........',
  ]),
  int_ink: intent([
    '.....k.....',
    '....klk.k..',
    '.kk.kIkkIk.',
    'kIkkIiIIik.',
    '.kIliiiiik.',
    '..kIiiiiVkk',
    '.kIiiiiVVik',
    'kIiiiiVVvk.',
    '.kVkVVvkk..',
    '..k.kVk....',
    '.....k.....',
  ]),
  int_pin: intent([
    '...........',
    '...........',
    '.kkkkkkkkk.',
    'kYYyyyyyygk',
    'kykkkkkkkgk',
    'kyk.....kgk',
    'kyk.....kgk',
    'kyk.....kGk',
    'kgk.....kGk',
    '.k.......k.',
    '...........',
  ]),
  int_ember: intent([
    '.....k.....',
    '....kok....',
    '....kok.k..',
    '...kuOkkok.',
    '..kuoOOkuk.',
    '..kuOZOouk.',
    '.kuoZWZOuk.',
    '.kuoZWWZok.',
    '.kxuoZZoxk.',
    '..kxuoouk..',
    '...kkkkk...',
  ]),
  int_censor: intent([
    '..kkkkkkk..',
    '..kWWWWqk..',
    '..kWgggqk..',
    'kkkkkkkkkkk',
    'kdddddddddk',
    'kjjjjjjjjjk',
    'kjjjjjjjjjk',
    'kkkkkkkkkkk',
    '..kWgggqk..',
    '..kqqqqqk..',
    '..kkkkkkk..',
  ]),
  int_steal: intent([
    '....kkkk...',
    '...kLLssk..',
    '..kLsssssk.',
    '..kssSssSk.',
    '.kLsk.ksSk.',
    '.kLk..kSk..',
    'kLk.kkkSk..',
    'kk.kZZkk...',
    '..kZzzak...',
    '..kzzaAk...',
    '...kkkk....',
  ]),
  int_pinch: intent([
    '.......kk..',
    '......kRRk.',
    '.....kRrrk.',
    '...kkRrrk..',
    '..kRPRrk.kk',
    '.kRPRrrkkRk',
    '.kRRrrrrRrk',
    'kRRrrrrrrxk',
    'kRrrrrrrxk.',
    '.kxrrrrxk..',
    '..kkkkkk...',
  ]),
  int_tide: intent([
    '...........',
    '..kk....kk.',
    '.kTTk..kTTk',
    'kT99Tkkt99k',
    'k9kk9TT9kk.',
    'kk..k99k...',
    '.kk....kk..',
    'kTTk..kTTk.',
    'T99Tkkt99Tk',
    '9kk9TT9kk9k',
    'k..k99k..kk',
  ]),
  int_submerge: intent([
    '...kkkkk...',
    '...k545k...',
    '...k434k...',
    'kkkk434kkkk',
    '.k5444443k.',
    '..k44433k..',
    '...k433k...',
    '....k3k....',
    'kkkkkkkkkkk',
    'kt9t9t9t9tk',
    'kkkkkkkkkkk',
  ]),
  int_shine: intent([
    '.....k.....',
    '....k6k....',
    '....k6k..k.',
    '...k565.k6k',
    'kkkk5Y5kkk.',
    'k665YYY566k',
    '.kkk5Y5kkkk',
    '...k565k...',
    '....k6k....',
    '....k6k....',
    '.....k.....',
  ]),
  int_anchor: intent([
    '....kkk....',
    '...kyGgk...',
    '...kgkGk...',
    '.kkkkgkkkk.',
    '.kyyygGGdk.',
    '.kkkkgkkkk.',
    'kk..kgk..kk',
    'kgk.kgk.kGk',
    'kgGkkgkkGdk',
    '.kgGGgGGdk.',
    '..kkkkkkk..',
  ]),
  int_strike: intent([
    '...kkkkk...',
    '..kRPRrxk..',
    '..kRrrrxk..',
    '...kxxmk...',
    '....kmk....',
    '..kkkkkkk..',
    '.kCccccBBk.',
    'kkkkkkkkkkk',
    'krrrrrrrrxk',
    'kxxxxxxxxmk',
    'kkkkkkkkkkk',
  ]),
  int_erase: intent([
    '...........',
    '...........',
    '....kkkkkkk',
    '...kPPPP55k',
    '..kPPPP554k',
    '.kkkkkkk44k',
    '.kRRRk443kk',
    '.kRrrk332k.',
    '.krrxk221k.',
    '.kkkkkkkk..',
    'k.k........',
  ]),
};
