import type { SpriteDef } from '../sprite.ts';

/**
 * Item icons, 16×16, one frame each. Anchor: bottom centre (8, 15).
 * Light: warm key from the upper left, cold rim on the right edge, shadows cold.
 *
 * Shared legend (one char per palette colour):
 *   k ink0  j ink1  n ink2  N ink3        1..6 cold1..cold6
 *   = teal0 7 teal1 8 teal2 9 teal3 t teal4 T teal5
 *   0 vio0  v vio1  V vio2  i vio3  I vio4  l vio5
 *   M red0  m red1  x red2  r red3  R red4  P red5
 *   U orange1 u orange2 o orange3 O orange4
 *   A gold1 a gold2 z gold3 Z gold4 W cream
 *   % wood0 b wood1 B wood2 c wood3 C wood4
 *   & green0 f green1 F green2 e green3 E green4
 *   D grey0 d grey1 G grey2 g grey3 y grey4 Y white w paper q paper2
 *   Q skin0 S skin1 s skin2 L skin3
 */
const legend: Record<string, string> = {
  '.': '',
  k: 'ink0', j: 'ink1', n: 'ink2', N: 'ink3',
  1: 'cold1', 2: 'cold2', 3: 'cold3', 4: 'cold4', 5: 'cold5', 6: 'cold6',
  '=': 'teal0', 7: 'teal1', 8: 'teal2', 9: 'teal3', t: 'teal4', T: 'teal5',
  0: 'vio0', v: 'vio1', V: 'vio2', i: 'vio3', I: 'vio4', l: 'vio5',
  M: 'red0', m: 'red1', x: 'red2', r: 'red3', R: 'red4', P: 'red5',
  U: 'orange1', u: 'orange2', o: 'orange3', O: 'orange4',
  A: 'gold1', a: 'gold2', z: 'gold3', Z: 'gold4', W: 'cream',
  '%': 'wood0', b: 'wood1', B: 'wood2', c: 'wood3', C: 'wood4',
  '&': 'green0', f: 'green1', F: 'green2', e: 'green3', E: 'green4',
  D: 'grey0', d: 'grey1', G: 'grey2', g: 'grey3', y: 'grey4', Y: 'white', w: 'paper', q: 'paper2',
  Q: 'skin0', S: 'skin1', s: 'skin2', L: 'skin3',
};

const icon = (rows: string[]): SpriteDef => ({ w: 16, h: 16, legend, frames: { idle0: rows }, ox: 8, oy: 15 });

export const ITEM_ICONS: Record<string, SpriteDef> = {
  // Крепкий кофе — red office mug, steam.
  item_coffee: icon([
    '................',
    '.....6....6.....',
    '....65...65.....',
    '.....56...56....',
    '....65...65.....',
    '.kkkkkkkkkkk....',
    '.kRbbBBBbbxk....',
    '.kPRRRRRRRxkkk..',
    '.kRrrrrrrrxkrxk.',
    '.kRrrrrrrr3k.xk.',
    '.kRrrrrrrr3k.xk.',
    '.kRrrrrrrr3krxk.',
    '.kRrrrrrrrxkkk..',
    '.kRrrrrrrxxk....',
    '..kxxxxxxxk.....',
    '...kkkkkkk......',
  ]),
  // Бутерброд — open-faced: toast, cheese slice, round of sausage.
  item_sandwich: icon([
    '................',
    '...kkkkkkkkkk...',
    '.kkOOOOOOOOOOkk.',
    'kOOWWWWxxxxWWOuk',
    'kOWWWWxPPRRxWWuk',
    'kuWWWxPPRRRRxq4k',
    '.kOWWxPRRPRRx4k.',
    '.kOWWxRRRRRrx4k.',
    '.kOZZxRPRRrrxuk.',
    '.kOZzzxRRrrxquk.',
    '.kOZzazxxxxqquk.',
    '.kOZzzzzaqqqquk.',
    '.kOZzzzzaqqqquk.',
    '.kuaaaaaaqqqquk.',
    '.kuuuuuuuuuuuuk.',
    '..kkkkkkkkkkkk..',
  ]),
  // Бронежилет из папок — dark vest plated with blue folders.
  item_vest: icon([
    '..kkkk....kkkk..',
    '..kNNk....kNNk..',
    '..kNNNk..kNNNk..',
    '.kkNNNNkkNNNNkk.',
    'k45kkkNNNNkkk54k',
    'kwwwwkNNNNkwwwyk',
    'k5444kNNNNk4443k',
    'k4333kNNNNk3332k',
    'k3222kNNNNk2221k',
    'kkkkkkNNNNkkkkkk',
    'k45kkkNNNNkkk54k',
    'kwwwwkNNNNkwwwyk',
    'k4333kNNNNk3332k',
    'k3222kNNNNk2221k',
    '.kkkkkkkkkkkkkk.',
    '................',
  ]),
  // Кольцевая скоба — steel binder ring with a hinge.
  item_ring: icon([
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkYYyyydkk...',
    '..kYYyyyyygdgk..',
    '..kYyykkkkyggk..',
    '.kYyyk....kgGGk.',
    '.kyyk......kG4k.',
    '.kyyk......kG4k.',
    '.kygk......kG4k.',
    '.kggk......kGdk.',
    '.kgggk....kGGdk.',
    '..kgggkkkkGGdk..',
    '..kGgggGGGGddk..',
    '...kkGGyyddkk...',
    '.....kkkkkk.....',
  ]),
  // Копирка — carbon sheet behind a written page.
  item_carbon: icon([
    '................',
    '.....kkkkkkkkkk.',
    '.....k33333332k.',
    '.....k34444221k.',
    '.kkkkkkkkkk221k.',
    '.kWWWWWWWqk441k.',
    '.kWggggggqk221k.',
    '.kWwwwwwwqk441k.',
    '.kWgggggwqk221k.',
    '.kWwwwwwwqk111k.',
    '.kWggggggqkkkkk.',
    '.kWwwwwwwqk.....',
    '.kWgggwwwqk.....',
    '.kWwwwwwwqk.....',
    '.kqqqqqqqqk.....',
    '.kkkkkkkkkk.....',
  ]),
  // Дырокол — side view: dark lever raised at the front, pin, sheet in the slot, blue base.
  item_punch: icon([
    '................',
    '................',
    '..kkkkkk........',
    '.kGggggGkkkkk...',
    '.kdGGGGGggggGkk.',
    '..kddDDDDGGGGgGk',
    '...kkkkDDDDDDdDk',
    '....kykkkkkkk3Dk',
    '....kgk....k432k',
    '.kkkkkkkkkkk432k',
    'kWWwwwwwwwwk321k',
    'kkkkkkkkkkkkkkkk',
    'k5444444444444k.',
    'k3222222222221k.',
    '.kkkkkkkkkkkkk..',
    '................',
  ]),
  // Лупа — brass-rimmed magnifier, cold glass, wooden handle.
  item_loupe: icon([
    '....kkkkk.......',
    '..kkZZzzzkk.....',
    '.kZzkkkkkazk....',
    '.kZk6655544ak...',
    'kZk66555444kak..',
    'kzk65554443kak..',
    'kzk55544433kAk..',
    'kzk54443332kAk..',
    '.kak4433322kAk..',
    '.kaAk33322kAAk..',
    '..kAAkkkkkAAkk..',
    '....kkkkkkkBCck.',
    '...........kCcBk',
    '............kcBk',
    '.............kbk',
    '..............k.',
  ]),
  // Бумажный самолётик — paper plane heading up-right.
  item_plane: icon([
    '................',
    '..............kk',
    '............kkWk',
    '..........kkWWwk',
    '........kkWWWwqk',
    '......kkWWWWwwk.',
    '....kkWWWWWwwqk.',
    '..kkWWWWWWwwqk..',
    '.kWWWWWWwkqqqk..',
    '..kkkkwwk44qk...',
    '......kk444k....',
    '.......k43k.....',
    '.......k3k......',
    '.......kk.......',
    '................',
    '................',
  ]),
  // Праздничный динамит — three red sticks, gold bow, lit fuse.
  item_dynamite: icon([
    '...........W....',
    '..........WZW...',
    '.........oZWZo..',
    '..........kZk...',
    '.........kdk....',
    '...kkkkkkdkkk...',
    '..kPRRkRRRkRrk..',
    '..kRrrkRrrkr3k..',
    '..kRrrkkkkkr3k..',
    '.kkZkkZzkzZkkkk.',
    'kZZzzkzZkZzkzzak',
    '.kkakkkaZakkkak.',
    '..kRrrkakakr3k..',
    '..kRrrkkRkkr3k..',
    '..kxxxkxxxkxmk..',
    '..kkkkkkkkkkkk..',
  ]),
  // Двусторонний скотч — white roll on a cardboard core, red liner tail.
  item_tape: icon([
    '................',
    '....kkkkkkk.....',
    '..kkWWWWwwwkk...',
    '.kWWWwwwwwwwqk..',
    '.kWWwkkkkkwwqk..',
    'kWWwkCCccckww4k.',
    'kWwkCckkkBckw4k.',
    'kWwkCk...kckw4k.',
    'kWwkck...kBkw4k.',
    'kwwkcBkkkBBkqqk.',
    'kwwqkcBBBBkqqqk.',
    '.kwqqkkkkkqqqkk.',
    '.kqqqqqqqqqqkrrk',
    '..kkqqqqqqkkrxk.',
    '....kkkkkkkrxk..',
    '..........kkk...',
  ]),
  // Магнит — red horseshoe magnet with steel tips.
  item_magnet: icon([
    '................',
    '.....kkkkkk.....',
    '...kkRRRRRrkk...',
    '..kRRRrrrrrrxk..',
    '.kRRrrkkkkrrxxk.',
    '.kRrrk....kxxmk.',
    '.kRrrk....kxxmk.',
    '.kRrrk....kxx3k.',
    '.kRrrk....kxx3k.',
    '.kRrrk....kxxmk.',
    '.kkkkk....kkkkk.',
    '.kYyyk....kyg4k.',
    '.kyggk....kgG4k.',
    '.kgGGk....kGGdk.',
    '.kkkkk....kkkkk.',
    '................',
  ]),
  // Скрепка-паук — paperclip body, wire legs, red eyes.
  item_spider: icon([
    '................',
    '................',
    '..k..........k..',
    '.kyk..kkkk..kyk.',
    '.kyk.kGggGk.kyk.',
    '..kykgRggRgkyk..',
    '...kkGggggGkk...',
    '.kkkykkkkkkykkk.',
    'kyyyykyyyykyyyyk',
    '.kkkkyykkyykkkk.',
    '...kkyykkyykk...',
    '..kykkyyyykkyk..',
    '.kyk.kkyykk.kyk.',
    '.kyk...kk...kyk.',
    '..k..........k..',
    '................',
  ]),
  // Кактус на столе — potted cactus with a pink flower.
  item_cactus: icon([
    '......kkkk......',
    '.....kPRRPk.....',
    '.....kkEEkk.....',
    '....kEEeetk.....',
    '.kk.kEWeetk.....',
    'kEEkkEeeeFk.kk..',
    'kEekkEeWeFkkEtk.',
    'kEeEEEeeeFkketk.',
    '.kFFFEeeeFeeetk.',
    '..kkkEeWeFFFFk..',
    '....kEeeeFkkk...',
    '.kkkkkkkkkkkkkk.',
    '.kOoooooooooouk.',
    '..kuuuuuuuuuUk..',
    '..kuuuuuuuuuUk..',
    '...kkkkkkkkkk...',
  ]),
  // Чернильница — violet ink jar with a quill.
  item_inkwell: icon([
    '.............kk.',
    '...........kkYk.',
    '..........kYYwk.',
    '.........kYYwk..',
    '........kYwwk...',
    '.......kYwgk....',
    '.....kkkkgkkk...',
    '.....kZzzkzak...',
    '...kkkkkkkkkkk..',
    '...kYlIIIIIIVk..',
    '...klIiiiiii3k..',
    '...kIiiiiiiV3k..',
    '...kIiiiiiVV3k..',
    '...kiiiiiVVVvk..',
    '...kVVVVVVVvvk..',
    '...kkkkkkkkkkk..',
  ]),
  // Ржавые ножницы — open rusty blades, red handles.
  item_scissors: icon([
    '.kk.........kk..',
    '.kyk.......kgk..',
    '..kyk.....k4k...',
    '..kyUk...kg4k...',
    '...kyUk.kgUk....',
    '...kyck.kcGk....',
    '....kykkgck.....',
    '.....kkdkk......',
    '....kgkkkyk.....',
    '...kgGk.kyyk....',
    '..kxxk...kxxk...',
    '.kxkkxk.kxkkxk..',
    '.kxk.xk.kxk.xk..',
    '.kmxxmk.kmxxmk..',
    '..kkkk...kkkk...',
    '................',
  ]),
  // Тлеющая спичка — match with a live flame.
  item_match: icon([
    '...........k....',
    '..........kok...',
    '.........kuOok..',
    '.........kuZOk..',
    '........kuZWOuk.',
    '........kuoWZok.',
    '.........kxRRk..',
    '........kxrrk...',
    '.......kCBk.....',
    '......kCBk......',
    '.....kCBk.......',
    '....kCBk........',
    '...kCBk.........',
    '..kCBk..........',
    '..kBk...........',
    '...k............',
  ]),
  // Сломанный калькулятор — cracked screen and body.
  item_calculator: icon([
    '................',
    '.kkkkkkkkkkkkk..',
    '.kGGGGGGGGGGGk..',
    '.kGkkkkkkkkkdk..',
    '.kGkTTT9Y99kdk..',
    '.kGk9TYkT99kdk..',
    '.kGk99Y9999kdk..',
    '.kGkkkkkkkkkdk..',
    '.kGddddddddd3k..',
    '.kGWWdWWdWWd3k..',
    '.kGyydyydyyd3k..',
    '.kGWWdWWdWWd3k..',
    '.kGyydyydyyd3k..',
    '.kGWWdWWdWWdok..',
    '.kdDDDDDDDDDDk..',
    '..kkkkkkkkkkk...',
  ]),
  // Счастливая монетка — gold coin, four-leaf clover, glint.
  item_lucky: icon([
    '.............W..',
    '............WYW.',
    '......kkkk...W..',
    '....kkZZZZkk....',
    '...kZZzzzzZZk...',
    '..kZzzZzzzzzak..',
    '..kZzEEzeEzaak..',
    '.kZzZEezeFzzaAk.',
    '.kZzzzzfzzzza4k.',
    '.kZzzEezeFzza4k.',
    '.kZzzeFzFFzza4k.',
    '..kZzzzzzzzaAk..',
    '..kZzazzzzaaAk..',
    '...kaaaaaaAAk...',
    '....kkAAAAkk....',
    '......kkkk......',
  ]),
  // Батарейка — copper-top cell with a charge bolt.
  item_battery: icon([
    '................',
    '......kkkk......',
    '......kYyk......',
    '....kkkkkkkk....',
    '....kZZzzzak....',
    '....kZzzzzak....',
    '....kaaaaaAk....',
    '....k2NNZN3k....',
    '....k2NZZN3k....',
    '....k2ZZNN3k....',
    '....k2NZZZ3k....',
    '....k2NNZN3k....',
    '....k2NZNNnk....',
    '....k2NNNNnk....',
    '....kkkkkkkk....',
    '................',
  ]),
  // Бесконечная ручка — fountain pen, gold nib, infinity glint.
  item_pen: icon([
    '.............kk.',
    '............kVik',
    '.WW.WW.....kViIk',
    'W..W..W...kVIik.',
    '.WW.WW...kViIk..',
    '........kzZzk...',
    '.......kVIik....',
    '......kViIk.....',
    '.....kVIik......',
    '....kzZzk.......',
    '...kZzZk........',
    '..kZzak.........',
    '..kzak..........',
    '..kak...........',
    '..kk............',
    '................',
  ]),
  // Мятная жвачка — mint blister of gum pellets with a leaf.
  item_gum: icon([
    '.............kkk',
    '............kEEk',
    '.kkkkkkkkkkkEeFk',
    '.kTTTTTTTTTkEFk.',
    '.kTtkkkttkkkkkk.',
    '.kTkYYykkYYyk8k.',
    '.kTkYyykkYyyk8k.',
    '.kTkyygkkyygk8k.',
    '.kTtkkkttkkkt8k.',
    '.kTtkkk9tkkk98k.',
    '.kTkYYykkYYyk8k.',
    '.kTkYyykkYyyk8k.',
    '.kTkyygkkyygk8k.',
    '.kTtkkkttkkkt8k.',
    '.kT88888888888k.',
    '.kkkkkkkkkkkkkk.',
  ]),
  // Табель — attendance sheet with red marks and a clock.
  item_timesheet: icon([
    '..kkkkkkkkkk....',
    '..kxrrrrrrrrk...',
    '..kWWWWWWWW4k...',
    '..kWgwgwgwg4k...',
    '..kWrwgwrwg4k...',
    '..kWgwrwgwg4k...',
    '..kWgwgwrwg4k...',
    '..kWrwgwgkkkkk..',
    '..kWgwgwk34443k.',
    '..kWgwrk34WWW32k',
    '..kWgwgk4WWkW41k',
    '..kWgwgk4WkkW41k',
    '..kqqqqk4WWWW41k',
    '..kkkkkk34WW421k',
    '.......kk33221kk',
    '........kkkkkk..',
  ]),
  // Кассовый аппарат — brass register with a drawer.
  item_register: icon([
    '................',
    '.....kkkkkk.....',
    '.....kTT99k.....',
    '.....kkkkkk.....',
    '.......kak......',
    '..kkkkkkkkkkkk..',
    '.kZZZZZzzzzzzak.',
    '.kZWzWzWzWzWz4k.',
    '.kzazazazazaa4k.',
    '.kZWzWzWzWzoa4k.',
    '.kzazazazazuaAk.',
    'kkkkkkkkkkkkkkkk',
    'kcZzZzEeEZzZcBbk',
    'kCcccccccccccccB',
    'kcBBBBBkkBBBBBbk',
    '.kkkkkkkkkkkkkk.',
  ]),
  // Бухгалтерская книга — green ledger, brass corners.
  item_ledger: icon([
    '................',
    '..kkkkkkkkkkkk..',
    '..kZzkEEEEEkzak.',
    '..kzkEEeeeeFkak.',
    '..kkEEeeeeeeFkk.',
    '..kaEeeZZzeeFtk.',
    '..kaEeZzzaeeFtk.',
    '..kaEezzaAeeFtk.',
    '..kaEeeaAeeeFtk.',
    '..kkeeeeeeeFFkk.',
    '..kzkeeeeeFFkak.',
    '..kaAkFFFFFkAAk.',
    '..kkkkkkkkkkkkk.',
    '...kwwwwwwwwwqk.',
    '...kqqqqqqqqqqk.',
    '...kkkkkkkkkkkk.',
  ]),
  // Толстый кошелёк — bulging leather wallet, cash and a coin.
  item_wallet: icon([
    '................',
    '................',
    '...kkkkkk.......',
    '..kEEEEEEkkkk...',
    '..kEeeefkEEEEk..',
    '.kkeeFkkeeeeFk..',
    'kCCkkkCCCkkkkkk.',
    'kCcccccccccccB3k',
    'kCcccccccckkkk3k',
    'kCccccccckZZzkkk',
    'kcccccccckzzak3k',
    'kccccccccckkkBBk',
    'kcBcccccccccBBbk',
    '.kBBBBBBBBBBBbk.',
    '..kkkkkkkkkkkk..',
    '................',
  ]),
  // Ведро льда — steel bucket with ice cubes.
  item_ice: icon([
    '.....kkkkkk.....',
    '.....k6YY5k.....',
    '.kkkkkk55kkkkkk.',
    '.k6YY5k44k6YY5k.',
    '.k6554k33k6554k.',
    '.k5544kkkk5T44k.',
    '.k54T3k65k5443k.',
    'kkkkkkkkkkkkkkkk',
    'kYyyyyyyyyyyyy4k',
    'kkygggggggggGkkk',
    'kykgggggggggGkGk',
    'kkkgyggggggGGkkk',
    '..kgygggggGG4k..',
    '..kggggggGGG4k..',
    '...kGGGGGGGGk...',
    '....kkkkkkkk....',
  ]),
  // Настольная лампа — green banker's lamp with warm glow.
  item_lamp: icon([
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kEEEEEEEEEtk..',
    '.kEeeeeeeeeeFtk.',
    'kFeeeeeeeeeeeFfk',
    'kffffffffffffffk',
    '.kWWZZZZZZZZZWk.',
    '..kkkkkkkkkkkk..',
    '.......kzk..k...',
    '.......kzk..Z...',
    '.......kak......',
    '......kzZak.....',
    '...kkkkkkkkkk...',
    '..kZZzzzzzzaak..',
    '..kkkkkkkkkkkk..',
  ]),
  // Гирлянда — sagging wire with coloured bulbs.
  item_garland: icon([
    '................',
    '................',
    '................',
    'G..............G',
    '.G............G.',
    '..GG........GG..',
    '.kddG......Gddk.',
    'kPRRrk....kTTt9k',
    'kRrrrkG..GkTt99k',
    'kRrrxk.GG.kt998k',
    '.kxxk.kddk.k88k.',
    '..kk.kWZZzk.kk..',
    '.....kZzzzk.....',
    '.....kZzzak.....',
    '......kaak......',
    '.......kk.......',
  ]),
  // Сломанные часы — alarm clock, cracked glass, bent hand.
  item_clock: icon([
    '.......kkk......',
    '.kkk..kyGk..kkk.',
    'kYyGk.kkyk.kyGGk',
    '.kkk..kyGk..kkk.',
    '....kkkkkkkk....',
    '...k34444432k...',
    '..k34WWWWWW21k..',
    '..k4WWkWWWWW5k..',
    '..k4WWWkWWWW5k..',
    '..k4WWWWkkkW5k..',
    '..k3WGWWWWWq1k..',
    '..k3wWGWWWqq1k..',
    '...k3wGGwqq1k...',
    '....k311111k....',
    '...kGkkkkkkGk...',
    '...kk......kk...',
  ]),
  // Резиновые перчатки — yellow rubber glove.
  item_gloves: icon([
    '....k.k.k.......',
    '...kZkZkZk......',
    '...kZkzkzkk.....',
    '...kZkzkzkZk....',
    '...kZkzkzkzk....',
    '.k.kZzzzzzzk....',
    'kZkkZzzzzz4k....',
    'kZzkZzzzzz4k....',
    '.kZzZzzzzz4k....',
    '..kZzzzzzaak....',
    '...kzzzzzaAk....',
    '...kzzzzaaAk....',
    '..kZZZZZzzzAk...',
    '..kaaaaaaaaAk...',
    '...kkkkkkkkk....',
    '................',
  ]),
  // Кошачья миска — red bowl with a fish on top.
  item_bowl: icon([
    '................',
    '................',
    '................',
    '......kkk.......',
    'kk...k45k.......',
    'k5k.k455555kk...',
    '.k4kk4444445Yk..',
    '.k3k4444444kk4k.',
    'k33kk33333333k..',
    'kk...kkkkkkkk...',
    '...kkkkkkkkkk...',
    '..kRRRRRRRRR3k..',
    '.kRrrrrWrWrrr3k.',
    '.kRrrrrrWWrrrxk.',
    'kRrrrrrrrrrrrrxk',
    'kkkkkkkkkkkkkkkk',
  ]),
  // Флешка — blue USB stick with a heart sticker.
  item_flash: icon([
    '....kkkkkkkk....',
    '....kYYYYYyk....',
    '....kykkykGk....',
    '....kykkykGk....',
    '....kyyyyyGk....',
    '...kkkkkkkkkk...',
    '...k54444443k...',
    '...k4t444433k...',
    '...k44PR4Rr3k...',
    '...k44RRRRr3k...',
    '...k444Rrx32k...',
    '...k4444x332k...',
    '...k33333322k...',
    '...k32222221k...',
    '....kkkkkkkk....',
    '................',
  ]),
  // Грамота «Сотрудник месяца» — gold frame, star, red seal.
  item_award: icon([
    'kkkkkkkkkkkkkkkk',
    'kZZZZZZZZZZZZZak',
    'kZkkkkkkkkkkkkAk',
    'kZkWWWWWWWWW4kAk',
    'kZkWggggggggqkAk',
    'kZkWWWWZWWWWqkAk',
    'kZkWWWzZzWWWqkAk',
    'kzkWzzzZzzzwqkAk',
    'kzkWWazzzaWwqkAk',
    'kzkWWaAWaAWwqkAk',
    'kzkWwwwwwwkkkkAk',
    'kzkWggggwkRRRrkk',
    'kakqqqqqkRPRRrxk',
    'kaAAAAAAkRRRRxxk',
    'kkkkkkkkkkrkkxkk',
    '.........kxk.kk.',
  ]),
  // Двойной эспрессо — small white cup on a saucer, dark crema, double steam.
  item_espresso: icon([
    '................',
    '......6...6.....',
    '.....65..65.....',
    '......56..56....',
    '.....65..65.....',
    '...kkkkkkkkk....',
    '...kCCccBBbk....',
    '...kYYYyyyykkk..',
    '...kYyyyyygk4k..',
    '...kyyyyyggk4k..',
    '....kyyyggkkk...',
    '.kkkkkkkkkkkkk..',
    '.kYYyyyyyyyy4k..',
    '..kggggggggGk...',
    '...kkkkkkkkk....',
    '................',
  ]),
  // Кровавый контракт — contract signed with a blood drop.
  item_blood: icon([
    '..kkkkkkkkkk....',
    '.kWWWWWWWWWqk...',
    '.kWggggggww4k...',
    '.kWwwwwwwww4k...',
    '.kWgggggggw4k...',
    '.kWwwwwwwww4k...',
    '.kWggggwwwkkk...',
    '.kWwwwwwwkRk....',
    '.kWgggwwkRPrk...',
    '.kWwwwwkRPRrrk..',
    '.kWwwwwkRRRrxk..',
    '.kWwwwwkrRrrxk..',
    '.kqqqqqqkxxxk...',
    '.kkkkkkkkkkk....',
    '................',
    '................',
  ]),
  // Ночная смена — crescent moon cradling a clock.
  item_nightshift: icon([
    '...kkkk.........',
    '..kWZZk.........',
    '.kWZzk..........',
    '.kZzk...........',
    'kWZzk...........',
    'kZzk...kkkkk....',
    'kZzk..k34443k...',
    'kZzk.k3566654k..',
    'kZzak35665665k..',
    'kZzak4666k6664k.',
    '.kzak466kk6663k.',
    '.kzaak46666653k.',
    '..kaaAk456553k..',
    '...kkAAk33332k..',
    '.....kkkkkkkk...',
    '................',
  ]),
  // Премия — envelope stuffed with cash, a coin in front.
  item_bonus: icon([
    '.....kkkkkk.....',
    '..kkkkEEEEk.....',
    '..kEEkeFeEkkkk..',
    '..kEekeeeEkEEEk.',
    '..kEekEEEEkeFEk.',
    '..kEekkkkkkeeEk.',
    'kkkkkkkkkkkkkkkk',
    'kWWWWWWWWWWWWW4k',
    'kWkWWWWWWWWWWk4k',
    'kWWkWWWWWWWWkw4k',
    'kWWWkkWWWWkkkkkk',
    'kWWWWWkkkkkZZzak',
    'kwwwwwwwwwkzZzak',
    'kqqqqqqqqqkzzaAk',
    'kkkkkkkkkkkkkkkk',
    '................',
  ]),
  // Пакт с Цензором — contract under a black censor bar, red seal.
  item_pact: icon([
    '..kkkkkkkkkkkk..',
    '..kWWWWWWWWW4k..',
    '..kWggggggww4k..',
    '..kWwwwwwwww4k..',
    '..kWgggggggw4k..',
    'kkkkkkkkkkkkkkkk',
    'krroozzEEttIIVVk',
    'kjjjjjjjjjjjjjjk',
    'kkkkkkkkkkkkkkkk',
    '..kWgggggwwwqk..',
    '..kWwwwwwwkkkk..',
    '..kWggggwkrRrrk.',
    '..kWwwwwkrRPrxk.',
    '..kqqqqqkrrrrxk.',
    '..kkkkkkkkxxxkk.',
    '.........kkkk...',
  ]),
  // Ластик — pink eraser in a blue sleeve.
  item_eraser: icon([
    '................',
    '................',
    '................',
    '.....kkkkkkkkkk.',
    '....kPPPPP5555k.',
    '...kPPPPP5555k4k',
    '..kkkkkkkkkkk44k',
    '..kRRRRRk4443k4k',
    '..kRrrrrk4333k3k',
    '..kRrrrrk3332k3k',
    '..kRrrrrk3322k2k',
    '..krrrrxk2221kk.',
    '..kkkkkkkkkkkk..',
    '.k.k............',
    'kPk.kk..........',
    '.k..kRk.........',
  ]),
  // Кофе с собой — paper cup, sleeve, lid, steam.
  item_coffeeToGo: icon([
    '.......6........',
    '......65........',
    '.......56.......',
    '...kkkkkkkkkk...',
    '..kYYYYYkkYYyk..',
    '.kyyyyyyyyyyygk.',
    '.kkkkkkkkkkkkkk.',
    '..kWWwwwwwww4k..',
    '..kCCCcccccc4k..',
    '..kCcccccccc4k..',
    '..kCcccccccc4k..',
    '...kWwwwwwwqk...',
    '...kWwwwwwwqk...',
    '...kWwwwwwqqk...',
    '....kqqqqqqk....',
    '....kkkkkkkk....',
  ]),
  // Степлер — red stapler on a black base.
  item_stapler: icon([
    '................',
    '................',
    '................',
    '................',
    '....kkkkkkkkkk..',
    '..kkRPPPPPPPRrk.',
    '.kRRrrrrrrrrrr3k',
    'kRrrrrrrrrrrrr3k',
    'kxxxxxxxxxxxxxmk',
    '.kkkyyyyyyyykkk.',
    '...kGGGGGGGGkmk.',
    '.kkkkkkkkkkkkkk.',
    'kGGdddddddddddDk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ]),
  // Корректор — whiteout bottle with a brush cap.
  item_corrector: icon([
    '......kkkk......',
    '.....kGgdDk.....',
    '.....kGgdDk.....',
    '.....kGgdDk.....',
    '....kkkkkkkk....',
    '....kgyyyyGk....',
    '...kkkkkkkkkk...',
    '..kYYYYYYYYy4k..',
    '..kYYYYYYYyy4k..',
    '..k4444444433k..',
    '..k5YY5555443k..',
    '..k4444444332k..',
    '..kYyyyyyyyg4k..',
    '..kyyyyyyygGGk..',
    '...kkkkkkkkkk...',
    '................',
  ]),
  // Шредер — sheet goes in, noodles come out.
  item_shredder: icon([
    '....kkkkkkkk....',
    '....kWWWWWWqk...',
    '....kWgggggqk...',
    '....kWwwwwwqk...',
    '.kkkkkkkkkkkkkk.',
    'kGgggggggggggg3k',
    'kgkkkkkkkkkkkk3k',
    'kgggggggggggtg3k',
    'kdddddddddddddDk',
    '.kkkkkkkkkkkkkk.',
    '..kWkWkwkWkwk...',
    '..kWkWkwkWkqk...',
    '..kWk.kwkWk.k...',
    '..kwk.kqkwk.....',
    '..kqk..k.kqk....',
    '...k......k.....',
  ]),
  // Мегафон — white horn, red bell rim, sound waves.
  item_megaphone: icon([
    '................',
    '................',
    '.........kkk..5.',
    '.......kkRRk.5..',
    '.....kkWWRrk..5.',
    '..kkkWWWwwRk.5..',
    '.kGkWWwwwwrk..5.',
    '.kGkwwwwwwrk.5..',
    '.kGkqqqqqqxk..5.',
    '..kkkqqqqqxk....',
    '....kkkkqqxk....',
    '...kddk.kkxk....',
    '...kdDk...kk....',
    '...kddk.........',
    '....kk..........',
    '................',
  ]),
  // Коробка с сюрпризом — violet gift box, gold ribbon and bow.
  item_giftbox: icon([
    '................',
    '....kk....kk....',
    '...kZzk..kzak...',
    '...kzZzkkzZak...',
    '....kkzZZzkk....',
    '.kkkkkkaakkkkkk.',
    '.kIIIIIZzIIII3k.',
    '.kiiiiiZziiii3k.',
    '.kkkkkkkkkkkkkk.',
    '..kiiiiZziii3k..',
    '..kiiiiZziii3k..',
    '..kiiiiZziiVVk..',
    '..kVVVVZzVVVvk..',
    '..kVVVVazVVvvk..',
    '..kkkkkkkkkkkk..',
    '................',
  ]),
  // Игральный кубик — die with red and dark pips.
  item_dice: icon([
    '................',
    '....kkkkkkkkkk..',
    '...kWWWWWWWWYyk.',
    '..kWWWrWWWWYyyk.',
    '.kkkkkkkkkkkky4k',
    '.kYYYYYYYYYkyy4k',
    '.kYkkYYYYYYkyk4k',
    '.kYkkYYYYYYky44k',
    '.kYYYYkkYYYkkyyk',
    '.kYYYYkkYYYky44k',
    '.kYYYYYYkkYky4kk',
    '.kYYYYYYkkYky4k.',
    '.kyyyyyyyyykkk..',
    '.kkkkkkkkkkkk...',
    '................',
    '................',
  ]),
  // Швабра — wooden mop with grey strands.
  item_mop: icon([
    '.............kk.',
    '............kCck',
    '...........kCck.',
    '..........kCck..',
    '.........kCck...',
    '........kCck....',
    '.......kCck.....',
    '......kyGk......',
    '.....kygGGk.....',
    '....kkkkkkkk....',
    '...kWwwqwwq4k...',
    '..kWwwqwwqwq4k..',
    '..kWwqwwqwwqgk..',
    '.kWwqkwqkwqkqgk.',
    '.kwqk.kqk.kqkgk.',
    '..kk...k...k.kk.',
  ]),
};
