import type { SpriteDef } from '../sprite.ts';

/**
 * Floor pickups, 12×12. Frames: idle0, idle1 (glint / sparkle). Anchor: bottom centre (6, 11).
 * Warm pickups (coins, hearts, keys) get warm highlights; the soul heart glows cold.
 * Legend: same characters as render/art/items.ts.
 */
const legend: Record<string, string> = {
  '.': '',
  k: 'ink0', j: 'ink1', n: 'ink2', N: 'ink3',
  1: 'cold1', 2: 'cold2', 3: 'cold3', 4: 'cold4', 5: 'cold5', 6: 'cold6',
  '=': 'teal0', 7: 'teal1', 8: 'teal2', 9: 'teal3', t: 'teal4', T: 'teal5',
  0: 'vio0', v: 'vio1', V: 'vio2', i: 'vio3', I: 'vio4', l: 'vio5',
  M: 'red0', m: 'red1', x: 'red2', r: 'red3', R: 'red4', P: 'red5',
  U: 'orange1', u: 'orange2', o: 'orange3', O: 'orange4',
  A: 'gold1', a: 'gold2', z: 'gold3', Z: 'gold4', W: 'cream',
  '%': 'wood0', b: 'wood1', B: 'wood2', c: 'wood3', C: 'wood4',
  '&': 'green0', f: 'green1', F: 'green2', e: 'green3', E: 'green4',
  D: 'grey0', d: 'grey1', G: 'grey2', g: 'grey3', y: 'grey4', Y: 'white', w: 'paper', q: 'paper2',
  Q: 'skin0', S: 'skin1', s: 'skin2', L: 'skin3',
};

const pk = (idle0: string[], idle1: string[]): SpriteDef => ({
  w: 12,
  h: 12,
  legend,
  frames: { idle0, idle1 },
  ox: 6,
  oy: 11,
});

export const PICKUPS: Record<string, SpriteDef> = {
  pk_coin: pk(
    [
      '............',
      '............',
      '....kkkk....',
      '..kkZZZzkk..',
      '..kZWZzzak..',
      '.kZZzaazzak.',
      '.kZzaZzazak.',
      '.kzzazzazAk.',
      '.kzzzaazaAk.',
      '..kzzzzaAk..',
      '..kkaaAAkk..',
      '....kkkk....',
    ],
    [
      '.........W..',
      '........WYW.',
      '....kkkk.W..',
      '..kkZWZzkk..',
      '..kZWZzzak..',
      '.kZZzaazzak.',
      '.kZzaZzazak.',
      '.kzzazzazAk.',
      '.kzzzaazaAk.',
      '..kzzzzaAk..',
      '..kkaaAAkk..',
      '....kkkk....',
    ],
  ),
  pk_nickel: pk(
    [
      '....kkkk....',
      '..kk6666kk..',
      '.k66333355k.',
      '.k635YY534k.',
      'k6355YY5423k',
      'k63YYYYYY23k',
      'k635YYYY423k',
      'k534Y44Y423k',
      '.k53444423k.',
      '.k43222233k.',
      '..kk3333kk..',
      '....kkkk....',
    ],
    [
      '....kkkk..6.',
      '..kk6666k6Y6',
      '.k66333355k6',
      '.k635YY534k.',
      'k6355YY5423k',
      'k63YYYYYY23k',
      'k635YYYY423k',
      'k534Y44Y423k',
      '.k53444423k.',
      '.k43222233k.',
      '..kk3333kk..',
      '....kkkk....',
    ],
  ),
  pk_half: pk(
    [
      '............',
      '....kkk.....',
      '...kRPRk....',
      '...kPRrrk...',
      '...kRrrrxk..',
      '...kRrrrxk..',
      '....kRrrxk..',
      '.....krrxk..',
      '......krxk..',
      '.......kxk..',
      '........k...',
      '............',
    ],
    [
      '............',
      '....kkk.....',
      '...kYPRk....',
      '...kYRrrk...',
      '...kRrrrxk..',
      '...kRrrrxk..',
      '....kRrrxk..',
      '.....krrxk..',
      '......krxk..',
      '.......kxk..',
      '........k...',
      '............',
    ],
  ),
  pk_heart: pk(
    [
      '............',
      '..kkk...kkk.',
      '.kRPRk.kRrrk',
      '.kPRrrkrrrxk',
      '.kRrrrrrrrxk',
      '.kRrrrrrrrxk',
      '..kRrrrrrxk.',
      '...krrrrxk..',
      '....krrxk...',
      '.....kxk....',
      '......k.....',
      '............',
    ],
    [
      '............',
      '..kkk...kkk.',
      '.kYPRk.kRrrk',
      '.kYRrrkrrrxk',
      '.kRrrrrrrrxk',
      '.kRrrrrrrrxk',
      '..kRrrrrrxk.',
      '...krrrrxk..',
      '....krrxk...',
      '.....kxk....',
      '......k.....',
      '............',
    ],
  ),
  pk_soul: pk(
    [
      '............',
      '..kkk...kkk.',
      '.k565k.k544k',
      '.k6544k4443k',
      '.k544444423k',
      '.k544444423k',
      '..k5444443k.',
      '...k44443k..',
      '....k443k...',
      '.....k3k....',
      '......k.....',
      '............',
    ],
    [
      '..........6.',
      '..kkk...kk6Y',
      '.k6Y5k.k54k6',
      '.kY544k4443k',
      '.k544444423k',
      '.k544444423k',
      '..k5444443k.',
      '...k44443k..',
      '....k443k...',
      '.....k3k....',
      '......k.....',
      '............',
    ],
  ),
  pk_bomb: pk(
    [
      '.......CWO..',
      '......C.O...',
      '.....kGk....',
      '.....kkk....',
      '...kk2NNkk..',
      '...k25NNnk..',
      '..k23NNNn2k.',
      '..k2NNNNn2k.',
      '..kNNNNnn2k.',
      '...kNnnn2k..',
      '...kknnnkk..',
      '.....kkk....',
    ],
    [
      '.......C.W..',
      '......C.WZO.',
      '.....kGk.O..',
      '.....kkk....',
      '...kk2NNkk..',
      '...k25NNnk..',
      '..k23NNNn2k.',
      '..k2NNNNn2k.',
      '..kNNNNnn2k.',
      '...kNnnn2k..',
      '...kknnnkk..',
      '.....kkk....',
    ],
  ),
  pk_key: pk(
    [
      '...kkkk.....',
      '..kZZzak....',
      '.kZk..kak...',
      '.kzk..kAk...',
      '..kzaaAk....',
      '...kzak.....',
      '...kzak.....',
      '...kzakkk...',
      '...kzaZZk...',
      '...kzakkk...',
      '...kzaZk....',
      '....kkkk....',
    ],
    [
      '...kkkk...W.',
      '..kWZzak.WYW',
      '.kZk..kak.W.',
      '.kzk..kAk...',
      '..kzaaAk....',
      '...kzak.....',
      '...kZak.....',
      '...kzakkk...',
      '...kzaZZk...',
      '...kzakkk...',
      '...kzaZk....',
      '....kkkk....',
    ],
  ),
  pk_chest: pk(
    [
      '............',
      '............',
      '..kkkkkkkk..',
      '.kCCgCCCgck.',
      'kCccgcccgcBk',
      'kkkkkkkkkkkk',
      'kccgkZzkgcBk',
      'kccgkakkgBBk',
      'kcBgcBBcgBbk',
      'kBBgBBBBgbbk',
      'kbbGbbbbGbbk',
      '.kkkkkkkkkk.',
    ],
    [
      '..........W.',
      '.........WYW',
      '..kkkkkkkkW.',
      '.kCCgCCCgck.',
      'kCccgcccgcBk',
      'kkkkkkkkkkkk',
      'kccgkWzkgcBk',
      'kccgkakkgBBk',
      'kcBgcBBcgBbk',
      'kBBgBBBBgbbk',
      'kbbGbbbbGbbk',
      '.kkkkkkkkkk.',
    ],
  ),
  pk_lockedChest: pk(
    [
      '............',
      '............',
      '..kkkkkkkk..',
      '.kZZdZZZdzk.',
      'kZzzdzzzdzak',
      'kkkkkkkkkkkk',
      'kzzdkyykdzak',
      'kzzdkyGkdaak',
      'kzadkGkkdaak',
      'kaadkkkkdaAk',
      'kAAdAAAAdAAk',
      '.kkkkkkkkkk.',
    ],
    [
      '..........W.',
      '.........WYW',
      '..kkkkkkkkW.',
      '.kZWdZZZdzk.',
      'kZWzdzzzdzak',
      'kkkkkkkkkkkk',
      'kzzdkYykdzak',
      'kzzdkyGkdaak',
      'kzadkGkkdaak',
      'kaadkkkkdaAk',
      'kAAdAAAAdAAk',
      '.kkkkkkkkkk.',
    ],
  ),
};
