import type { SpriteDef } from '../sprite.ts';

/** Board icons, 18×18. Warm families: blade, coin. Cold: shield, ink. */
export const TILES: Record<string, SpriteDef> = {
  tile_blade: {
    w: 18,
    h: 18,
    ox: 9,
    oy: 9,
    legend: { '.': '', k: 'ink0', w: 'white', g: 'grey4', G: 'grey3', d: 'grey2', r: 'red3', R: 'red2', D: 'red1', o: 'orange4', c: 'cold5' },
    frames: {
      idle0: [
        '..............kkk.',
        '.............kwwgk',
        '............kwwgGk',
        '...........kwwgGk.',
        '..........kwwgGk..',
        '.........kwwgGk...',
        '........kwwgGk....',
        '.......kwwgGk.....',
        '..kk..kwwgGk......',
        '..krkkwwgGk.......',
        '..korkwgGk........',
        '...korkGk.........',
        '....korRk.........',
        '...kkorRDk........',
        '..korRkkRDk.......',
        '.korRk..kDk.......',
        '.kRDk....k........',
        '..kk..............',
      ],
    },
  },
  tile_shield: {
    w: 18,
    h: 18,
    ox: 9,
    oy: 9,
    legend: { '.': '', k: 'ink0', a: 'cold6', b: 'cold5', c: 'cold4', d: 'cold3', e: 'cold2', f: 'cold1', y: 'gold3', Y: 'gold4' },
    frames: {
      idle0: [
        '..................',
        '..kkkkkkkkkkkkkk..',
        '.kabbbbbbbbbbccdk.',
        '.kbccccccccccddek.',
        '.kbcccccyYcccddek.',
        '.kbccccyYYycccdek.',
        '.kbcccccyycccddek.',
        '.kbccccccccccddek.',
        '.kbccccccccccddek.',
        '.kbcccccccccdddek.',
        '..kbcccccccddeek..',
        '..kbccccccdddeek..',
        '...kbccccddeeek...',
        '....kbccddeefk....',
        '.....kbddeefk.....',
        '......kkeefk......',
        '........kkk.......',
        '..................',
      ],
    },
  },
  tile_ink: {
    w: 18,
    h: 18,
    ox: 9,
    oy: 9,
    legend: { '.': '', k: 'ink0', a: 'white', b: 'vio5', c: 'vio4', d: 'vio3', e: 'vio2', f: 'vio1' },
    frames: {
      idle0: [
        '........k.........',
        '.......kdk........',
        '.......kdk........',
        '......kcddk.......',
        '......kcdde.......',
        '.....kcdddek......',
        '....kccddddek.....',
        '....kcdddddek.....',
        '...kcaddddddek....',
        '...kbadddddddek...',
        '..kcbdddddddeek...',
        '..kcddddddddeek...',
        '..kcdddddddeeek...',
        '..kcddddddeeefk...',
        '...kdddddeeefk....',
        '....keeeeeefk.....',
        '.....kkkkkkk......',
        '..................',
      ],
    },
  },
  tile_coin: {
    w: 18,
    h: 18,
    ox: 9,
    oy: 9,
    legend: { '.': '', k: 'ink0', a: 'cream', b: 'gold4', c: 'gold3', d: 'gold2', e: 'gold1', o: 'orange2' },
    frames: {
      idle0: [
        '..................',
        '......kkkkkk......',
        '....kkbbbbccdk....',
        '...kbbccccccddk...',
        '..kbacccccccddek..',
        '..kbcccddddccdek..',
        '.kbccckeeeekcddek.',
        '.kbcccke..ekcddek.',
        '.kbcccke..ekcddek.',
        '.kbcccke..ekcddek.',
        '.kbcccke..ekcddek.',
        '.kbccckkkkkkcddek.',
        '..kccccddddcddek..',
        '..kcccccccccdeek..',
        '...kdcccccdddek...',
        '....kkddddeeek....',
        '......kkkkkk......',
        '..................',
      ],
    },
  },
  tile_prism: {
    w: 18,
    h: 18,
    ox: 9,
    oy: 9,
    legend: { '.': '', k: 'ink0', w: 'white', a: 'cold6', b: 'teal5', c: 'vio5', d: 'red5', e: 'gold4', f: 'cold4', g: 'vio4' },
    frames: {
      idle0: [
        '........kk........',
        '.......kwak.......',
        '......kwwabk......',
        '.....kwwaabbk.....',
        '....kwwaaabbbk....',
        '...kdwwaaabbbck...',
        '..kddwwaaabbbcck..',
        '.kdddeewaabbbccgk.',
        'kdddeeewwabbcccggk',
        '.kddeeewaabbcccgk.',
        '..kdeeewaabbccgk..',
        '...kdeeaabbccgk...',
        '....keeaabbcgk....',
        '.....keaabbcgk....'.slice(0, 18),
        '......kaabbgk.....',
        '.......kabbk......',
        '........kbk.......',
        '.........k........',
      ],
    },
  },
  tile_junk: {
    w: 22,
    h: 22,
    ox: 11,
    oy: 11,
    legend: { '.': '', k: 'ink0', a: 'vio2', b: 'vio1', c: 'vio0', d: 'ink1', e: 'vio3' },
    frames: {
      idle0: [
        '......................',
        '....kk.......kk.......',
        '...kbbk..kk.kbbk..k...',
        '....kbbkkbbkkbbk.kbk..',
        '.....kbbbbbbbbbkkbbk..',
        '..kk.kbbaabbbbbbbbk...',
        '.kbbkkbaaebbbbbbbk....',
        '.kbbbbbaebbbbbbcbk....',
        '..kbbbbbbbbbbbbccbkk..',
        '...kbbbbbbbbbbbcccbbk.',
        '...kbbbbbbbbbbbbccbbk.',
        '..kbbbbbbbbbbbbbbcbk..',
        '.kbbbbbbbbbbbbbbbbk...',
        '.kbbcbbbbbbbbbbbbbbk..',
        '..kkccbbbbbbbbbbbbbbk.',
        '....kccbbbbbbbbbcbbk..',
        '...kbkccbbbbbbbccbk...',
        '..kbbkkcccbbbbcckk....',
        '..kbk..kkccccckk......',
        '...k.....kkkkk.kk.....',
        '..............kbbk....',
        '...............kk.....',
      ],
    },
  },
  tile_staple: {
    w: 20,
    h: 8,
    ox: 10,
    oy: 4,
    legend: { '.': '', k: 'ink0', a: 'white', b: 'grey4', c: 'grey3', d: 'grey2' },
    frames: {
      idle0: [
        '.kkkkkkkkkkkkkkkkkk.',
        'kaabbbbbbbbbbbbbbbck',
        'kbccccccccccccccccdk',
        'kbk..............kdk',
        'kbk..............kdk',
        'kbk..............kdk',
        'kck..............kdk',
        '.k................k.',
      ],
    },
  },
  tile_ember: {
    w: 9,
    h: 11,
    ox: 4,
    oy: 10,
    legend: { '.': '', k: 'ink0', a: 'cream', b: 'gold4', c: 'orange3', d: 'orange2', e: 'red2' },
    frames: {
      idle0: [
        '....k....',
        '...kbk...',
        '...kbk...',
        '..kbcbk..',
        '.kbcbcek.',
        '.kcbabck.',
        'kdcbaabck',
        'kdcaaabck',
        'kedcbbcek',
        '.kedddek.',
        '..kkkkk..',
      ],
      idle1: [
        '.........',
        '....k....',
        '...kbk...',
        '..kbcbk..',
        '..kcbcek.',
        '.kcbabck.',
        'kdcbaabck',
        'kdcaaabck',
        'kedcbbcek',
        '.kedddek.',
        '..kkkkk..',
      ],
    },
  },

  // ── Queue beads (7×7): what falls next into each column. Native size, never scaled. ──
  tile_mini_blade: {
    w: 7,
    h: 7,
    ox: 3,
    oy: 3,
    legend: { '.': '', k: 'ink0', L: 'red5', M: 'red3', D: 'red1', w: 'white' },
    frames: { idle0: ['.kkkkk.', 'kLMMMwk', 'kMMMwDk', 'kMMwMDk', 'kMwMDDk', 'kMDDDDk', '.kkkkk.'] },
  },
  tile_mini_shield: {
    w: 7,
    h: 7,
    ox: 3,
    oy: 3,
    legend: { '.': '', k: 'ink0', L: 'cold5', M: 'cold3', D: 'cold1', y: 'gold4' },
    frames: { idle0: ['kkkkkkk', 'kLLLMMk', 'kLMyMDk', 'kMMMMDk', '.kMMDk.', '..kDk..', '...k...'] },
  },
  tile_mini_ink: {
    w: 7,
    h: 7,
    ox: 3,
    oy: 3,
    legend: { '.': '', k: 'ink0', L: 'vio5', M: 'vio3', D: 'vio1' },
    frames: { idle0: ['...k...', '..kMk..', '.kLMMk.', 'kLMMMDk', 'kMMMMDk', 'kMMMDDk', '.kkkkk.'] },
  },
  tile_mini_coin: {
    w: 7,
    h: 7,
    ox: 3,
    oy: 3,
    legend: { '.': '', k: 'ink0', L: 'gold4', M: 'gold3', D: 'gold1', o: 'orange2' },
    frames: { idle0: ['.kkkkk.', 'kLLMMMk', 'kLMooMk', 'kMoMoDk', 'kMooMDk', 'kMDDDDk', '.kkkkk.'] },
  },
  tile_mini_prism: {
    w: 7,
    h: 7,
    ox: 3,
    oy: 3,
    legend: { '.': '', k: 'ink0', w: 'white', a: 'cold6', b: 'teal5', c: 'vio5', d: 'red5', e: 'gold4' },
    frames: { idle0: ['...k...', '..kwk..', '.kdwbk.', 'kdewabk', '.keabk.', '..kck..', '...k...'] },
  },
  tile_mini_junk: {
    w: 7,
    h: 7,
    ox: 3,
    oy: 3,
    legend: { '.': '', k: 'ink0', a: 'vio2', b: 'vio1', c: 'vio0' },
    frames: { idle0: ['.k..kk.', 'kbkkbbk', 'kbaabbk', '.kbbbck', 'kbbbcck', 'kbccck.', '.kkkk..'] },
  },
  /** Anchor over a locked column (the anchor keeper). */
  tile_anchor: {
    w: 9,
    h: 10,
    ox: 4,
    oy: 9,
    legend: { '.': '', k: 'ink0', a: 'teal5', b: 'teal4', c: 'teal3', d: 'teal2' },
    frames: {
      idle0: [
        '...kkk...',
        '...kak...',
        '...kkk...',
        '.kkkbkkk.',
        '.kabbbck.',
        '.kkkbkkk.',
        'kk.kbk.kk',
        'kbkkbkkck',
        '.kbbbcck.',
        '..kkkkk..',
      ],
    },
  },
};
