import type { SpriteDef } from '../sprite.ts';

/**
 * UI kit (v3 office look): run-map pictograms for the «План эвакуации» sheet, tile cards,
 * HUD icons, pocket consumables, a few relics, memo panels, stamps and keycap buttons.
 * The game draws the paper, plan lines, dashed paths and all text itself.
 *
 * Shared legend: items.ts characters plus the office ramps
 *   h/H/J/K/X = slate0..slate4, p * + ^ = beige0..beige3, @ $ # = crt0..crt2.
 */
const L: Record<string, string> = {
  '.': '',
  k: 'ink0', j: 'ink1', n: 'ink2', N: 'ink3',
  '1': 'cold1', '2': 'cold2', '3': 'cold3', '4': 'cold4', '5': 'cold5', '6': 'cold6',
  '8': 'teal2', '9': 'teal3', t: 'teal4', T: 'teal5',
  '0': 'vio0', v: 'vio1', V: 'vio2', i: 'vio3', I: 'vio4', l: 'vio5',
  M: 'red0', m: 'red1', x: 'red2', r: 'red3', R: 'red4', P: 'red5',
  U: 'orange1', o: 'orange3', O: 'orange4',
  A: 'gold1', a: 'gold2', z: 'gold3', Z: 'gold4', W: 'cream',
  b: 'wood1', B: 'wood2', c: 'wood3', C: 'wood4',
  '&': 'green0', f: 'green1', F: 'green2', e: 'green3', E: 'green4',
  D: 'grey0', d: 'grey1', G: 'grey2', g: 'grey3', y: 'grey4', Y: 'white', w: 'paper', q: 'paper2',
  h: 'slate0', H: 'slate1', J: 'slate2', K: 'slate3', X: 'slate4',
  p: 'beige0', '*': 'beige1', '+': 'beige2', '^': 'beige3',
  '@': 'crt0', $: 'crt1', '#': 'crt2',
};

export const UI_KIT: Record<string, SpriteDef> = {
  // ── Run map «План эвакуации»: node pictograms 16×16 (boss 24×24), anchor centre. idle0 = normal, done = visited (pencil-grey, crossed out).
  map_fight: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '....k....k......',
        '...kWk..kWk.k...',
        '..kWWWkkWwwkqk..',
        '.kWW55q55wwqqqk.',
        'kWWwwqwwwwwwwqqk',
        'kWkkkwwwwwkkkqqk',
        'kWwjjkwwwkjjwqgk',
        'kwwjRwwqwwRjwqgk',
        'kwwwwwwqwwwwwqgk',
        '.kwqwkkkkkkwqqk.',
        '.kqqkjYjYjYkqgk.',
        '..kqqkkkkkkqqk..',
        '..kq44gqq44gqk..',
        '...kkgqqkkqgk...',
        '.....kkk..kk....',
      ],
      done: [
        '................',
        '....G....G......',
        '...GwG..GwG.G...',
        '..GJwwGGwwwGJG..',
        '.GwwJyyyywwJyyG.',
        'GwwwwJwwwwJwwyyG',
        'GwGGGwJwwJGGGyyG',
        'GwwGGGwJJGGGwyyG',
        'GwwGywwJJwyGwyyG',
        'GwwwwwJywJwwwyyG',
        '.GwywJGGGGJwyyG.',
        '.GyyJGwGwGwJyyG.',
        '..GJyGGGGGGyJG..',
        '..GyyyyyyyyyyG..',
        '...GGyyyGGyyG...',
        '.....GGG..GG....',
      ],
    },
  },
  map_elite: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '....k....k......',
        '...kWk..kWk.k...',
        '..kWWWkkWwwkqk..',
        '..kW55q55wwqqk..',
        '.kWkkwwwwwkkqqk.',
        '.kWwjkkwkkjwqqk.',
        '.kwwjOjwjOjwqgk.',
        '.kwwwwwqwwwwqgk.',
        '..kwkkkkkkkkqk..',
        '..kqkYkYkYkkgk..',
        '...kkkkkkkkkk...',
        '..kJHkWRrWkHhk..',
        '.kJJHkWrrWkHHhk.',
        'kJJHHHkrxkHHHhhk',
        'kJHHHHkrxkHHHhhk',
        'kkkkkkkkkkkkkkkk',
      ],
      done: [
        '....G....G......',
        '...GwG..GwG.G...',
        '..GwwwGGwwwGyG..',
        '..GJyyyyywwyJG..',
        '.GwGJwwwwwGJyyG.',
        '.GwwGJGwGGJwyyG.',
        '.GwwGyJwGJGwyyG.',
        '.GwwwwwJJwwwyyG.',
        '..GwGGGJJGGGyG..',
        '..GyGwJwGJGGyG..',
        '...GGJGGGGJGG...',
        '..GgJGwygwGJGG..',
        '.GgJgGwggwGgJGG.',
        'GgggggGggGgggGGG',
        'GgggggGggGgggGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
  },
  map_event: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '.........kkkkk..',
        '..kkkkkkkZZZzk..',
        '..kZZZZZZzzzzak.',
        '..kZzzznnnnzzak.',
        '..kZzznnzznnzak.',
        '..kZzzzzzznnzak.',
        '...kZzzzznnzzak.',
        '...kZzzznnzzzak.',
        '...kZzzznnzzzak.',
        '...kZzzzzzzzzak.',
        '...kZzzznnzzkkk.',
        '...kZzzznnzkZak.',
        '...kzaaaaaakaAk.',
        '...kkkkkkkkkkk..',
        '................',
      ],
      done: [
        '................',
        '.........GGGGG..',
        '..GGGGGGGwwwyG..',
        '..GJwwwwwyyyJyG.',
        '..GwJyyGGGGJyyG.',
        '..GwyJGGyyJGyyG.',
        '..GwyyJyyJGGyyG.',
        '...GwyyJJGGyyyG.',
        '...GwyyJJGyyyyG.',
        '...GwyJyGJyyyyG.',
        '...GwJyyyyJyyyG.',
        '...GJyyyGGyJGGG.',
        '...JwyyyGGyGJyG.',
        '...GyyyyyyyGygG.',
        '...GGGGGGGGGGG..',
        '................',
      ],
    },
  },
  map_shop: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '.........kkkkk..',
        '.........k#$#k..',
        '.........k@@@k..',
        '...kkkkkkkkkkkk.',
        '..k^^^^^^^^^^+k.',
        '..k^k+k+k+k^+*k.',
        '.k^^^^^^^^^^+*k.',
        '.k^+k+k+k+k^+*k.',
        'k^^^^^^^^^^^+*pk',
        'kkkkkkkkkkkkkkkk',
        'k+kZZkzzkZzk+*pk',
        'k+kzakaakzak+*pk',
        'k**kkkkkkkkk**pk',
        'kkkkkkkkkkkkkkkk',
        '................',
      ],
      done: [
        '................',
        '.........GGGGG..',
        '.........GwgwG..',
        '...J.....GGGJG..',
        '...GJGGGGGGJGGG.',
        '..GyyJyyyyJyyyG.',
        '..GyGyJyGJGyyyG.',
        '.GyyyyyJJyyyyyG.',
        '.GyyGyGJJyGyyyG.',
        'GyyyyyJyyJyyyygG',
        'GGGGGJGGGGJGGGGG',
        'GyGwJGyyGwyJyygG',
        'GyGJyGyyGyyGJygG',
        'GyyGGGGGGGGGyygG',
        'GGGGGGGGGGGGGGGG',
        '................',
      ],
    },
  },
  map_rest: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '..........k.....',
        '.........k5k....',
        '........k454k...',
        '.......k5644k...',
        '.......k4433k...',
        '........k33k....',
        '...kkkkkkkkkk...',
        '..kYYYYYYYYYyk..',
        '..kk45533333kk..',
        '...kWwwwwwwqk...',
        '...kWwwwwwqgk...',
        '....kWwwwwqk....',
        '....kWwwwqgk....',
        '.....kWwwqk.....',
        '......kWgk......',
        '.......kk.......',
      ],
      done: [
        '..........G.....',
        '.........GyG....',
        '........GyyyG...',
        '...J...GywyyJ...',
        '....J..GyygJG...',
        '.....J..GgJG....',
        '...GGGJGGJGGG...',
        '..GwwwwJJwwwyG..',
        '..GGyyyJJgggGG..',
        '...GwwJwwJwyG...',
        '...GwJwwwwJyG...',
        '....JwwwwwyJ....',
        '...JGwwwwyyGJ...',
        '.....GwwwyG.....',
        '......GwyG......',
        '.......GG.......',
      ],
    },
  },
  map_treasure: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '.kkkkkkkkkkkkkk.',
        '.kXXXXXXXXXXXKk.',
        '.kXKKKKKKKKKKJk.',
        '.kXKkkkkkkkkKJk.',
        '.kzKkJJJJJJkKJk.',
        '.kXKkJyyyJJkKJk.',
        '.kXKkJyYkyJkzJk.',
        '.kXKkJykyyJkzJk.',
        '.kzKkJJyyJJkzJk.',
        '.kXKkJJJJJJkKJk.',
        '.kXKkkkkkkkkKJk.',
        '.kKKKKKKKKKKKJk.',
        '.kJJJJJJJJJJJHk.',
        '.kkHkkkkkkkkHkk.',
        '..kk........kk..',
      ],
      done: [
        '................',
        '.GGGGGGGGGGGGGG.',
        '.GyyyyyyyyyyygG.',
        '.GyJggggggggJgG.',
        '.GygJGGGGGGJggG.',
        '.GygGJggggJGggG.',
        '.GygGgJyyJgGggG.',
        '.GygGgyJJygGygG.',
        '.GygGgyJJygGygG.',
        '.GygGgJyyJgGygG.',
        '.GygGJggggJGggG.',
        '.GygJGGGGGGJggG.',
        '.GgJggggggggJgG.',
        '.GggggggggggggG.',
        '.GGgGGGGGGGGgGG.',
        '..GG........GG..',
      ],
    },
  },
  map_boss: {
    w: 24,
    h: 24,
    ox: 12,
    oy: 12,
    legend: L,
    frames: {
      idle0: [
        '...kkkkkkkkkkkkkkkkkk...',
        '...kXXXXXXXXXXXXXXXXk...',
        '...kXKKKKKKKKKKKKKKJk...',
        '...kXkkkkkkkkkkkkkkJk...',
        '...kXkCCCCCCCCCCCckJk...',
        '...kXkdGdBBBBBBBcbkJk...',
        '...kXkDdkkkkkkkkBbkJk...',
        '...kXkCBkZZZZZzkBbkJk...',
        '...kXkCBkZzzzzakBbkJk...',
        '...kXkCBkkkkkkkkBbkJk...',
        '...kXkCcBBBBBBBBcbkJk...',
        '...kXkCcccccccZzcbkJk...',
        '...kXkCcBBBBBBBBabkJk...',
        '...kXkCcBccccccBcbkJk...',
        '...kXkdGdccccccBcbkJk...',
        '...kXkDdBccccccBcbkJk...',
        '...kXkCcBBBBBBBBcbkJk...',
        '...kXkCbbbbbbbbbbbkJk...',
        '...kXkkkkkkkkkkkkkkJk...',
        '..kkXkORRRRRRRRRROkJkk..',
        '.kKKkPRrrrrrrrrrRPkkKKk.',
        '....PPRRrrrrrrRRPP......',
        '.....PPPRRRRRRPPP.......',
        '.......PPPPPPPP.........',
      ],
      done: [
        '...GGGGGGGGGGGGGGGGGG...',
        '...GyyyyyyyyyyyyyyyyG...',
        '...GygggggggggggggggG...',
        '...GyGGGGGGGGGGGGGGgG...',
        '...GyGggggggggggggGgG...',
        '...GyGgJggggggggJGGgG...',
        '...GyGGgJGGGGGGJgGGgG...',
        '...GyGggGJwwwwJGgGGgG...',
        '...GyGggGJyyyyJGgGGgG...',
        '...GyGggGGJGGJGGgGGgG...',
        '...GyGgggggJJggggGGgG...',
        '...GyGgggggJJgwygGGgG...',
        '...GyGggggJggJggyGGgG...',
        '...GyGgggJggggJggGGgG...',
        '...GyGgggJggggJggGGgG...',
        '...GyGGgJggggggJgGGgG...',
        '...GyGgJggggggggJGGgG...',
        '...GyGgGGGGGGGGGGGGgG...',
        '...GyGGGGGGGGGGGGGGgG...',
        '..GGyGGGGGGGGGGGGGGgGG..',
        '.GggG.............GGggG.',
        '........................',
        '........................',
        '........................',
      ],
    },
  },
  // ── Map furniture: «Вы здесь» pin (anchor = tip), compass rose, evacuation-plan signs.
  map_here: {
    w: 12,
    h: 16,
    ox: 6,
    oy: 15,
    legend: L,
    frames: {
      idle0: [
        '....kkkkk...',
        '..kkRPRrrkk.',
        '.kRPRrrrrrxk',
        '.kPRrkkkrrxk',
        '.kRrkYYWkrxk',
        '.kRrkYWWkrxk',
        '.kRrrkkkrxxk',
        '.kRrrrrrrxxk',
        '..kRrrrrrxk.',
        '..krrrrrxxk.',
        '...krrrrxk..',
        '...kxrrrxk..',
        '....kxrxk...',
        '....kxrxk...',
        '.....kxk....',
        '......k.....',
      ],
    },
  },
  map_compass: {
    w: 20,
    h: 20,
    ox: 10,
    oy: 10,
    legend: L,
    frames: {
      idle0: [
        '..........k.........',
        '.........kxk........',
        '.........kxk........',
        '........KKxKK.......',
        '......KK.kxk.KK.....',
        '.....K..kRxxk..K....',
        '....K...kRxxk...K...',
        '....K...kRxxk...K...',
        '...K.kkkYRxxYkkk.K..',
        '..kKkYYYYYxYYYYYkKk.',
        '.kYYYYYYYYkJJJJJJJJk',
        '..kKkJJJJJYJJJJJkKk.',
        '...K.kkkJYYJJkkk.K..',
        '....K...kYYJk...K...',
        '....K...kYYJk...K...',
        '.....K..kYYJk..K....',
        '......KK.kYk.KK.....',
        '........KKYKK.......',
        '.........kYk........',
        '.........kYk........',
      ],
    },
  },
  map_extinguisher: {
    w: 10,
    h: 10,
    ox: 5,
    oy: 5,
    legend: L,
    frames: {
      idle0: [
        '....kkkk..',
        '...kyyGkk.',
        '..kkkGkyk.',
        '.kdkRRrk..',
        '.kdkRPrxk.',
        '.kdkRrrxk.',
        '.kdkRrrxk.',
        '..kkRrrxk.',
        '...kxxxmk.',
        '...kkkkkk.',
      ],
    },
  },
  map_exit: {
    w: 14,
    h: 10,
    ox: 7,
    oy: 5,
    legend: L,
    frames: {
      idle0: [
        'kkkkkkkkkkkkkk',
        'kFFFFFFFFFFFFk',
        'kFFFFYYFFYYYYk',
        'kFFFFYYFFYffYk',
        'kFFYYYFYFYffYk',
        'kFFFFYYFFYffYk',
        'kFFFYFFYFYffYk',
        'kFFYFFFFYYffYk',
        'kFFFFFFFFFFFFk',
        'kkkkkkkkkkkkkk',
      ],
    },
  },
  // ── Tile cards 48×64, anchor top-left. Window 22×22 at (13,3): draw the 18×18 icon with its centre at (24,14). Title band x3..44 y26..34 (light text, centred at x 24, line top y 26). Body x3..44 y36..60 (dark text from x 5, 3 lines at 9 px pitch: line tops y 35, 44, 53; ~40 px ≈ 9 Tiny5 chars per line). The clip hole at x5..8 y4..7 is see-through.
  ui_card_blade: {
    w: 48,
    h: 64,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle0: [
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '.kRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRk.',
        'kRrrrrrrrrrrxxxxxxxxxxxxxxxxxxxxxxxrrrrrrrrrrrxk',
        'kRrrrrrrrrrrxkkkkkkkkkkkkkkkkkkkkkkRrrrrrRrrrrxk',
        'kRrrrrkkrrrrxkxxxxxxxxxxxxxxxxxxxMkRrrrrRrrrrrxk',
        'kRrrrk..kRrrxkxmmmmmmmmmmmmmmmmmmMkRrrrRrrrrrrxk',
        'kRrrrk..kRrrxkxmmmmmmmmmmmmmmmmmmMkRrrRrrrrrrrxk',
        'kRrrrrkkrrrrxkxmmmmmmmmmmmmmmmmmmMkRrRrrrrrrrrxk',
        'kRrrrrRRrrrrxkxmmmmmmmmmmmmmmmmmmMkRRrrrrrrrrrxk',
        'kRrrrrrrrrrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrrrrrrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrrrrrrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrrrrrrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrrrrrrRxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrrrrrRrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrrrrRrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrrrRrrRxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrrRrrRrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrrRrrRrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrRrrRrrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrRrrRrrrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrRrrRrrrrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrrRrrrrrrxkxmmmmmmmmmmmmmmmmmmMkRrrrrrrrrrrxk',
        'kRrrRrrrrrrrxkMMMMMMMMMMMMMMMMMMMMkRrrrrrrrrrrxk',
        'kRrRrrrrrrrrxkkkkkkkkkkkkkkkkkkkkkkRrrrrrrrrrrxk',
        'kRrrrrrrrrrrrRRRRRRRRRRRRRRRRRRRRRRRrrrrrrrrrrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrxk',
        'kRrMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMrxk',
        'kRrqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        '.kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk.',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      ],
    },
  },
  ui_card_shield: {
    w: 48,
    h: 64,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle0: [
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '.k44444444444444444444444444444444444444444444k.',
        'k4333333333322222222222222222222222333333333332k',
        'k433333333332kkkkkkkkkkkkkkkkkkkkkk433333433332k',
        'k43333kk33332k2222222222222222222Nk433334333332k',
        'k4333k..k4332k2111111111111111111Nk433343333332k',
        'k4333k..k4332k2111111111111111111Nk433433333332k',
        'k43333kk33332k2111111111111111111Nk434333333332k',
        'k433334433332k2111111111111111111Nk443333333332k',
        'k433333333332k2111111111111111111Nk433333333332k',
        'k433333333332k2111111111111111111Nk433333333332k',
        'k433333333332k2111111111111111111Nk433333333332k',
        'k433333333332k2111111111111111111Nk433333333332k',
        'k433333333342k2111111111111111111Nk433333333332k',
        'k433333333432k2111111111111111111Nk433333333332k',
        'k433333334332k2111111111111111111Nk433333333332k',
        'k433333343342k2111111111111111111Nk433333333332k',
        'k433333433432k2111111111111111111Nk433333333332k',
        'k433334334332k2111111111111111111Nk433333333332k',
        'k433343343332k2111111111111111111Nk433333333332k',
        'k433433433332k2111111111111111111Nk433333333332k',
        'k434334333332k2111111111111111111Nk433333333332k',
        'k433343333332k2111111111111111111Nk433333333332k',
        'k433433333332kNNNNNNNNNNNNNNNNNNNNk433333333332k',
        'k434333333332kkkkkkkkkkkkkkkkkkkkkk433333333332k',
        'k4333333333334444444444444444444444433333333332k',
        'k4311111111111111111111111111111111111111111132k',
        'k4311111111111111111111111111111111111111111132k',
        'k4311111111111111111111111111111111111111111132k',
        'k4311111111111111111111111111111111111111111132k',
        'k4311111111111111111111111111111111111111111132k',
        'k4311111111111111111111111111111111111111111132k',
        'k4311111111111111111111111111111111111111111132k',
        'k4311111111111111111111111111111111111111111132k',
        'k4311111111111111111111111111111111111111111132k',
        'k43NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN32k',
        'k43qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k43qwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww32k',
        'k4333333333333333333333333333333333333333333332k',
        '.k22222222222222222222222222222222222222222222k.',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      ],
    },
  },
  ui_card_ink: {
    w: 48,
    h: 64,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle0: [
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '.kIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIk.',
        'kIiiiiiiiiiiVVVVVVVVVVVVVVVVVVVVVVViiiiiiiiiiiVk',
        'kIiiiiiiiiiiVkkkkkkkkkkkkkkkkkkkkkkIiiiiiIiiiiVk',
        'kIiiiikkiiiiVkVVVVVVVVVVVVVVVVVVV0kIiiiiIiiiiiVk',
        'kIiiik..kIiiVkVvvvvvvvvvvvvvvvvvv0kIiiiIiiiiiiVk',
        'kIiiik..kIiiVkVvvvvvvvvvvvvvvvvvv0kIiiIiiiiiiiVk',
        'kIiiiikkiiiiVkVvvvvvvvvvvvvvvvvvv0kIiIiiiiiiiiVk',
        'kIiiiiIIiiiiVkVvvvvvvvvvvvvvvvvvv0kIIiiiiiiiiiVk',
        'kIiiiiiiiiiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiiiiiiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiiiiiiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiiiiiiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiiiiiiIVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiiiiiIiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiiiiIiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiiiIiiIVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiiIiiIiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiiIiiIiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiIiiIiiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiIiiIiiiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiIiiIiiiiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiiIiiiiiiVkVvvvvvvvvvvvvvvvvvv0kIiiiiiiiiiiVk',
        'kIiiIiiiiiiiVk00000000000000000000kIiiiiiiiiiiVk',
        'kIiIiiiiiiiiVkkkkkkkkkkkkkkkkkkkkkkIiiiiiiiiiiVk',
        'kIiiiiiiiiiiiIIIIIIIIIIIIIIIIIIIIIIIiiiiiiiiiiVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvviVk',
        'kIi000000000000000000000000000000000000000000iVk',
        'kIiqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwiVk',
        'kIiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiVk',
        '.kVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVk.',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      ],
    },
  },
  ui_card_coin: {
    w: 48,
    h: 64,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle0: [
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '.kZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZk.',
        'kZzzzzzzzzzzaaaaaaaaaaaaaaaaaaaaaaazzzzzzzzzzzak',
        'kZzzzzzzzzzzakkkkkkkkkkkkkkkkkkkkkkZzzzzzZzzzzak',
        'kZzzzzkkzzzzakaaaaaaaaaaaaaaaaaaabkZzzzzZzzzzzak',
        'kZzzzk..kZzzakaAAAAAAAAAAAAAAAAAAbkZzzzZzzzzzzak',
        'kZzzzk..kZzzakaAAAAAAAAAAAAAAAAAAbkZzzZzzzzzzzak',
        'kZzzzzkkzzzzakaAAAAAAAAAAAAAAAAAAbkZzZzzzzzzzzak',
        'kZzzzzZZzzzzakaAAAAAAAAAAAAAAAAAAbkZZzzzzzzzzzak',
        'kZzzzzzzzzzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzzzzzzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzzzzzzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzzzzzzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzzzzzzZakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzzzzzZzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzzzzZzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzzzZzzZakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzzZzzZzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzzZzzZzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzZzzZzzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzZzzZzzzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzZzzZzzzzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzzZzzzzzzakaAAAAAAAAAAAAAAAAAAbkZzzzzzzzzzzak',
        'kZzzZzzzzzzzakbbbbbbbbbbbbbbbbbbbbkZzzzzzzzzzzak',
        'kZzZzzzzzzzzakkkkkkkkkkkkkkkkkkkkkkZzzzzzzzzzzak',
        'kZzzzzzzzzzzzZZZZZZZZZZZZZZZZZZZZZZZzzzzzzzzzzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzak',
        'kZzbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbzak',
        'kZzqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwzak',
        'kZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzak',
        '.kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak.',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      ],
    },
  },
  ui_card_status: {
    w: 48,
    h: 64,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle0: [
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '.kyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyk.',
        'kyggggggggggGGGGGGGGGGGGGGGGGGGGGGGgggggggggggGk',
        'kyggggggggggGkkkkkkkkkkkkkkkkkkkkkkygggggyggggGk',
        'kyggggkkggggGkGGGGGGGGGGGGGGGGGGGDkyggggygggggGk',
        'kygggk..kyggGkGddddddddddddddddddDkygggyggggggGk',
        'kygggk..kyggGkGddddddddddddddddddDkyggygggggggGk',
        'kyggggkkggggGkGddddddddddddddddddDkygyggggggggGk',
        'kyggggyyggggGkGddddddddddddddddddDkyygggggggggGk',
        'kyggggggggggGkGddddddddddddddddddDkyggggggggggGk',
        'kyggggggggggGkGddddddddddddddddddDkyggggggggggGk',
        'kyggggggggggGkGddddddddddddddddddDkyggggggggggGk',
        'kyggggggggggGkGddddddddddddddddddDkyggggggggggGk',
        'kygggggggggyGkGddddddddddddddddddDkyggggggggggGk',
        'kyggggggggygGkGddddddddddddddddddDkyggggggggggGk',
        'kygggggggyggGkGddddddddddddddddddDkyggggggggggGk',
        'kyggggggyggyGkGddddddddddddddddddDkyggggggggggGk',
        'kygggggyggygGkGddddddddddddddddddDkyggggggggggGk',
        'kyggggyggyggGkGddddddddddddddddddDkyggggggggggGk',
        'kygggyggygggGkGddddddddddddddddddDkyggggggggggGk',
        'kyggyggyggggGkGddddddddddddddddddDkyggggggggggGk',
        'kygyggygggggGkGddddddddddddddddddDkyggggggggggGk',
        'kygggyggggggGkGddddddddddddddddddDkyggggggggggGk',
        'kyggygggggggGkDDDDDDDDDDDDDDDDDDDDkyggggggggggGk',
        'kygyggggggggGkkkkkkkkkkkkkkkkkkkkkkyggggggggggGk',
        'kygggggggggggyyyyyyyyyyyyyyyyyyyyyyyggggggggggGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygddddddddddddddddddddddddddddddddddddddddddgGk',
        'kygDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDgGk',
        'kygqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kygqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgGk',
        'kyggggggggggggggggggggggggggggggggggggggggggggGk',
        '.kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk.',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      ],
    },
  },
  // ── Rare overlay 48×64: gold foil over the outer ring, gilded window rim, corner brackets, gilded title-band ends. Draw it on top of any ui_card_*; idle1 = glint.
  ui_card_rare: {
    w: 48,
    h: 64,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle0: [
        '................................................',
        '..ZZZZWWZZZZZZZZWZZZZZZZZZZZZZWWZZZZZZZZZZZZZZ..',
        '.Z..........ZZzzzzzzzzzzzzzzzzzzzzza..........a.',
        '.Z.Zza......Z......................a......azZ.a.',
        '.Z.z........z......................a........z.a.',
        '.Z.a........z......................a........a.a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.W..........z......................a..........a.',
        '.W..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.W..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........aaaaaaaaaaaaaaaaaaaaaaaA..........a.',
        '.Z.Z........................................Z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.a........................................a.a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.W............................................a.',
        '.W............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.W............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
        '................................................',
      ],
      idle1: [
        '................................................',
        '..ZZZZWWZZZZZZZZWZZZZZWWYYWWZZWWZZZZZZZZZZZZZZ..',
        '.Z..........ZZzzzzzzzzzzzzzzzzzzzzza.....Z....a.',
        '.Z.Zza......Z......................a.....WazZ.a.',
        '.Z.z........z......................a...ZWYWZz.a.',
        '.Z.a........z......................a.....W..a.a.',
        '.Z..........z......................a.....Z....a.',
        '.Z..........z......................a.....Z....a.',
        '.W..........z......................a..........a.',
        '.W..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.W..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........z......................a..........a.',
        '.Z..........aaaaaaaaaaaaaaaaaaaaaaaA..........a.',
        '.Z.Z........................................Z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.z........................................z.a.',
        '.Z.a........................................a.a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.W............................................a.',
        '.W............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.W............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '.Z............................................a.',
        '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
        '................................................',
      ],
    },
  },
  // ── HUD icons 9×9, anchor centre (4,4).
  ui_hp: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        '.kkk.kkk.',
        'kRPRkRrrk',
        'kPRYkYrxk',
        'kRrr2rrxk',
        'kRr221rxk',
        '.kRr21xk.',
        '..kr1xk..',
        '...kxk...',
        '....k....',
      ],
    },
  },
  ui_armor: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        'kkkk.....',
        'k65kkkkk.',
        'k5666654k',
        'k5444443k',
        'k54YYy43k',
        'k4444432k',
        '.k44432k.',
        '..k432k..',
        '...kkk...',
      ],
    },
  },
  ui_charge: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        '...k...Z.',
        '..klk.ZWZ',
        '..kIk..Z.',
        '.kIiIk...',
        'kIlIiVk..',
        'klIiiVk..',
        'kIiiVvk..',
        '.kVVvk...',
        '..kkk....',
      ],
    },
  },
  ui_coin: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        '..kkkkk..',
        '.kZZZzak.',
        'kZWzzzzak',
        'kZzkkkzak',
        'kzzkakzAk',
        'kzzkkkzAk',
        'kzzzzzaAk',
        '.kaaaaAk.',
        '..kkkkk..',
      ],
    },
  },
  ui_mult: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        'kkk...kkk',
        'kPRk.kRrk',
        'kRrrkrrxk',
        '.krrrrxk.',
        '..krrxk..',
        '.kRrrrxk.',
        'kRrxkrrxk',
        'krxk.kxmk',
        'kkk...kkk',
      ],
    },
  },
  ui_deck: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        '...kkkkkk',
        '...k5443k',
        'kkkkkk43k',
        'kWWWwk43k',
        'kWwrwk32k',
        'kWrRrkkkk',
        'kWwrwqk..',
        'kwwwqqk..',
        'kkkkkkk..',
      ],
    },
  },
  ui_map: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        '...kkk...',
        'kkkqqqkkk',
        'kWWqqqwwk',
        'kWrqJqwwk',
        'kWWqqJwwk',
        'kWWqqqwek',
        'kWWqqqwwk',
        'kWWkkkwwk',
        'kkk...kkk',
      ],
    },
  },
  ui_pause: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        'kkkk.kkkk',
        'kWwk.kWwk',
        'kWqk.kWqk',
        'kWqk.kWqk',
        'kWqk.kWqk',
        'kWqk.kWqk',
        'kWqk.kWqk',
        'kwqk.kwqk',
        'kkkk.kkkk',
      ],
    },
  },
  ui_shard: {
    w: 9,
    h: 9,
    ox: 4,
    oy: 4,
    legend: L,
    frames: {
      idle0: [
        '.....kk..',
        '....kTTk.',
        '...kT6tk.',
        '..kT6Ytk.',
        '..kTttt9k',
        '.kTtt99k.',
        '.kt998k..',
        'k998kk...',
        'kkk......',
      ],
    },
  },
  // ── Pocket consumables 16×16, anchor centre (8,8).
  pocket_bomb: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '............Z...',
        '..........kwWO..',
        '........kkwqO...',
        '.....kkkygkk....',
        '...kk221gGk.....',
        '..k5522111k.....',
        '.k5Y522111Nk....',
        '.k55222111Nk....',
        'k22222111NNNk...',
        'k12221111NNNk...',
        'k1111111NNN3k...',
        '.k11111NNN3k....',
        '.k111NNNNN3k....',
        '..kNNNNN33k.....',
        '...kkNN3kk......',
        '.....kkk........',
      ],
    },
  },
  pocket_coffee: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '.....6....6.....',
        '....65...65.....',
        '.....56...56....',
        '....65...65.....',
        '................',
        '..kkkkkkkkkkkk..',
        '..kYYYYYYYYYyk..',
        '..kkBBcBBBBBkk..',
        '...kWwwwwwwqk...',
        '...kRrrrrrrxk...',
        '...kWwwwwwwqk...',
        '....kWwwwwqk....',
        '....kWwwwwqk....',
        '....kWwwwqqk....',
        '....kqqqqqqk....',
        '....kkkkkkkk....',
      ],
    },
  },
  pocket_eraser: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '................',
        '................',
        '......kkkkkkkk..',
        '.....kWPPPPPPPk.',
        '....kPPPPPPPPRk.',
        '...kPPPPPPPPRRk.',
        '..kkkkkkkkkkRrk.',
        '..kRRRRRRRRkrrk.',
        '..kRrrrrrrrkrxk.',
        '..kRrrrrrrrkxk..',
        '..kxxxxxxxxkk...',
        '..kkkkkkkkkk....',
        '............k...',
        '..........kPk.k.',
        '...........k.kRk',
      ],
    },
  },
  pocket_sticker: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '.......6655.....',
        '..kkkkk6655kkk..',
        '..kRRRRR66RRrk..',
        '..kRrrrrrrrrxk..',
        '..kRrrrWWrrrxk..',
        '..kRrrrWWrrrxk..',
        '..kRrrrWWrrrxk..',
        '..kRrrrWqrrrxk..',
        '..kRrrrrrrrrxk..',
        '..kRrrrWWrrrxk..',
        '..kRrrrqqrrkkk..',
        '..kRrrrrrrkPxk..',
        '..kRrrrrrrkxk...',
        '..kxxxxxxxkk....',
        '..kkkkkkkkk.....',
        '................',
      ],
    },
  },
  pocket_energy: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '.....kkkkkk.....',
        '....kYyyyygk....',
        '....kkkkkkkk....',
        '....kEeeeeFk....',
        '....kEeekZFk....',
        '....kEekZzFk....',
        '....kEkZzkFk....',
        '....kEkZZZkk....',
        '....kEekzkFk....',
        '....kEekZkFk....',
        '....kEekkeFk....',
        '....kEeeeeFk....',
        '....kkkkkkkk....',
        '....kyyyyygk....',
        '.....kkkkkk.....',
      ],
    },
  },
  // ── Relics 16×16, anchor centre (8,8), items.ts style (items.ts characters only).
  item_knife: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '.............kk.',
        '............kYyk',
        '...........kYygk',
        '...........kkkk.',
        '..........kYk...',
        '.........kYygk..',
        '........kYggk...',
        '.......kYygk....',
        '.....kkYygk.....',
        '....kGgzgk......',
        '....kZzzak......',
        '...kZzzak.......',
        '..kZzzak........',
        '.kZazak.........',
        '.kazak..........',
        '..kak...........',
      ],
    },
  },
  item_binderclip: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '....kkkkkkkk....',
        '....kYyyyyyk....',
        '....kykkkkgk....',
        '....kyk..kgk....',
        '....kyk..kgk....',
        '...kkykkkkgkk...',
        '...kgygggggGk...',
        '..kGdddddddDDk..',
        '..kGGddddddDDk..',
        '.kGddddddddDD2k.',
        '.kGddddddddDD2k.',
        'kGdddddddddDD22k',
        'kjjjjjjjjjjjjjjk',
        'kkkkkkkkkkkkkkkk',
        '................',
      ],
    },
  },
  item_inkpot: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '................',
        '................',
        '................',
        '.........kkk....',
        '.......kkYygk...',
        '......k6lyyk....',
        '.....k6YIigk....',
        '....k6YIiVvk....',
        '...k6YIiVvk..kk.',
        '...klIiVvk..kIlk',
        '....kiVvk...kiVk',
        '.....kvk.....kk.',
        '......k.........',
        '................',
        '................',
      ],
    },
  },
  item_poster: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '.kkkkkkkkkkkkkk.',
        '.kjjjjjjjjjjjjk.',
        '.kjOOOOOOOOOOjk.',
        '.kjOOOWWWOOOOjk.',
        '.kjoOZWWWZOoojk.',
        '.kjooZZZZZVoojk.',
        '.kjVViiiVVViijk.',
        '.kjvVVVvvVVVvjk.',
        '.kjjjjjjjjjjjjk.',
        '.kjjyyyyyyyjjjk.',
        '.kjjjgggggjjjjk.',
        '.kjjjjjjjjjjjjk.',
        '.kkkkkkkkkkkkkk.',
        '................',
        '................',
      ],
    },
  },
  item_coffeemachine: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '.kkkkkkkkkkkk...',
        '.kyyyyyyyyyyGk..',
        '.kGGGGGGGGGGdk..',
        '.kGGGGGGGk9tdk..',
        '.kGrGGGGGk99dk..',
        '.kGGGGGGGkkkdk..',
        '.kdddkkkddddDk..',
        '.kdk..kGk...kk..',
        '.kdk...6..6.....',
        '.kdk..6..6......',
        '.kdk.kkkkkk.....',
        '.kdk.kYYYykkk...',
        '.kdk.kYyyykyk...',
        '.kdkkkkkkkkkkk..',
        '.kyyyyyyyyyyGk..',
      ],
    },
  },
  item_pocketbag: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '................',
        '......kkkk......',
        '.....kCccBk.....',
        '.....kk..kk.....',
        '.kkkkkkkkkkkkkk.',
        'kCCCCCCCCCCCCcBk',
        'kCcccccccccccBbk',
        'kkkkkkZzkkkkkkkk',
        'kCcccckZakcccBbk',
        'kCccccckkccccBbk',
        'kcccCcccccccBBbk',
        'kcccccccccccBBbk',
        'kBcccccccccBBBbk',
        'kBBBBBBBBBBBBbbk',
        '.kkkkkkkkkkkkkk.',
        '................',
      ],
    },
  },
  item_stamprelic: {
    w: 16,
    h: 16,
    ox: 8,
    oy: 8,
    legend: L,
    frames: {
      idle0: [
        '......kkkk......',
        '.....kRPRrk.....',
        '.....kRrrxk.....',
        '......kxxk......',
        '......kCck......',
        '......kCck......',
        '....kkkCckkk....',
        '...kCCCCcccBk...',
        '...kcccccccBk...',
        '..kkkkkkkkkkkk..',
        '..kGyyyyyyyyGk..',
        '..kVVVVVVVVVVk..',
        '...kkkkkkkkkk...',
        '................',
        '................',
        '................',
      ],
    },
  },
  // ── Memo sheets, anchor top-left. Paper x0..w-3, y3..h-3 (2 px shadow right/bottom); paperclip over x6..12, y0..16 — start the first text line right of x 16 or below y 20; dog-ear bottom-right.
  ui_memo: {
    w: 120,
    h: 80,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle0: [
        '........kkk.............................................................................................................',
        '.......kyyyk............................................................................................................',
        '......kyk.kYk...........................................................................................................',
        'kkkkkkkYkkkykkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        'kWWWWWkYkkkykqWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk..',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkkkgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkykwkgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkykwkgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwkgggkwqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwkkkwwqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwqqqqqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqqqqqqqqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkkkkkkkkkkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqqqqykjjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqqqykjjjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqqykjjjj.',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqykjjjj..',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqykjjjj...',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqykjjjj....',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkykjjjj.....',
        'kWqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkkjjjj......',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjjjj.......',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj........',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.........',
      ],
    },
  },
  ui_memo_wide: {
    w: 200,
    h: 120,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle0: [
        '........kkk.............................................................................................................................................................................................',
        '.......kyyyk............................................................................................................................................................................................',
        '......kyk.kYk...........................................................................................................................................................................................',
        'kkkkkkkYkkkykkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        'kWWWWWkYkkkykqWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk..',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykykqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqqqqqqwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqwwwwwwwqqwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkykgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqwwwwwwwwwwwqqwwwwwwwwwwwwwwwqkjj',
        'kWwwwwkYkkkgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqwwwwwwwwwwwwwqqwwwwwwwwwwwwwwqkjj',
        'kWwwwwkykwkgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqwwwwwwwwwwwwwwwqqwwwwwwwwwwwwwqkjj',
        'kWwwwwkykwkgkqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwqkjj',
        'kWwwwwwkgggkwqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwqkjj',
        'kWwwwwwwkkkwwqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwqkjj',
        'kWwwwwwqqqqqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwwwwwqwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqqwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqqqqqqqqqqqkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkkkkkkkkkkkkjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqqqqqqykjjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqqqqqykjjjj',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqqqqykjjjj.',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqqqykjjjj..',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqqykjjjj...',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqqykjjjj....',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqqykjjjj.....',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkqykjjjj......',
        'kWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwqkykjjjj.......',
        'kWqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkkjjjj........',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjjjj.........',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj..........',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj...........',
      ],
    },
  },
  // ── Rubber-stamp imprints 40×20, anchor centre (20,10). Blank inside: the game writes ~6 caps (≤ 28 px) in the stamp colour (green2 / red2), label line top at sprite row 6 (anchor y − 4); clear rows 7..13, x 5..34.
  ui_stamp_ok: {
    w: 40,
    h: 20,
    ox: 20,
    oy: 10,
    legend: L,
    frames: {
      idle0: [
        '........................................',
        '...........................FFFFFFFFFFFF.',
        '.............FFFFFFFFFFFFFFFFFFFFFFFFFF.',
        '.FFFFFFF..FFFFFFFFFFFFFFFFF..........FF.',
        '.FFFFFFF..FFF..............FFFFFFFFF.FF.',
        '.FF..........FFFFFFFFFFFFFF........F.FF.',
        '.FF.FFFFFFFFF......................F.FF.',
        '.FF.F..............................F....',
        '.FF.F..............................F....',
        '.FF.F..............................F.ee.',
        '.FF.F..............................F.ee.',
        '.FF.F..............................F.ee.',
        '.FF.F..............................F.ee.',
        '.FF.F..............................F.ee.',
        '.FF.F......................FFFFFFFFF.ee.',
        '.FF.F........FFFFFFFFFFFFFF..........ee.',
        '.FF.FFFFFFFFF..............eeeeeeeeeeee.',
        '.FF..........FFFFFFFFFeeeeeeeeeeeeeeeee.',
        '.FFFFFFFFFFFFFFFFFFFFFeeeee.............',
        '.FFFFFFFFFFFF...........................',
      ],
    },
  },
  ui_stamp_no: {
    w: 40,
    h: 20,
    ox: 20,
    oy: 10,
    legend: L,
    frames: {
      idle0: [
        '........................................',
        '.xxxxxxxxxxxx...........................',
        '.xxxxxxxxxxxxxxxxxxxxxxxxxx.............',
        '.xx..........xxxxxxxxxxxxxxxxxxxxxxxxxx.',
        '.xx.xxxxxxxxx..............xxxxxxxxxxxx.',
        '.xx.x........xxxxxxxxxxxxxx..........xx.',
        '.xx.x......................xxxxxxxxx.xx.',
        '.xx.x..............................x.xx.',
        '....x..............................x.xx.',
        '....x..............................x.xx.',
        '.xx.x..............................x.xx.',
        '.xx.x..............................x.rr.',
        '.xx.x..............................x.rr.',
        '.xx.x..............................x.rr.',
        '.xx.xxxxxxxxx......................x.rr.',
        '.xx..........xxxxxxxxxxxxxx........x.rr.',
        '.xxxxxxxxxxxx..............xxxxxxxxx.rr.',
        '.xxxxxxxxxxxxxxxxxxxxxrrr............rr.',
        '.............xxxxxxxxxrrr...rrrrrrrrrrr.',
        '............................rrrrrrrrrrr.',
      ],
    },
  },
  // ── Keycap buttons 64×18, anchor top-left. Frames idle / hover / down. Face (label area) x2..61: idle/hover y1..12, down y3..14 (label +2 px). Beige: dark label (ink2). Red: cream label with red1 shadow.
  ui_button: {
    w: 64,
    h: 18,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle: [
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
        'kW^kkkk^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^kf&k^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^kkkk^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'k++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++k',
        'k**************************************************************k',
        'k**************************************************************k',
        'kppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppk',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.',
      ],
      hover: [
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        'kYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYWk',
        'kYWkkkkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+k',
        'kYwk#Ekwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'kYwkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'kYwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'kYwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'kYwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'kYwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'kYwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'kYwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'kYwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww+k',
        'k++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++k',
        'k**************************************************************k',
        'k**************************************************************k',
        'kppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppk',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.',
      ],
      down: [
        '................................................................',
        '................................................................',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
        'kW^kkkk^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^k#Ek^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^kkkk^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'kW^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^+k',
        'k++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++k',
        'kppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppk',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.',
      ],
    },
  },
  ui_button_red: {
    w: 64,
    h: 18,
    ox: 0,
    oy: 0,
    legend: L,
    frames: {
      idle: [
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        'kRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRk',
        'kRrkkkkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrkUmkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrkkkkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.',
      ],
      hover: [
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        'kPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPRk',
        'kPRkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRxk',
        'kPrkWZkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kPrkkkkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kPrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kPrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kPrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kPrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kPrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kPrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kPrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
        'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.',
      ],
      down: [
        '................................................................',
        '................................................................',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        'kRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRk',
        'kRrkkkkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrkWZkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrkkkkrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxk',
        'kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk',
        'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.',
      ],
    },
  },
};
